zalando/nakadi

nakadi/swagger.yaml
What is implemented all the time is event_type and metadata. To avoid misleading assumptions and confusion sync the swagger file with the implementation and the so far vision.
@v-stepanov @valgog @jkliff
=> Fixed #33. This definition was accidentally changed.

build.gradle, src/main/java/de/zalando/aruha/nakadi/domain/EventTypeSchema.java
It's better to implement it explicitly than implicitly. Adding a huge
dependency just for this fucntionality doesnt seem resoanable.
=> ARUHA-50 remove unnecessary dependencies

src/main/resources/application.yml
There are currently 2 major issues with the connection pool on the test
environment:
1. It tries to open too many connections with the database
2. It does not recover from a database restart (or a network problem)
In order to fix those issues, we are adding some checks and also
avoiding requesting too many connections during application boot.
It's not the most efficient solution, since it adds another query just to check for connection, but it's the most reliable and responsive solution.
Another approach would be to use `removeAbandoned` property http://tomcat.apache.org/tomcat-7.0-doc/jdbc-pool.html#Common_Attributes or even implementing some custom validation class.
I considered this approach to be sufficient by now.
=> ARUHA-97 Tune connection pool

src/acceptance-test/java/de/zalando/aruha/nakadi/repository/db/EventTypeDbRepositoryTest.java, src/acceptance-test/java/de/zalando/aruha/nakadi/webservice/EventTypeAT.java, src/main/java/de/zalando/aruha/nakadi/controller/EventTypeController.java, src/main/java/de/zalando/aruha/nakadi/domain/EventType.java, src/test/java/de/zalando/aruha/nakadi/controller/EventTypeControllerTest.java, src/test/java/de/zalando/aruha/nakadi/validation/EventBodyMustRespectSchema.java, src/test/java/de/zalando/aruha/nakadi/validation/JSONSchemaValidationTest.java, src/test/resources/sample-invalid-json-schema.json
In order to validate submitted events we need to make sure that each
`EventType` has a valid json-schema definition.
We are not to much strict on the schema data, e.g. if someone submits a
Swager definition, it should work just fine.
Examples of rejected schemas can be found in the added tests.
I also made a minor rename refactor in order to make it easier to compose error messages related to fields and to make our domain more similar to the API definition.
=> Aruha 61 validate persistency of schemas

src/acceptance-test/java/de/zalando/aruha/nakadi/webservice/UserJourneyAT.java, src/main/java/de/zalando/aruha/nakadi/controller/EventPublishingController.java, src/main/java/de/zalando/aruha/nakadi/validation/EventValidation.java, src/test/java/de/zalando/aruha/nakadi/controller/EventPublishingControllerTest.java, src/test/resources/sample-event-type-update.json, src/test/resources/sample-event-type.json
The purpose of this PR is to provide the simplest implementation
possible to the validation of event schema. It's not focused on
performance, which should be addressed in a future ticket.
=> aruha-63 validate event schema on publish

src/acceptance-test/java/de/zalando/aruha/nakadi/webservice/UserJourneyAT.java, src/main/java/de/zalando/aruha/nakadi/config/WebConfig.java
Disables suffix detection by Spring, e.g. ".htm", ".xml" or ".json". Hence, content-type negotiation via file type suffix isn't possible anymore. On the other hand, it's now possible to have `PathVariable`s containing a dot.
=> Fixes 138 Allow dots in event-type names

src/main/java/de/zalando/aruha/nakadi/config/JsonConfig.java
...that breaks the build if the compiler is configured to be restrictive.
Any better suggestion to get rid of that warning?
=> This unchecked cast causes a warning

src/acceptance-test/java/de/zalando/aruha/nakadi/webservice/UserJourneyAT.java, src/main/java/de/zalando/aruha/nakadi/config/RepositoriesConfig.java, src/main/java/de/zalando/aruha/nakadi/controller/EventTypeController.java, src/main/java/de/zalando/aruha/nakadi/repository/db/EventTypeCache.java, src/main/java/de/zalando/aruha/nakadi/validation/EventBodyMustRespectSchema.java, src/main/java/de/zalando/aruha/nakadi/validation/EventValidation.java, src/main/java/de/zalando/aruha/nakadi/validation/ValidationStrategy.java, src/test/java/de/zalando/aruha/nakadi/controller/EventTypeControllerTest.java, src/test/java/de/zalando/aruha/nakadi/utils/TestUtils.java, src/test/java/de/zalando/aruha/nakadi/validation/EventValidationTest.java, src/test/java/de/zalando/aruha/nakadi/validation/JSONSchemaValidationTest.java, src/test/resources/sample-event-type-update.json, src/test/resources/sample-event-type.json
This PR adds the idea of an effective schema. An effective schema is an schema that is aware of categories.
If the event type is of business category, then we should expect it to have "metadata" in the root of the every event.
If from data category, then we should expect to find `data_op`, `data_type` and `data` at the root. The later should contain the original `schema` as a value.
Do you think we should be strict about what fields are allowed at the root object of a data event?
If so, I could add an `additionalProperties: false` to it.
=> Aruha 108 category aware validation

api/nakadi-event-bus-api.yaml
In order to more precisely communicate partial success scenarios, we are
introducing 207 Multi-status code as a possible http response code.
In case all events have been published successfully, then we just return
200 with empty body, otherwise we provide detailed status information in
the form of an array of BatchItemResponse's.
We considered using 422 as a response answer but it just doesn't feel correct
since we could have a mix of successes and failures in the batch.
=> aruha-113 add multi-status code 207

build.gradle, src/main/java/de/zalando/aruha/nakadi/config/RepositoriesConfig.java, src/main/java/de/zalando/aruha/nakadi/validation/EventMetadataValidationStrategy.java, src/main/java/de/zalando/aruha/nakadi/validation/EventValidation.java, src/main/java/de/zalando/aruha/nakadi/validation/MetadataValidator.java, src/test/java/de/zalando/aruha/nakadi/validation/JSONSchemaValidationTest.java
The current validation rejects DateTimes with variable number of
millisecond digits (it's accepts only zero or 3 digits milliseconds strings).
It's better to use Joda validation since it handles such scenarios,
even though it accepts timezones without ":" which should be
invalid by the RFC 3339.
But it's better to accept such small variation than reject valid dates.
Fixes #185
=> Aruha 154 hotfix datetime validation

README.md
A change to the README was required to keep up to date with the new
bulk event publishing API.
=> aruha-112 improve readme with batch example

src/main/java/de/zalando/aruha/nakadi/controller/EventTypeController.java, src/main/java/de/zalando/aruha/nakadi/partitioning/PartitionResolver.java, src/test/java/de/zalando/aruha/nakadi/controller/EventTypeControllerTest.java, src/test/java/de/zalando/aruha/nakadi/partitioning/PartitionResolverTest.java
The partition strategy was not being validated on the update. So would
be possible to do stuff with PUT that is not possible on the POST. For
example, defining hash partition strategy without a
patition_key_fields. But this is not possible on POST.
This could cause 500 when publishing events to an event type with
inconsistent partition strategy data.
=> aruha-131 validate partition strategy on update

src/main/java/de/zalando/aruha/nakadi/domain/BatchItemResponse.java, src/test/java/de/zalando/aruha/nakadi/service/EventPublisherTest.java
Display `detail: null` could confuse users. Display empty string
instead.
=> aruha-112 don't display null detail

src/main/java/de/zalando/aruha/nakadi/config/JsonConfig.java
In the beginning of the project this JSONObjectSerializer was required
to map to and from JSONObject automatically due to a spring
misconfiguration.
Since then, this issue has been solved and it's no longer need to have
this module.
=> aruha-102 Cleanup object mapper

src/main/java/de/zalando/aruha/nakadi/domain/BatchItem.java, src/main/java/de/zalando/aruha/nakadi/domain/BatchItemResponse.java, src/test/java/de/zalando/aruha/nakadi/service/EventPublisherTest.java
In order to make it easier for producers to correlate a response with an
event we are setting the eid as a property in the batch item response.
=> aruha-181 Set eid in the response when present

README.md
Some Mac OS users had port issues while booting Nakadi locally.
These instructions should help then with the setup.
=> aruha-183 Improve documentation for mac os

src/acceptance-test/java/de/zalando/aruha/nakadi/webservice/EventStreamReadingAT.java, src/main/java/de/zalando/aruha/nakadi/controller/EventStreamController.java, src/main/java/de/zalando/aruha/nakadi/domain/CursorError.java, src/main/java/de/zalando/aruha/nakadi/exceptions/InvalidCursorException.java, src/main/java/de/zalando/aruha/nakadi/repository/TopicRepository.java, src/main/java/de/zalando/aruha/nakadi/repository/kafka/KafkaTopicRepository.java, src/test/java/de/zalando/aruha/nakadi/controller/EventStreamControllerTest.java, src/test/java/de/zalando/aruha/nakadi/repository/kafka/KafkaTopicRepositoryTest.java
Some users were confused when the provided offsets were resulting in
error. So instead of providing a boolean answer we now display more
detailed reasons for:
1. out of bounds offset
2. invalid offset value (nonnumerical nor "BEGIN")
3. empty partition
4. inexistent partition.
Also fixes #158
=> aruha-175 Improved error message for invalid offset streaming

api/nakadi-event-bus-api.yaml
@v-stepanov @rcillo @jkliff @antban
=> The description and example belong to the item and not to the array

src/main/java/de/zalando/aruha/nakadi/validation/EventValidation.java, src/test/java/de/zalando/aruha/nakadi/utils/TestUtils.java, src/test/java/de/zalando/aruha/nakadi/validation/JSONSchemaValidationTest.java, src/test/resources/product-event.json, src/test/resources/product-json-schema.json
Since we wrapping the original json schema inside a wrapper schema,
references to definitions in the root of the provided JSON were broken.
This commit fixes this issue by moving definitions to the root of the
wrapper json.
If there are other definitions at other levels of the provided json
schema, that would stil be an unsolved issue.
=> aruha-151 fix definitions on data change events

api/nakadi-event-bus-api.yaml
The format of the serialized string should follow the specified
"schema.type", as stated in the EventTypeSchema object definition.
=> aruha-184 fix schema doc

api/nakadi-event-bus-api.yaml
Trying to create an event type without any specified enrichment strategy
result in:
```
Failed to create event type end2end_monitor.test_invoked, code: 422,
message: {u'status': 422, u'type': u'http://httpstatus.es/422',
u'detail': u'must define metadata enrichment strategy', u'title':
u'Unprocessable Entity'}
```
But according to specs default enrichment_strategies is `metadata-enrichment`.
So in this PR we made it clear that enrichment strategy is required, when it
should specify it and why.
=> aruha-185 fix enrichment api documentation

api/nakadi-event-bus-api.yaml
The server accepts partition_key_fields as the field name for event type creation and not the advertised field partitioning_key_fields.
Fixes #258
=> Replace partitioning_key_fields with partition_key_fields.

api/nakadi-event-bus-api.yaml, src/test/java/de/zalando/aruha/nakadi/domain/BatchItemResponseTest.java
For #259. This changes the definition to declare lowercase strings for those fields and adds a test case to verify the JSON configuration is serializing lowercase values.
=> Match BatchItemResponse enum casing with API spec.

src/main/java/de/zalando/aruha/nakadi/controller/EventStreamController.java, src/main/resources/application.yml, src/test/java/de/zalando/aruha/nakadi/controller/EventStreamControllerTest.java
This changes the event stream response's content type from "text/plain" to "application/x-json-stream" to make it line up with the API definition. Possibly some discussion needed on the preferred content type for the stream before merging.
For #257
=> Return application/x-json-stream for an event stream.

api/nakadi-event-bus-api.yaml
This reflows the API definition text paragraphs to make it easier
to read. Formatting change only, no content is being edited.
Context: I've been doing some documentation work and comparing 
the api spec against the implementation, which means spending a 
lot of time reading the yaml file :)
=> Reflow API YAML file text to have a width of 100.

api/nakadi-event-bus-api.yaml
This removes the `validation_strategies` property from event
type, and the corresponding registry path to see validations
available in the installation. These features are not
implemented yet by the server, and they can be added back
when they're available.
For #287
=> ARUHA-242: Remove validation_strategies from the API yaml.

api/nakadi-event-bus-api.yaml
Follow up to 00448ed to lower case the metadata_enrichment and
json_schema enum values and align the code with the API
definition.
After this the only uppercase enums are the 4 letters used for the
`data_op` value (these match the implementation, which checks they
are uppercase when sent).
=> ARUHA-240: lower case some enums in the definition.

api/nakadi-event-bus-api.yaml
The `data_key_fields` isn't implemented in the code and setting it
stops event type creation. This removes the property from the API
definition for the moment; apart from breaking event type creation,
it's not a certainty the property will be used (there's a TBD in
the documentation).
For #272.
=> ARUHA-240: Remove data_key_fields from definition.

api/nakadi-event-bus-api.yaml
This fixes typos introduced in efd1ae6.
For #283
=> ARUHA-239: Fix indentation of descriptions.

api/nakadi-event-bus-api.yaml, src/main/java/de/zalando/aruha/nakadi/controller/EventStreamController.java, src/test/java/de/zalando/aruha/nakadi/controller/EventStreamControllerTest.java
In order to workaround the connection closing issue https://techjira.zalando.net/browse/ARUHA-196, where connections take a very long time (hours) to get closed when client disconnects due to
RST tcp package missing.
=> aruha-243 change default value of stream_timeout

api/nakadi-event-bus-api.yaml, src/main/java/de/zalando/aruha/nakadi/partitioning/HashPartitionStrategy.java, src/main/java/de/zalando/aruha/nakadi/util/JsonPathAccess.java, src/main/java/de/zalando/aruha/nakadi/validation/EventValidation.java, src/test/java/de/zalando/aruha/nakadi/partitioning/PartitionResolverTest.java, src/test/java/de/zalando/aruha/nakadi/utils/TestUtils.java, src/test/resources/sample-data-event.json
When defining `partition_key_fields` users expect that the lookup path
to be relative to the originally defined schema, but since Nakadi
manipulates the schema for DataChangeEvent's, we need to add this
special case in order to scope the path to the nested "data" field.
This ways users no longer need to prepend "data." to
partition_key_fields.
=> aruha-246 fix data change event partition

README.md
The validator service at online.swagger.io doesn't
return a content type, which seems to be confusing
github's image proxy. Removing it for now as it
looks broken.
For #224
=> Remove badge link to swagger validator.

README.md
Fixes #262 
This is a basic contributor section and doesn't cover a todo list or target issues mentioned in #262.
=> Add a Contributing section to the Readme.

api/nakadi-event-bus-api.yaml
ARUHA-247: Optimise API definition for swagger tooling.
This changes the API definition to help swagger ui and codegen tools. Because 
there are structural changes to the object definitions, the API version is 
bumped to 0.6.0. The API JSON format is *not* being changed, just how the 
objects represent the data:
- BusinessEvent and DataChangeEvent extend Event to make them available to
swagger codegen's api client as subclasses. This specific subclassing
technique for allOf allows codegen to subclass from Event but not do weird
stuff like remove fields in the subclass (it's fiddly, but works).
- Change how BusinessEvent and DataChangeEvent inline Metadata to make it
visible to swagger ui, and avoid redundant Java classes. Avoid "Inline"
anonymous objects in the ui.
- Change how …
=> ARUHA-247: Optimise API definition for swagger tooling.

src/main/java/de/zalando/aruha/nakadi/controller/EventTypeController.java, src/main/java/de/zalando/aruha/nakadi/domain/EventType.java, src/test/java/de/zalando/aruha/nakadi/controller/EventTypeControllerTest.java
In the API it's called "default_statistics" but it was implemented as "default_statistic" (without an "s")
@v-stepanov @rcillo @antban @jkliff
=> Fix field name of EventType

build.gradle
This has fixes that will allow legal schema processing that fails with 1.2.0, in particular number handling: https://github.com/everit-org/json-schema/issues/31
=> Upgrade org.everit.json.schema to 1.3.0.

.travis.yml
@v1ctor @adyach @antban please review
I temporary switch off codacy as repo.jpm4j.org is currently down and our build on travis fails.
=> ARUHA-282: switched off codacy

database/migration/R2016_07_12/aruha-253-fix-default-statistics.sql, src/acceptance-test/java/de/zalando/aruha/nakadi/webservice/EventTypeAT.java, src/main/java/de/zalando/aruha/nakadi/controller/EventTypeController.java, src/main/java/de/zalando/aruha/nakadi/domain/EventType.java, src/test/java/de/zalando/aruha/nakadi/controller/EventTypeControllerTest.java
During validation time the team decided to not release this change since it would be backwards incompatible and would require some downtime during rollout in order to execute database migrations.
We are going to provide an alternative implementation in order to smoothly rollout with no downtime.
=> Aruha 253 undo backward incompatible changes

database/nakadi/execute_db_scripts_in_container.sh
One user has a problem with running docker-compose.  The database update script runs sql scripts in reverse order for some reason.
=> ARUHA-299: postgres database update script does not work for ubuntu user

build.gradle, src/main/java/de/zalando/aruha/nakadi/validation/EventBodyMustRespectSchema.java, src/main/java/de/zalando/aruha/nakadi/validation/MetadataValidator.java, src/main/java/de/zalando/aruha/nakadi/validation/RFC3339DateTimeValidator.java, src/test/java/de/zalando/aruha/nakadi/validation/JSONSchemaValidationTest.java, src/test/java/de/zalando/aruha/nakadi/validation/RFC3339DateTimeValidatorTest.java, src/test/resources/product-event.json
Overriding default everit date-time validator by a correct
implementation of RFC3339 validation fixes #274 and another non reported
bug that allowed offset string without colon to be accepted.
=> aruha-262 fix date time validation once and for all

README.md
Even with Docker 1.12 out of beta the `network_mode: host` bug is still there: https://github.com/docker/docker/issues/22753#issuecomment-242711639
I'm also waiting for this to be fixed.
=> Still a docker/issues/22753 on Mac (1.12)

README.md
Nakadi doesn't work with some popular docker versions.
The documentation should mention that you need very recent versions of docker.
=> Clarify on required docker versions.

api/nakadi-event-bus-api.yaml
The indentation has been accidentally broken. I suggest using Intellij swagger plugin for those who had not yet installed it https://plugins.jetbrains.com/plugin/8347
=> aruha-190 fix broken indentation

api/nakadi-event-bus-api.yaml
The original idea for including an `id` property to cursors was to make
them identifiable, so to easy the task of
debugging (https://github.com/zalando/nakadi/pull/353#discussion_r76253962).
Although, up to now, no state is stored when delivering cursors to
clients. E.g. Nakadi doesn't keep track of what cursors have been delivered.
If we are going to identify cursors with an uuid, in order to recognise
such ID later, when a consumer commits it, it would be required to hold
such information in the server.
Since making the server statefull is not an option, we are removing this
field from the API definition. We believe that improving traceability and
easier debugging easy can be achieved by other means, as for example,
the newly added field `cursor_token`.
=> aruha-190 remove id from cursors

api/nakadi-event-bus-api.yaml
There is no way to be over specific on the meaning of this field. We use
the same approach in other parts of the API.
=> aruha-190 renaming event type property

build.gradle, docker-compose.yml, src/acceptance-test/java/org/zalando/nakadi/repository/kafka/KafkaRepositoryAT.java, src/acceptance-test/java/org/zalando/nakadi/webservice/hila/HilaAT.java, src/acceptance-test/java/org/zalando/nakadi/webservice/hila/HilaRebalanceAT.java, src/main/java/org/zalando/nakadi/config/NakadiSettings.java, src/main/java/org/zalando/nakadi/controller/SubscriptionStreamController.java, src/main/java/org/zalando/nakadi/service/subscription/StreamParameters.java, src/main/java/org/zalando/nakadi/service/subscription/state/StreamingState.java, src/main/resources/application.yml, src/main/resources/swagger.yaml, src/test/java/org/zalando/nakadi/controller/EventTypeControllerTest.java
This PR is part of bigger task. I'm merging it against a feature branch, so that I could get some early feedback and make reviewing easier. It includes:
Renaming window_size to max_uncommitted_size makes the API easier to
understand since it doesn't introduce any new terminology (window
concept is not present anywhere in the api so far).
We are also reducing the default amount to 10 since there are some
potentially large messages and a default of 100 would mean that
several megabytes would be streamed at once.
Allowing clients to control the commit_timeout implied in potentially
unlimited resource allocation in the server, leading to security and
operational problem.
We removed this parameter from the API but kept it as an application
configuration.
The default value was also changed to …
=> Aruha 338 stream parameters change

src/acceptance-test/java/org/zalando/nakadi/webservice/UserJourneyAT.java, src/test/resources/sample-event-type.json
These tests are manually executed against staging and sandbox
environment after deploying a new release.
Since we toggled this feature on in staging, this test has been broken
due to missing owning application.
=> aruha-123 fix user journey tests

README.md
It was pointing to https://github.com/api/nakadi-event-bus-api.yaml
=> Fix relative link to the API definition

Dockerfile
Since we removed "-Djava.security.egd=file:/dev/./urandom" from dockerfile endtrypoint it sometimes takes a lot of time for Nakadi to start in Docker (at least in my environment):
`INFO: Creation of SecureRandom instance for session ID generation using [SHA1PRNG] took [23,655] milliseconds.`
I suggest to return it back.
=> ARUHA-365: returned back pseudo random session id generation

build.gradle, src/acceptance-test/java/org/zalando/nakadi/repository/kafka/KafkaRepositoryAT.java, src/main/java/org/zalando/nakadi/Application.java, src/main/java/org/zalando/nakadi/config/NakadiSettings.java, src/main/java/org/zalando/nakadi/repository/kafka/KafkaSyncPostCommand.java, src/main/java/org/zalando/nakadi/repository/kafka/KafkaTopicRepository.java, src/main/resources/application.yml, src/test/java/org/zalando/nakadi/controller/EventTypeControllerTest.java, src/test/java/org/zalando/nakadi/repository/kafka/KafkaSyncPostCommandTest.java, src/test/java/org/zalando/nakadi/repository/kafka/KafkaTopicRepositoryTest.java
This change only for publishing events.
=> ARUHA-406: Avoid Kafka unavailability from cascading to Nakadi

src/acceptance-test/java/org/zalando/nakadi/webservice/BlockEventPublishingAT.java, src/main/java/org/zalando/nakadi/validation/SchemaEvolutionService.java, src/main/java/org/zalando/nakadi/validation/schema/CompatibilityModeChangeConstraint.java, src/test/java/org/zalando/nakadi/validation/SchemaEvolutionServiceTest.java, src/test/java/org/zalando/nakadi/validation/schema/CompatibilityModeChangeConstraintTest.java
This PR introduces rules for upgrading an existing FIXED event type schema to a COMPATIBLE schema.
=> aruha-404 allow for compatibility mode upgrade

src/acceptance-test/java/org/zalando/nakadi/repository/db/EventTypeDbRepositoryTest.java, src/main/java/org/zalando/nakadi/config/JsonConfig.java, src/test/java/org/zalando/nakadi/controller/SubscriptionControllerTest.java
In order to introduce some new fields to event types (compatibility mode
and schema versioning), I plan to first run a migration that would do
so.
But once we run this database migration that adds such fields to event
types, it would break the running version, since it would introduce new
fields that are not known to the current stack.
In order to avoid this incompatibilities, I will first release this
feature first, which ignores unknow attributes instead of breaking.
=> aruha-400 prepare for unknown attributes

src/main/java/org/zalando/nakadi/controller/SchemaController.java, src/main/java/org/zalando/nakadi/repository/db/SchemaRepository.java, src/main/java/org/zalando/nakadi/service/SchemaService.java, src/test/java/org/zalando/nakadi/controller/SchemaControllerTest.java
In this PR:
* return an EventTypeSchema instead of only the schema
* return 404 not found instead of 500 if the event type or the schema version does not exist
* return 400 bad request with details if the version number is invalid
* improved query handling in SchemaRepository
=> Aruha 402-1 bugfix view specific schema version

database/migration/aruha-400-schema-evolution.sql
It was incorrectly using `create_missing` parameter as `null`. This migration should set this value even if it's not present.
=> aruha-400 fix migration

src/main/resources/schema.json, src/test/resources/org/zalando/nakadi/validation/invalid-json-schema-examples.json
$ref have been accidentally blocked.
This bug actually reveals a core schema meta-schema definition
problem. I've extended the meta-schema definition to accept $ref.
=> aruha-509 fix bug with $ref

src/main/java/org/zalando/nakadi/controller/EventPublishingController.java
This PR fixes a bug in batch size reporting for batches with multi-byte characters. I don't think a unit test is necessary for this.
=> ARUHA-520 use getBytes(..) to report actual batch size

src/main/java/org/zalando/nakadi/controller/SubscriptionController.java, src/main/java/org/zalando/nakadi/service/subscription/SubscriptionService.java, src/main/java/org/zalando/nakadi/util/FeatureToggleService.java, src/main/java/org/zalando/nakadi/util/FeatureToggleServiceDefault.java, src/test/java/org/zalando/nakadi/controller/SubscriptionControllerTest.java
In order to migrate the database, we need to disable features that write
to the database, so that we can dump & restore consistently, without
loosing any data.
=> aruha-538 disable subscription creation

src/main/java/org/zalando/nakadi/validation/JsonSchemaEnrichment.java, src/test/resources/org/zalando/nakadi/validation/strict-validation.json
Additional properties should not be enforced when using composed
schemas since it would cause the rejection of all events different from
an empty json object.
=> aruha-515 do not enforce additionalProperties for composed schemas

README.md
The documentation does not specify how to choose the number of partitions when creating an event. This PR documents this process, and gives an example.
=> Document how to control the partition count

api/nakadi-event-bus-api.yaml
Uses a summarised version of the documentation in README.md.
=> ARUHA-483 Fix commit timeout description in API definition

src/main/java/org/zalando/nakadi/service/EventTypeService.java, src/test/java/org/zalando/nakadi/controller/EventTypeControllerTest.java
This feature toggle has been removed in
fc99630023d4b04e866348624e726aa299fa1d32 after being left abandoned for
several months. It ends up causing undesirable side effects and for that
reason I'm restoring it as a hotfix.
The definitive solution is yet to be presented. This is just hotfix.
=> aruha-576 hotfix feature toggle

src/main/java/org/zalando/nakadi/controller/EventStreamController.java, src/main/java/org/zalando/nakadi/repository/TopicRepository.java, src/main/java/org/zalando/nakadi/repository/kafka/KafkaFactory.java, src/main/java/org/zalando/nakadi/repository/kafka/KafkaTopicRepository.java, src/test/java/org/zalando/nakadi/controller/EventStreamControllerTest.java, src/test/java/org/zalando/nakadi/repository/kafka/KafkaTopicRepositoryTest.java
In order to use Kafka quota on a fine grained level, we are going to
identify consumers using a combination of application name and event
type name. This will guarantee that an application can stream up to the
default quota from a single partition, since Kafka quotas are
implemented per client-id per broker.
=> aruha-584 consumer quota

README.md
Currently the travis badge shows "build failing" even if it's just a feature branch with build problems. The badge should refer to the master branch to correctly show that the master builds are actually fine.
=> README: Point travis badge to master branch

api/nakadi-event-bus-api.yaml
In order to be able to reset cursor for given subscription we need api to be adjusted
=> aruha-600: api change for reseting subscription cursor

README.md
https://techjira.zalando.net/browse/ARUHA-723
The README (and likely the manual) state that only 1 event type can be used per subscription.
This is no longer the case.
=> ARUHA-723 Update README since we support multiple ETs in subscriptions

api/nakadi-event-bus-api.yaml, src/main/java/org/zalando/nakadi/controller/EventTypeController.java, src/main/java/org/zalando/nakadi/util/FeatureToggleServiceDefault.java, src/test/java/org/zalando/nakadi/controller/EventTypeControllerTest.java
[ARUHA-732
](https://techjira.zalando.net/browse/ARUHA-732)
* everyone should be able to delete events on staging
* only Aruha team should be able to delete events on live
* the API definition should reflect this
* this should be under a feature flag
=> Aruha 732 dont delete event types

api/nakadi-event-bus-api.yaml
Ticket link https://techjira.zalando.net/browse/ARUHA-531
Previous to Timelines, cursor's offsets used to be sequential Long
numbers as Strings, for example "00000123". Because of that, several
consumers used to convert such strings back into numbers, our example
above would be converted to 123, and later use them as numbers for
several purposes.
One of the things consumers used to do was to query for `/partitions`
endpoint to get the newest available offset and then calculate the
distance between the newest and the latest consumed offset. This is how
many consumers from low level API would detect lag in consumer.
After introducing timelines, it will be no longer possible to easily
convert an offset to a number and perform such operations on the client
side. For that reason, we are …
=> ARUHA-541 consumer lag monitoring endpoint

api/nakadi-event-bus-api.yaml
This commit clarifies on subscription stats object about
unconsumed_events property absence
=> aruha-815: changed description of the stats object

src/main/java/org/zalando/nakadi/domain/ConsumedEvent.java, src/main/java/org/zalando/nakadi/repository/kafka/KafkaFactory.java, src/main/java/org/zalando/nakadi/repository/kafka/KafkaLocationManager.java, src/main/java/org/zalando/nakadi/repository/kafka/KafkaTopicRepository.java, src/main/java/org/zalando/nakadi/repository/kafka/NakadiKafkaConsumer.java, src/main/java/org/zalando/nakadi/service/EventStream.java, src/main/java/org/zalando/nakadi/service/EventStreamWriter.java, src/main/java/org/zalando/nakadi/service/EventStreamWriterBinary.java, src/main/java/org/zalando/nakadi/service/EventStreamWriterString.java, src/test/java/org/zalando/nakadi/repository/kafka/NakadiKafkaConsumerTest.java, src/test/java/org/zalando/nakadi/service/EventStreamTest.java, src/test/java/org/zalando/nakadi/service/subscription/state/PartitionDataTest.java
*This is a complimentary PR. It was not implemented in the original one and is out of the scope of the task. But I felt like it would be a valuable contribution.*
In order to reduce the unecessary allocation of String objects, we are
going to adopt Kafka byte array deserializer on the consumption path.
We expect to alleviate GC with this change.
=> aruha-840 use Kafka byte array deserializer

.gitignore, .idea/codeStyleSettings.xml
Looking at many PRs in our repo, there is a lot of unnecessary movements of imports. IDEA allows to export code style difference between your settings and IDEA. I decided to finish it exporting my idea code style diff.
So lets try to adopt that format to avoid huge import movements.
=> Code style diff file

src/main/java/org/zalando/nakadi/enrichment/MetadataEnrichmentStrategy.java, src/test/java/org/zalando/nakadi/enrichment/MetadataEnrichmentStrategyTest.java
Nakadi used to expect the flow_id to be taken from a header but not even
a single user was happy that their flow_id has been
overriten. E.g. users do not expect their event to be changed if they
are sending something already.
It's also a general guideline from Nakadi, not to "enrich" events,
always favoring user defined data. We do not change users data and this
bug broke this commitment.
Fixes #391
=> Do not override flow_id when present

CONTRIBUTING.md, MAINTAINERS
This PR adds a new CONTRIBUTING.md file, which provides information
for new contributors on how to get started. This file is adapted from
Skipper's version
(https://github.com/zalando/skipper/blob/master/CONTRIBUTING.md)
This PR also updates the list of contributors.
=> Update Maintainers list and provide information for contributors

api/nakadi-event-bus-api.yaml, src/main/java/org/zalando/nakadi/controller/CursorOperationsController.java, src/main/java/org/zalando/nakadi/exceptions/runtime/InvalidCursorOperation.java, src/main/java/org/zalando/nakadi/service/CursorOperationsService.java, src/main/java/org/zalando/nakadi/service/subscription/SubscriptionService.java, src/test/java/org/zalando/nakadi/service/CursorOperationsServiceTest.java
We got some early feedback that it would be more useful for users to get
negative distance as a result instead of just an error. This way they
don't need to order cursors on their side before querying Nakadi.
=> aruha-858 allow calculation of negative distances

api/nakadi-event-bus-api.yaml
[ARUHA-654: Update API documentation in nakadi-manual](https://techjira.zalando.net/browse/ARUHA-654)
The was some errors in Nakdi Open API(swagger) file 
that prevent building API part of Nakadi manual.
The command  `swagger2markup-cli` was failing with the exception:
```
Exception in thread "main" java.lang.NullPointerException: property must not be null
at org.apache.commons.lang3.Validate.notNull(Validate.java:222)
at io.github.swagger2markup.internal.adapter.PropertyAdapter.<init>(PropertyAdapter.java:40)
at io.github.swagger2markup.internal.utils.ModelUtils.getType(ModelUtils.java:120)
at io.github.swagger2markup.internal.adapter.ParameterAdapter.getType(ParameterAdapter.java:163)
at io.github.swagger2markup.internal.adapter.ParameterAdapter.<init>(ParameterAdapter.java:57)
at ... …
```
=> ARUHA-654: Fix swagger format to build manual

CHANGELOG.md, api/nakadi-event-bus-api.yaml
ARUHA-654:Update API documentation in nakadi-manual
If summary present in the OpenAPI file the swagger2markdown uses the summary instead of endpoint name as an anchor.
The script that generates Index files uses only the endpoint name.
It is better to unify the API and use "description" everywhere.
=> ARUHA-654: Fix. OpenAPI creates broken link in the Nakadi manual.

CHANGELOG.md, api/nakadi-event-bus-api.yaml
ARUHA-906: Merge Documentation
https://techjira.zalando.net/browse/ARUHA-906
Tha parser was failing to parse this part of swagger in CursorDistanceResult.
The ident level was wrong.
=> ARUHA-906: Fix wrong formatting in swagger

CHANGELOG.md
Updated kafka client version due to migration
[ARUHA-876: Upgrade Nakadi Kafka client to 0.10.1.0](https://techjira.zalando.net/browse/ARUHA-876)
Updated kafka client due to migration
=> aruha-876: updated kafka client version

CHANGELOG.md, build.gradle, src/main/java/org/zalando/nakadi/config/JettyConfig.java, src/main/resources/application.yml
[ARUHA-1083: Deploy Nakadi with Jetty](https://techjira.zalando.net/browse/ARUHA-1083)
This PR replaces Tomcat by Jetty as the default servlet container. The main motivation is to solve a rare but critical concurrency bug that could lead to wrong event delivery. The investigation is detailed in this [postmortem](https://docs.google.com/document/d/1d1ryipAuUGUqOYAfZBhQZRiQTT5BnVce4BOiHJU61vM/edit).
As a positive side effect, we also observed much lower CPU usage with Jetty.
No special deployment instruction. But since it changes a significant component, we should first try it with a smaller part of traffic before shipping to all users.
=> aruha-1083 change Tomcat by Jetty

CHANGELOG.md, src/main/java/org/zalando/nakadi/config/JettyConfig.java, src/main/resources/application.yml
This is a continuation from https://github.com/zalando/nakadi/pull/732
By default, Jetty output stream flushing behaves differently from Tomcat
when using compression. Calling flush would not cause the actual bytes
to be immediately flushed. This change in behaviour introduced a
problem, where subscription consumers would not get batches on time in
order to commit them. This way, their connections would be constantly
closed and they were not able to make progress.
With this change, all batches are flushed to the wire at the exact same
time as they used to be before switching to Jetty.
=> aruha-1083 fix gzip flush

docs/_documentation/using_clients.md
The [`go-nakadi`](https://github.com/stoewer/go-nakadi) package provides a Nakadi client library for the Go programming language. Although the project is rather new, the client still provides a feature rich and well tested API. It would be great if the Nakadi maintainers could have a look at the `go-nakadi` package and add it to the list of available clients in Nakadi's documentation. Every feedback on `go-nakadi` is very welcome.
Just an amendment for the documentation, nothing special here.
=> Add go-nakadi library to the list of Nakadi clients

docs/_documentation/using_clients.md
[ARUHA-751: Add Nakadi Client Library for Haskell to the Manual](https://github.com/zalando/nakadi/issues/751)
Documentation improvement. Mentions another Nakadi client library.
n/a
=> #751 Mention nakadi-client for Haskell in the manual

src/main/java/org/zalando/nakadi/controller/EventPublishingController.java
This is part of https://techjira.zalando.net/browse/ARUHA-1242
By adding event type and the name of the "user" publishing, we are able
to easily identify top publishing applications using scalyr.
We already expose this data in our /metrics endpoint, but as we all know
very well, it has more than 2MB and zmon is just not able to handle it,
specially when running 400 instances for Black Friday.
On the other hand, scalyr, when properly used, is reliable and
performant.
I'm gonna use this new information to identify event types that would
require repartitioning for Black Friday.
It will require a modification in scalyr parser in order to properly extract the new fields and make queries faster.
=> aruha-1242 add event type and application to SLO log

CHANGELOG.md, src/main/java/org/zalando/nakadi/service/job/TimelineCleanupJob.java, src/main/resources/application.yml, src/test/java/org/zalando/nakadi/service/job/TimelineCleaningJobTest.java
[ARUHA-1203: Fix massive topic deletion]
Kafka may go down in case of deletion of many topics. 
To avoid that while switching timelines the timeout added between deletions
Just deploy it
=> ARUHA-1203 Add delay (by default 2 seconds) between deletion of topics

CHANGELOG.md, docs/_data/nakadi-event-bus-api.yaml, src/main/java/org/zalando/nakadi/service/EventStreamConfig.java, src/main/java/org/zalando/nakadi/service/subscription/StreamParameters.java, src/main/java/org/zalando/nakadi/service/subscription/state/StreamingState.java, src/test/java/org/zalando/nakadi/controller/EventStreamControllerTest.java, src/test/java/org/zalando/nakadi/service/EventStreamConfigBuilderTest.java, src/test/java/org/zalando/nakadi/service/subscription/StreamParametersTest.java
[ARUHA-1316: Limit stream_timeout for LoLA and HiLA](https://techjira.zalando.net/browse/ARUHA-1316)
Limited stream timeout to 1h ±10min.
We should watch carefully in a case it brings problems to our users.
=> ARUHA-1316: added default stream_timeout;

docs/_documentation/using_clients.md
[ARUHA-776: Name of ticket](https://github.com/zalando/nakadi/issues/776)
I've dropped the entry listing Peek client as the project URL is dead.
None
=> Dropped no-longer existing Peek client

src/main/java/org/zalando/nakadi/service/subscription/zk/NewZkSubscriptionClient.java
[ARUHA-1340: Remove a lot of logging from cursors commit]
Right now on cursor commit nakadi logs full topology. This is not needed at all. Removed.
=> ARUHA-1340 Remove topology logging on cursors commit

CHANGELOG.md, src/acceptance-test/java/org/zalando/nakadi/webservice/hila/SubscriptionAT.java, src/main/java/org/zalando/nakadi/exceptions/runtime/UnknownStorageTypeException.java, src/main/java/org/zalando/nakadi/repository/TopicRepository.java, src/main/java/org/zalando/nakadi/repository/kafka/KafkaTopicRepository.java, src/main/java/org/zalando/nakadi/service/CursorOperationsService.java, src/test/java/org/zalando/nakadi/controller/SubscriptionControllerTest.java, src/test/java/org/zalando/nakadi/service/CursorOperationsServiceTest.java, src/test/java/org/zalando/nakadi/utils/TestUtils.java
ARUHA-1347: /stats returns 500s, after Kafka cluster is removed
In this PR, we do not try to create a TopicRepository when calling /stats, which fails when the cluster has been deleted.
This PR is a quick fix. A more thorough refactoring of Cursors should be planned
=> Aruha 1347 - do not fail when getting subscriptions stats with deleted storage

docs/_data/nakadi-event-bus-api.yaml
Clarify what values one should specify for stream starts - this part does
not seem to had been documented elsewhere.
Document use of begin/end as placeholders for stream offset start.
=> Clarify documentation beginning offset values

CHANGELOG.md, src/main/java/org/zalando/nakadi/service/subscription/state/StartingState.java, src/main/java/org/zalando/nakadi/service/subscription/state/StreamingState.java, src/test/java/org/zalando/nakadi/service/subscription/StartingStateTest.java, src/test/java/org/zalando/nakadi/service/subscription/state/StreamingStateTest.java
https://techjira.zalando.net/browse/ARUHA-1387
This PR optimizes the initialization of streams with a large number of event types. It does so by reducing the amount of requests made to Kafka in order to get the first and last available offsets.
Before this PR, for a subscription with 50 event types, it would request Kafka 50 times (or 100 in case of first usage). This would cause streams to not send data for several seconds. This delay in start would cause clients to trigger "Read Timeouts". In extreme situations, they would not be able to read anything and would have to retry several times until the request is served by a less loaded instance which would execute all this requests more quickly.
The optimization is not about object allocation, usage of streams or anything else. It's about …
=> Aruha 1387 faster stream initialization

docs/_documentation/faq.md
Also it is not clear what this phrase means "Because Nakadi has exclusive offset handling,".
I would probably remove this altogether and only said that newest_available_offset always holds offset of the latest received event even if all events are expired.
=> Correct FAQ section title

CHANGELOG.md, src/main/java/org/zalando/nakadi/service/subscription/zk/AbstractZkSubscriptionClient.java
[ARUHA-1388: Subscription is locked in ZK]
There is an unreproducable bug in curator library with obtaining a lock with this actions: 
1. Create lease
2. Loose zk connection
3. Try to delete lease and fail
It is impossible to reproduce, and it is really really really rare. 
In order to reduce the impact on system because of this bug and provide log entries to filter on, we will just log it for further investigation.
=> Add timeout for subscription locking

CHANGELOG.md, src/main/java/org/zalando/nakadi/controller/EventPublishingController.java, src/main/java/org/zalando/nakadi/filters/LoggingFilter.java, src/main/java/org/zalando/nakadi/service/NakadiKpiPublisher.java, src/main/resources/application.yml, src/test/java/org/zalando/nakadi/controller/EventPublishingControllerTest.java, src/test/java/org/zalando/nakadi/service/NakadiKpiPublisherTest.java
https://techjira.zalando.net/browse/ARUHA-1401
Collecting data necessary to calculate event publishing KPIs. Further details can be found in the data modeling document https://docs.google.com/document/d/1d4Z4FzSSrVCl2oy2G-bAPEcFbyAed_ZOxQqzr2rBGpw/edit#heading=h.c9gt0cqkozqy
It was necessary to refactor out the `hash` computation so that it could
be reused.
The corresponding event type should be created in the targeted deployment environments.
=> aruha-1399 collect event publishing KPI

docs/_data/nakadi-event-bus-api.yaml, src/acceptance-test/java/org/zalando/nakadi/webservice/EventStreamReadingAT.java, src/main/java/org/zalando/nakadi/controller/EventStreamController.java, src/main/java/org/zalando/nakadi/service/EventStream.java, src/main/java/org/zalando/nakadi/service/EventStreamConfig.java, src/main/java/org/zalando/nakadi/service/subscription/StreamingContext.java, src/main/java/org/zalando/nakadi/service/subscription/SubscriptionStreamerFactory.java, src/main/java/org/zalando/nakadi/service/subscription/state/PartitionData.java, src/main/java/org/zalando/nakadi/service/subscription/state/StreamingState.java, src/main/resources/application.yml, src/test/java/org/zalando/nakadi/controller/EventStreamControllerTest.java
[ARUHA-1442: Limit memory consumption of subscription streamer to 50 Mb](link to ticket)
Now single subscription stream can kill nakadi with not wisely set streaming configuration parameters. 
This PR allows to collect batches only in case when for single stream it takes less then 50Mb, otherwise heaviest partitions will be dumped.
=> ARUHA-1442 Limit memory consumption of subscription streamer to 50 Mb

README.md
ARUHA-1498: Remove internal link from public documentation for Nakadi
Removes Zalando internal link from README.md
Fixes #831
=> ARUHA-1498 Remove internal link from readme. Fixes #831

src/main/java/org/zalando/nakadi/validation/schema/diff/SchemaDiff.java, src/test/java/org/zalando/nakadi/validation/schema/SchemaDiffTest.java
[ARUHA-1452: Not possible to add "properties" object to schema when updating ET]
The problem with the schema library is that EmptySchema is not empty ObjectSchema (as it may seem).
In order to be able to treat it in the same way, emptySchema is casted to the actual type that is being checked.
=> ARUHA-1452 Allow migration from EmptySchema to ObjectSchema and back.

docs/_concepts/archive-authz.md, docs/_config.yml
> Zalando ticket : ARUHA-1085
This is a concept to allow some applications to archive events from all
event types, regardless of the event types' authorization policy.
=> ARUHA-1085 Concept for archiving all event types

CHANGELOG.md, README.md, docs/_data/nakadi-event-bus-api.yaml, docs/_documentation/using_consuming-events-lola.md, src/main/java/org/zalando/nakadi/controller/EventStreamController.java
> Zalando ticket : ARUHA-1489
This PR marks the Low-level API as deprecated:
- in the documentation
- in the swagger file
- with a warning added to the response to calls to the deprecated endpoint
Users of the low-level API are encouraged to migrate to the high-level API.
=> Aruha 1489 Deprecate Low-level API

CHANGELOG.md, src/main/java/org/zalando/nakadi/domain/AllDataAccessResource.java, src/main/java/org/zalando/nakadi/repository/db/AuthorizationDbRepository.java, src/main/java/org/zalando/nakadi/service/AdminService.java, src/main/java/org/zalando/nakadi/service/AuthorizationValidator.java, src/test/java/org/zalando/nakadi/controller/EventStreamControllerTest.java, src/test/java/org/zalando/nakadi/controller/PartitionsControllerTest.java
> Zalando ticket : ARUHA-1504
If an application holds a READ permission for resource all_data_access, it will be able to read from all event types, regardless of their authorization policy.
The list of subjects with permissions for all_data_access must be inserted directly into the DB.
=> ARUHA-1504 Global read access for all_data_access

src/main/java/org/zalando/nakadi/domain/EventTypeBase.java
Do not allow to create event type with null compatibility mode
> Zalando ticket : ARUHA-1496
Getting event type with null compatibility mode returns 500
=> ARUHA-1496: disallow  to post event type with null compatability mode

docs/_documentation/using_clients.md
Updated Nakadi documentation to refer to the new homepage of the nakadi-client package for Haskell instead of referring straight to the API documentation as published on Hackage.
n/a
=> Documentation: Link to new homepage for nakadi-client for Haskell

docs/_documentation/using_clients.md
Changed the link for the Nakadi Rust Client(Nakadion)
Changed the link for the Nakadi Rust Client(Nakadion) to point
at crates.io(official Rust artifact repository) instead of my personal repository.
=> Change Nakadion Nakadi Client link in docs

CHANGELOG.md, src/main/java/org/zalando/nakadi/controller/SubscriptionStreamController.java, src/main/java/org/zalando/nakadi/repository/db/SubscriptionDbRepository.java, src/main/java/org/zalando/nakadi/service/BlacklistService.java, src/main/java/org/zalando/nakadi/service/subscription/SubscriptionService.java
> Zalando ticket : INC-13145
This PR stops logging a full stack trace when a users makes a GET request to `/subscriptions/{id}` or `/subscriptions/{id}/events` with a subscription ID that does not exist
=> INC-13145 Do not log stack trace when users provide a non-existing subscription ID

CHANGELOG.md, src/main/java/org/zalando/nakadi/controller/EventPublishingController.java, src/main/java/org/zalando/nakadi/repository/db/EventTypeDbRepository.java, src/main/java/org/zalando/nakadi/service/timeline/TimelineService.java
> Zalando ticket : ARUHA-1581
Do not log stack trace when event type does not exist
=> Do not log stack trace when event type does not exist

CHANGELOG.md, src/acceptance-test/java/org/zalando/nakadi/webservice/hila/HilaRebalanceAT.java, src/main/java/org/zalando/nakadi/service/CursorsService.java
> Fix 500 on Nakadi stream from single partition : ARUHA-1626
-
=> ARUHA-1626: fixed commit for subscriptions that use direct assignment of partitions;

docs/_api/event-types_name_events_get.md, docs/_documentation/intro.md, docs/_documentation/using_authorization.md, docs/_documentation/using_consuming-events-lola.md, docs/_documentation/using_event-types.md, docs/_documentation/using_producing-events.md
Fixed samples in the docs, replaced https with http for localhost.
Some curl samples were failing with TLS error.
-
=> localhost uses http not https - fixed samples in docs

docs/_documentation/using_clients.md
This PR removes both the Nakadi Klients and Reactive Nakadi clients as suggested clients for Nakadi, reasons being
1. Both clients are unmaintained. The last commit for Reactive Nakadi is over a year ago and Nakadi Klients is deprecated
2. Nakadi Klients is already marked as deprecated
3. Both clients implement the low level Nakadi API (which is also deprecated) and there is no hint that either of the clients have plans to upgrade to the high level API
=> Removing deprecated/unmaintained Nakadi clients

docs/_documentation/using_clients.md
Documentation change: the homepage of the nakadi-client package for Haskell is now reachable via HTTPS. Previously it was only reachable via plain HTTP.
Changed URL: http → https.
n/a
=> Use https instead of plain http in nakadi-client URL

docs/_documentation/using_clients.md
See zalando/riptide#352
Added Riptide Stream to list of clients
Riptide Stream is a module that is part of the Riptide ecosystem/library. It has no direct dependency to Riptide and can just be used with a plain Spring RestTemplate. Therefore it's a compelling way for Spring applications that need to stream events from Nakadi. Riptide Stream does not offer anything Nakadi specific. Any calls to create subscriptions and commit cursors need to done manually, but that's usually no big issue since those are just simple HTTP calls (in comparison to reading the HTTP event stream).
=> Added Riptide Stream to list of clients

CHANGELOG.md, docs/_data/nakadi-event-bus-api.yaml, src/acceptance-test/java/org/zalando/nakadi/webservice/UserJourneyAT.java, src/acceptance-test/java/org/zalando/nakadi/webservice/hila/HilaAT.java, src/main/java/org/zalando/nakadi/controller/ExceptionHandling.java, src/main/java/org/zalando/nakadi/controller/SubscriptionController.java, src/main/java/org/zalando/nakadi/domain/ConsumedEvent.java, src/main/java/org/zalando/nakadi/domain/SubscriptionEventTypeStats.java, src/main/java/org/zalando/nakadi/exceptions/ErrorGettingCursorTimeLagException.java, src/main/java/org/zalando/nakadi/exceptions/runtime/InconsistentStateException.java, src/main/java/org/zalando/nakadi/exceptions/runtime/LimitReachedException.java, src/main/java/org/zalando/nakadi/exceptions/runtime/TimeLagStatsTimeoutException.java, src/main/java/org/zalando/nakadi/repository/kafka/NakadiKafkaConsumer.java, src/main/java/org/zalando/nakadi/service/NakadiCursorComparator.java, src/main/java/org/zalando/nakadi/service/subscription/SubscriptionService.java, src/main/java/org/zalando/nakadi/service/subscription/SubscriptionTimeLagService.java, src/main/java/org/zalando/nakadi/service/timeline/TimelineService.java, src/test/java/org/zalando/nakadi/controller/SubscriptionControllerTest.java, src/test/java/org/zalando/nakadi/repository/kafka/NakadiKafkaConsumerTest.java, src/test/java/org/zalando/nakadi/service/EventStreamTest.java, src/test/java/org/zalando/nakadi/service/SubscriptionServiceTest.java, src/test/java/org/zalando/nakadi/service/SubscriptionTimLagServiceTest.java, src/test/java/org/zalando/nakadi/service/SubscriptionTimeLagServiceTest.java, src/test/java/org/zalando/nakadi/service/subscription/state/PartitionDataTest.java
Extended subscription statistics endpoint with optional time-lag information.
Zalando ticket: ARUHA-1664
=> ARUHA-1664: Subscription time lag stats

src/main/java/org/zalando/nakadi/config/JettyConfig.java
ARUHA-1674
As there are requests that are "GET with POST" we have to support gzip compression on post requests as well
=> ARUHA-1674 use gzip compression on post requests as well

src/main/java/org/zalando/nakadi/controller/EventPublishingController.java, src/main/java/org/zalando/nakadi/filters/LoggingFilter.java
https://techjira.zalando.net/browse/ARUHA-1698
On each request to publish an event to Nakadi, 2 lines of logs are
generated: 1 for ACCESS_LOG and 1 for SLO log.
SLO log is used by scalyr to report SLOs. It contains basically the same
information but with the addition of the request size.
This change adds the body size to ACCESS_LOG and removes SLO for
publishing requests. This will result in an overall reduction of 30% of log lines,
which is the amount of logging we were requested to reduce in order to
avoid overspending on logs.
=> Reduce logging by removing content duplication

README.md
Example of publishing an event in ReadMe.md contains [invalid JSON with trailing commas](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Trailing_commas#Trailing_commas_in_JSON). Posting it to API causes a parsing exception.
```
nakadi_1     | [2018-06-14 01:54:09.712Z] [DEBUG] [3uL1wsYUrpu8rUSwobeQ40hl] [qtp1912187243-21] [org.zalando.nakadi.controller.EventPublishingController] --- Problem parsing event
nakadi_1     | org.json.JSONException: Not allowed to finish object with comma at pos 44
nakadi_1     | 	at org.zalando.nakadi.domain.StrictJsonParser.syntaxError(StrictJsonParser.java:235)
nakadi_1     | 	at org.zalando.nakadi.domain.StrictJsonParser.readObjectTillTheEnd(StrictJsonParser.java:180)
nakadi_1     | 	at …
```
=> Updated publishing example in ReadMe.md

CHANGELOG.md, src/acceptance-test/java/org/zalando/nakadi/repository/kafka/KafkaRepositoryAT.java, src/main/java/org/zalando/nakadi/repository/kafka/KafkaLocationManager.java, src/main/java/org/zalando/nakadi/repository/kafka/KafkaSettings.java, src/main/resources/application.yml
https://techjira.zalando.net/browse/ARUHA-1739
In order to send larger messages we need to also allow for bigger
requests. This is not only the case for bigger messages but also if we
want to send larger batches to kafka, which in some cases can increase
throughput.
=> Increase max request size

CHANGELOG.md, docs/_data/nakadi-event-bus-api.yaml, src/acceptance-test/java/org/zalando/nakadi/webservice/UserJourneyAT.java, src/main/java/org/zalando/nakadi/domain/Audience.java, src/main/java/org/zalando/nakadi/domain/EventAudience.java, src/main/java/org/zalando/nakadi/domain/EventTypeBase.java, src/main/java/org/zalando/nakadi/service/EventTypeService.java, src/test/java/org/zalando/nakadi/controller/EventTypeControllerTest.java, src/test/java/org/zalando/nakadi/utils/EventTypeTestBuilder.java, src/test/resources/sample-event-type-update.json, src/test/resources/sample-event-type.json
https://techjira.zalando.net/browse/ARUHA-1508
Extend the API with Zalando's internal details.
=> Add event audience field to event type

CHANGELOG.md, src/main/java/org/zalando/nakadi/service/EventTypeService.java, src/main/java/org/zalando/nakadi/service/FeatureToggleService.java, src/test/java/org/zalando/nakadi/service/EventTypeServiceTest.java
> Zalando ticket : ARUHA-1693
On test environments we may allow users to delete event-types together with subscriptions
We should toggle this feature to make it work
=> ARUHA-1693: Added functionality to delete subscriptions together with event-type (if feature is toggled);

docs/_data/nakadi-event-bus-api.yaml
The event categories don't have any common base object/model instead, an Event schema can be one of the three categories
In my humble opinion, this way of describing Event is much cleaner and easier to read and better looks in the manual.
=> Docs. Better Event model description.

docs/_data/nakadi-event-bus-api.yaml
> Zalando ticket : ARUHA-1756
Initial API for Log Compaction feature in Nakadi.
--
=> ARUHA-1756: initial API for Log Compaction;

CHANGELOG.md, build.gradle, docker-compose.yml
> Zalando ticket : ARUHA-1798
New version of Kafka client
This version of Kafka client should be compatible with all versions of Kafka clusters from 0.10.1.0 up.
=> ARUHA-1798 Upgrade kafka client to  1.1.1

CHANGELOG.md, src/main/java/org/zalando/nakadi/service/EventTypeService.java, src/test/java/org/zalando/nakadi/controller/EventTypeControllerTest.java
This feature was assumed to be enabled for a long time now. It happens
that it was never enabled, since it breaks existent use cases. More
specifically event log, which has not predefined schema.
Since this feature was never there and now it was accidentally enabled,
this is a hotfix to completely remove.
=> Remove partition key fields check

docs/_data/nakadi-event-bus-api.yaml
https://techjira.zalando.net/browse/ARUHA-1681
Since the introduction of Event Type Authorization, it was planned that
Subscriptions would also be authorized. Even though data is already
protected through Event Type Authorization, users can still accidentally
commit offsets to subscriptions owned by other users, eventually causing
applications to not process all the data. Subscriptions could also be
accidentally deleted or have its slots assigned to some other
application impeding applications from consuming data.
With this feature we address all of the problems above. This is just the
API definition.
=> Subscription authorization

CHANGELOG.md, src/main/java/org/zalando/nakadi/service/EventTypeService.java, src/test/java/org/zalando/nakadi/controller/EventTypeControllerTest.java
Don't allow the root object type in schema for business and data category to be of type array
> Zalando ticket : ARUHA-1715 
Presently, it is allowed to specify the type of root object in schema to be of type `array`. That is now restricted.
=> Don't allow schema root object type to be array

CHANGELOG.md, src/main/java/org/zalando/nakadi/domain/StrictJsonParser.java, src/test/java/org/zalando/nakadi/domain/BatchFactoryTest.java
Nakadi replies with status code 500 when the number being parsed is greater than max long.
> Zalando ticket : ARUHA-1784
When a user publishes an event with a number greater than max long, the strict json parser fails, and nakadi replies with 500.
=> Fix ISE when parsing number larger than max long

Dockerfile, src/main/resources/application.yml
Put nakadi-event-bus-api.yaml under the api/ folder in docker
When starting the server using the IDE or bootRun, the server currently fails to start because the default setup is to look for `nakadi-event-bus-api.yaml` in the root dir whereas it is in the `api/` folder.
This PR sets it to `api/` by default and makes the appropriate change in the Dockerfile.
=> Put nakadi-event-bus-api.yaml under the api/ folder in docker

src/main/java/org/zalando/nakadi/service/subscription/state/PartitionData.java, src/main/java/org/zalando/nakadi/service/subscription/state/StreamingState.java
> Zalando ticket : [ARUHA-1921](https://techjira.zalando.net/browse/ARUHA-1921) 
Nakadi did not respect batch sizes and max uncommitted events parameters when there was a memory overflow.
=> Send allowed number of events (or less) when memory overflow happens

src/main/java/org/zalando/nakadi/repository/db/EventTypeDbRepository.java
> Zalando ticket : ARUHA-1997
For some reason (probably because of migrating to Hikari) in most cases we now have a different exception thrown when user tries to create ET that already exists. This is a fix for that problem.
=> ARUHA-1997: Extended the catched exception range;

docs/_documentation/using_consuming-events-hila.md
> https://github.com/zalando/nakadi/issues/990
The reason that the link is broken in the documentation is that it uses a relative path. The documentation meant to be used in Nakadi.io as well as Github. Nakadi.io domain and Github interpret the relative paths differently. So to fix the broken link, I changed the path to the absolute path linking to the swagger file in the Github repo.
=> 990 - change the relative link to absolute path to fix a broken link in the documentations.

src/main/java/org/zalando/nakadi/repository/MultiTimelineEventConsumer.java, src/main/java/org/zalando/nakadi/repository/kafka/KafkaFactory.java, src/main/java/org/zalando/nakadi/repository/kafka/KafkaLocationManager.java, src/main/java/org/zalando/nakadi/repository/kafka/KafkaTopicRepository.java, src/main/resources/log4j.properties
During restart of the brokers it was figured out when broker ip changes kafka consumer client does not support that properly and consumers have to be recreated. This PR brings ability to track broker list change and disconnect client.
=> Stop consumers when kafka broker ip changed

src/main/java/org/zalando/nakadi/repository/kafka/KafkaFactory.java, src/main/java/org/zalando/nakadi/repository/kafka/KafkaTopicRepository.java
Producer has to be recreated in case of Kafka broker ip was changed, otherwise it reports that broker with old ip is not available.
=> Kafka producer crutch

Dockerfile
Use the latest openjdk base image
=> Update openjdk base image to 1.8.0-191-19

src/main/java/org/zalando/nakadi/service/subscription/StreamParameters.java, src/test/java/org/zalando/nakadi/service/subscription/StreamParametersTest.java
> Zalando ticket : ARUHA-2159
If a stream is configured with `stream_keep_alive_limit` as `0` the related check `isKeepAliveLimitReached` always returned `true` instead of `false`.
Nothing to add here
=> Fixed check if keep alive limit is reached for indefinitely configured limit

src/main/java/org/zalando/nakadi/controller/PostSubscriptionController.java, src/main/java/org/zalando/nakadi/controller/advice/PostSubscriptionExceptionHandler.java, src/main/java/org/zalando/nakadi/service/subscription/SubscriptionService.java, src/main/java/org/zalando/nakadi/service/subscription/SubscriptionValidationService.java
Also, improve method signature when UnableProcessException can be
thrown
> Zalando ticket : ARUHA-2121
Also, improve method signature when UnableProcessException can be
thrown
=> Aruha-2121 Handle UnableProcessException properly in PostSubscriptionController

src/main/java/org/zalando/nakadi/controller/EventPublishingController.java, src/main/java/org/zalando/nakadi/service/AdminService.java, src/test/java/org/zalando/nakadi/controller/EventPublishingControllerTest.java
Cache when fetching admins from the database and don't check for `VIEW` operation on publish event endpoint.
=> Cache admins and don't check VIEW for publish endpoint

build.gradle
https://jira.zalando.net/browse/ARUHA-2262
Some dependencies could not be easily updated due to major version
incompatibility. Once we proceed with spring boot update we should
cover most of the remaining threats.
=> Upgrade library versions as much as we can

src/test/java/org/zalando/nakadi/repository/kafka/KafkaTopicRepositoryTest.java
Set health check interval to 10 ms (default 500ms) to trigger circuit breaker.
Fix https://github.com/zalando/nakadi/issues/741
Health check emits events once in a fixed period of time (see com.netflix.hystrix.metric.consumer.HealthCountsStream for more info). Default period is 500 ms which is enough for all 1000 batch items to be sent without health check being emitted. Hence the test `whenKafkaPublishTimeoutThenCircuitIsOpened` fails. 
=> Set health check interval to 10 ms (default 500ms) trigger circuit breaker

src/main/java/org/zalando/nakadi/validation/schema/diff/SchemaDiff.java, src/test/resources/org/zalando/nakadi/validation/invalid-schema-evolution-examples.json
https://jira.zalando.net/browse/ARUHA-2282
This fixes a NPE changing an ArraySchema through generalization: an
array that used to define schemas for each item specifically now has a
single schema for all items.
We also added tests for the other way around: a schema that used to
have a single definition for all items now has a per item schema.
=> Detect changes to ArraySchema

src/main/java/org/zalando/nakadi/service/AuthorizationValidator.java
Check that the attributes (and hence the admin `*`, `*` is checked for updates too).
Right now, it is not checked for updates on event-types and subscriptions that the admin doesn't contain wildcard.
=> Check old authorization attributes when updating

src/main/resources/application.yml, src/test/java/org/zalando/nakadi/controller/EventTypeControllerTest.java, src/test/java/org/zalando/nakadi/controller/EventTypeControllerTestCase.java, src/test/java/org/zalando/nakadi/service/EventTypeServiceTest.java
> Zalando ticket: ARUHA-2439
With the new requirements in Nakadi SQL joins there is a need to reduce the retention time in Nakadi for an event type. This PR reduces the retention time from 1 day to 3 hours.
=> reduced retention time

docs/_documentation/intro.md
Remove obsolete links to changelog since the changelog was removed in https://github.com/zalando/nakadi/commit/9fefab11964581e82b791de063241f656483cefe.
=> Remove obsolete links to changelog

src/acceptance-test/java/org/zalando/nakadi/repository/kafka/KafkaRepositoryAT.java, src/main/java/org/zalando/nakadi/config/NakadiSettings.java, src/main/java/org/zalando/nakadi/repository/db/SubscriptionDbRepository.java, src/main/java/org/zalando/nakadi/service/EventTypeService.java, src/main/java/org/zalando/nakadi/service/FeatureToggleService.java, src/main/resources/application.yml, src/test/java/org/zalando/nakadi/controller/EventTypeControllerTestCase.java, src/test/java/org/zalando/nakadi/service/EventPublisherTest.java, src/test/java/org/zalando/nakadi/service/EventTypeServiceTest.java, src/test/java/org/zalando/nakadi/utils/TestUtils.java
To delete an event type if EVENT_TYPE_DELETION_ONLY_ADMINS, the following criteria must be met:
- the caller is in the admins section (possibly through a wildcard)
- there is an admin section
- the only subscriptions attached to the event type are subscriptions defined in the settings nakadi.eventType.deletableSubscription.owningApplication and nakadi.eventType.deletableSubscription.consumerGroup
=> Allow admins to delete event types

src/acceptance-test/java/org/zalando/nakadi/webservice/hila/HilaRepartitionAT.java, src/main/java/org/zalando/nakadi/service/EventTypeService.java, src/main/java/org/zalando/nakadi/service/subscription/zk/NewZkSubscriptionClient.java, src/main/java/org/zalando/nakadi/service/timeline/TimelineService.java, src/test/java/org/zalando/nakadi/controller/EventTypeControllerTestCase.java, src/test/java/org/zalando/nakadi/service/EventTypeServiceTest.java
Combine depended tasks interface to repartition event type
Add partitions to active timeline Kafka topic
Update timelines of the event type to have offsets for partitions added
Update event type cache
Close streaming connections for the subscriptions
=> ARUHA-2538: repartitioning itself combined

src/main/java/org/zalando/nakadi/service/timeline/TimelineService.java
Only active timelines have to be taken for repartitioning
=> take only active timelines

src/main/java/org/zalando/nakadi/repository/kafka/HystrixKafkaCircuitBreaker.java, src/main/java/org/zalando/nakadi/repository/kafka/KafkaTopicRepository.java, src/test/java/org/zalando/nakadi/repository/kafka/KafkaTopicRepositoryTest.java
This PR recreates the PR from https://github.com/zalando/nakadi/pull/1038
It fixes kafka circuit breaker to switch to open state multiple times based on Kafka's response.
=> added circuit breaker changes and test

src/main/java/org/zalando/nakadi/service/subscription/StreamingContext.java, src/main/java/org/zalando/nakadi/service/subscription/state/CleanupState.java
Switch state to DEAD state in case of exception without scheduling it in the task queue. One cleaner way to achieve the same is using priority queue for tasks, but I do not see where we need to handle tasks with priority other than during an exception.
=> Switch state immediately to DEAD state if exception/do not schedule it

src/acceptance-test/java/org/zalando/nakadi/repository/kafka/KafkaRepositoryAT.java, src/main/java/org/zalando/nakadi/controller/EventPublishingController.java, src/main/java/org/zalando/nakadi/repository/TopicRepository.java, src/main/java/org/zalando/nakadi/repository/kafka/KafkaTopicRepository.java, src/main/java/org/zalando/nakadi/service/EventPublisher.java, src/main/java/org/zalando/nakadi/service/EventsProcessor.java, src/test/java/org/zalando/nakadi/repository/kafka/KafkaTopicRepositoryTest.java, src/test/java/org/zalando/nakadi/service/EventPublisherTest.java, src/test/java/org/zalando/nakadi/service/EventsProcessorTest.java
There are requests to delete a lot of events in a compacted event types, and right now nakadi basically lacks this functionality. 
I know that the code is not pretty, but in order to solve current needs of users, we can provide non-documented endpoint to allow deletion of events (the endpoint and service is not covered with unit tests), so my suggestion will be to merge this pr to master, tests it on data and then revert it, keeping this pr open in order to be able to rework it and allow this endpoint to everyone. 
The base idea is that publishing and deletion is almost the same - users have to publish the same events to different endpoint, and nakadi will publish null to kafka to remove events.
=> ARUHA-2642 Temporary allow deletion of events

src/main/java/org/zalando/nakadi/service/subscription/StreamingContext.java, src/main/java/org/zalando/nakadi/service/subscription/state/StreamingState.java
At the end of the StartingState, we schedule rebalance on changes to the session list, and then, secondly register the session.
This fires in an event to re-balance via zookeeper watches. Once the rebalance finishes, the session gets the partitions it needs to stream from.
Re-balance might finish later than sending the headers and due to this, the check of offsets will happen only after the re-balance assigns a partition to the session. 
This improves the rate at which 200s will be returned, but there can be still a few 200s, if the rebalance finishes after sending the headers. (There is an listener scheduled for changing topology before sending the headers, using this change)
If we make sending the headers blocking after re-balance finishes, the response time will increase. What do you …
=> Add scheduler for refresh topology

src/main/java/org/zalando/nakadi/repository/EventTypeRepository.java, src/main/java/org/zalando/nakadi/repository/db/CachingEventTypeRepository.java, src/main/java/org/zalando/nakadi/repository/db/EventTypeDbRepository.java, src/main/java/org/zalando/nakadi/service/EventTypeService.java, src/main/java/org/zalando/nakadi/service/RepartitioningService.java, src/main/java/org/zalando/nakadi/service/job/TimelineCleanupJob.java, src/main/java/org/zalando/nakadi/service/timeline/TimelineService.java, src/test/java/org/zalando/nakadi/controller/EventTypeControllerTest.java, src/test/java/org/zalando/nakadi/repository/db/CachingEventTypeRepositoryTest.java, src/test/java/org/zalando/nakadi/service/EventTypeServiceTest.java, src/test/java/org/zalando/nakadi/service/job/TimelineCleaningJobTest.java
ARUHA-2637 Use transactions while creating event type
Also, As a part of the same problem - do not reset cache during transaction, run event type cache update only after successful transaction commit, as updating cache in the middle of transaction only leads to bugs.
=> ARUHA-2637 Use transactions while creating event type

docs/_data/nakadi-event-bus-api.yaml, src/main/java/org/zalando/nakadi/controller/SubscriptionStreamController.java, src/main/java/org/zalando/nakadi/service/subscription/StreamParameters.java, src/main/java/org/zalando/nakadi/service/subscription/state/PartitionData.java, src/main/java/org/zalando/nakadi/service/subscription/state/StreamingState.java, src/main/java/org/zalando/nakadi/view/UserStreamParameters.java, src/test/java/org/zalando/nakadi/service/subscription/StreamParametersTest.java, src/test/java/org/zalando/nakadi/service/subscription/state/PartitionDataTest.java, src/test/java/org/zalando/nakadi/service/subscription/state/StreamingStateTest.java
This is an API extension proposal.
In order to improve the SLO from Nakadi archiver, we are introducing a
new parameter that makes slicing events in 5 minutes window possible.
As it's explained in the description of the parameter, using
`batch_flush_timeout` alone is not enough and it leads to the
accumulation of events produced throughout a longer timespan than the
desired 5 minutes window.
To further illustrate when this happens consider the following
sequence of events:
1. events are produced one per minute starting at minute 0
2. a stream to read these events is not openned until minute 10. This
stream has batch_flush_timeout of 5 minutes.
3. at minute 15 a batch is flushed containing the events produced from
minute 0 to minute 15 (15 events).
This is not the desired behaviour for …
=> Introduce batch_timespan consumption parameter

Dockerfile, docker-compose.yml, src/main/java/org/zalando/nakadi/repository/EventTypeRepository.java, src/main/java/org/zalando/nakadi/repository/db/CachingEventTypeRepository.java, src/main/java/org/zalando/nakadi/repository/db/EventTypeDbRepository.java, src/main/java/org/zalando/nakadi/service/EventTypeService.java, src/main/java/org/zalando/nakadi/service/RepartitioningService.java, src/main/java/org/zalando/nakadi/service/timeline/TimelineService.java, src/main/resources/application.yml, src/test/java/org/zalando/nakadi/controller/EventTypeControllerTest.java, src/test/java/org/zalando/nakadi/repository/db/CachingEventTypeRepositoryTest.java, src/test/java/org/zalando/nakadi/service/EventTypeServiceTest.java
Use transactions while creating event type, notify about updates only after transaction commit, do not rely on psql getTypeInfo call for null types, as connection may be in simple mode (no prepared statements)
ARUHA-2637
=> Aruha 2637

src/acceptance-test/java/org/zalando/nakadi/webservice/hila/HilaAT.java, src/acceptance-test/java/org/zalando/nakadi/webservice/hila/HilaDeleteEventsAT.java, src/acceptance-test/java/org/zalando/nakadi/webservice/utils/NakadiTestUtils.java, src/main/java/org/zalando/nakadi/repository/MultiTimelineEventConsumer.java
Aruha 2642 - Continue event consumption if some of events were deleted 
There is a problem with consumption stack - in case if some events were deleted and log cleaner not yet compacted this events, then nakadi won't be able to consume it. 
This pr targets this issue - skip deleted events from the stream
=> Aruha 2642 - Continue event consumption if some of events were deleted 

src/main/java/org/zalando/nakadi/service/subscription/state/StreamingState.java
Accidentally batch timeout was offered in the place of batch timespan
which caused batch sizes to be reduced in size in some situations
adding latency to some consumers.
=> Batch timeout was used in the place of batch timespan

src/main/java/org/zalando/nakadi/service/subscription/state/PartitionData.java, src/test/java/org/zalando/nakadi/service/subscription/state/PartitionDataTest.java
In case there are no events in the time window, but there a single
event outside the time window, this event would trigger extraction but
then no events would be sent, as the window is empty.
As no events would be sent, the value of the window would not be
updated.
This could cause low frequency streams to get stuck.
=> Avoid sending empty batches in case there are no events in the upcoming window

database/migration/aruha-2643-subscription-add-index.sql
> Zalando ticket : ARUHA-2643
This is just a temporary solution to reduce the cost of queries that internal applications make for fetching subscriptions by owning application (while still using offset based pagination)
=> Add index on owning application for subscription table

src/main/java/org/zalando/nakadi/service/subscription/StreamingContext.java, src/test/java/org/zalando/nakadi/service/subscription/StreamingContextTest.java
In case of exception before creation of subscription for zookeeper changes to sessions list, the corresponding session registered in Zookeeper is not cleaned up, leading to a zombie state, where a stream is present, but not in `StreamingState`.
The bug that the consumption instance wouldn't clean up the session was because the session timed out while releasing the lock during registration of session (i.e before [switching](https://gist.github.com/ferbncode/5f97ee428d9124c869c51ccf0139ef42#file-exception-L66) to streaming state)
See exception here: https://gist.github.com/ferbncode/5f97ee428d9124c869c51ccf0139ef42
This can then only be fixed by terminating the instance where the exception occurred.
=> Session not cleaned if error before making zookeeper session change subscription

src/main/java/org/zalando/nakadi/service/subscription/StreamingContext.java, src/main/java/org/zalando/nakadi/service/subscription/zk/AbstractZkSubscriptionClient.java, src/test/java/org/zalando/nakadi/service/subscription/StreamingContextTest.java
Initially, I did set the flag (`sessionRegistered` back to false only after successfully un-registering a node. If an exception occurred after deletion of the node, it is happening that the variable is not unset and we loop through `CleanupState.onEntry()` logging too much
Added check if the node exists (it should not increase much over-head on zookeeper, since this is not a very frequent operation) before deletion as I don't want to set `sessionRegistered=false` if un-registering fails, which would cause the zombie session issue
=> Check if node exists before attempt to delete

src/main/java/org/zalando/nakadi/service/subscription/StreamingContext.java, src/main/java/org/zalando/nakadi/service/subscription/zk/AbstractZkSubscriptionClient.java
Do unregister based on a flag as before. Right now, disk is still filling up if it fails with the `isActiveSession` call.
=> Do unregister session as before

api-metastore/src/main/java/org/zalando/nakadi/service/EventTypeService.java, app/src/main/java/org/zalando/nakadi/service/SystemEventTypeInitializer.java
Signed-off-by: Thomas Abraham <thomas.abraham@zalando.de>
> Zalando ticket : ARUHA-2704
When Nakadi starts up, it tries to create a few system event types.
When the event type creation fails, because they already exist, it logs the an error with complete stack trace. This PR introduces a `createIfMissing` function, which will check if the event exists first.
=> Create system event-types only if they are missing

core-services/src/main/java/org/zalando/nakadi/service/AuthorizationValidator.java, core-services/src/main/java/org/zalando/nakadi/service/publishing/EventPublisher.java, core-services/src/test/java/org/zalando/nakadi/service/AuthorizationValidatorTest.java
Don't check `authorization` per event if owner is not set.
=> Don't check event authorization if the owner is not set

core-services/src/main/java/org/zalando/nakadi/service/publishing/EventOwnerExtractorFactory.java, core-services/src/test/java/org/zalando/nakadi/service/publishing/EventOwnerExtractorTest.java
StrictJsonParser.java returns `JSONObject.NULL` for fields where value is set as `null`. Thus, fixed the code to handle `nulls` as expected.
=> Fix handling of `null` path as StrictJsonParser uses JSONObject.NULL

docs/_data/nakadi-event-bus-api.yaml
The section of the API responsible for defining the amount of partitions (`EventTypeStatistics`) was elusive and unclear. Users were not able to tell by themselves how many partition they would get after providing values in the section. It has caused pain for every user who ever tried to understand it. Even though Nakadi UI reduced this pain by providing a saner and more direct way to define the amount of partitions, the API was never reviewed and kept haunting new users with its unpractical definition.
This change in the documentation aims in making it more direct and plain honest. Trying to "hide" the behaviour from users was unproductive and generated an unexplainable amount of support time answering the same question over and over again.
We do plan on getting rid of this section of …
=> Document how to choose number of partition of an event type

acceptance-test/build.gradle, acceptance-test/src/acceptance-test/java/org/zalando/nakadi/repository/kafka/KafkaRepositoryAT.java, acceptance-test/src/acceptance-test/java/org/zalando/nakadi/repository/kafka/KafkaTestHelper.java, api-consumption/build.gradle, api-cursors/build.gradle, api-misc/build.gradle, app/build.gradle, app/src/main/resources/application.yml, build.gradle, core-common/build.gradle, core-common/src/main/java/org/zalando/nakadi/repository/kafka/KafkaTopicRepository.java, core-common/src/main/java/org/zalando/nakadi/repository/zookeeper/ZookeeperSettings.java, core-metastore/build.gradle, core-services/build.gradle, docker-compose.yml
Kafka Client removed `zkUtils` and `adminUtils` from client libraries. Implemented their functions from `KafkaZkClient` and `AdminZkClient`.
For creating a `ZookeeperClient` instance, the following new parameters: https://jaceklaskowski.gitbooks.io/apache-kafka/kafka-ZooKeeperClient.html
I kept the max-in-flight requests parameter to `1000`(not too high), for we'd be using this zookeeper connection/client for only creation/update and deletion of topics.
We used the `zkUtils` and `adminUtils` libraries only for creating topics/updating retention time and deleting topics
=> Update Kafka Clients to 2.4.0

api-metastore/src/main/java/org/zalando/nakadi/validation/schema/PartitionKeyFieldsConstraint.java
https://jira.zalando.net/browse/ARUHA-2648
For a long time changing partition_key_fields was an operation
performed only by admins via a database hack. This used to be case in
order to protect consumers from unexpected changes on how events are
hashed, which could lead to a number of issues on the consumer side.
But as the number of such requests grew, we decided to let the users
decided whether this field should or not be changed. We give them the
responsibility over this operation.
=> Allow to modify partition_key_fields

acceptance-test/src/acceptance-test/java/org/zalando/nakadi/webservice/EventTypeAT.java, app/src/main/java/org/zalando/nakadi/config/WebConfig.java
Sometimes users tend to create event types with names that have extensions like ones defined here: 
https://github.com/spring-projects/spring-framework/blob/master/spring-context-support/src/main/resources/org/springframework/mail/javamail/mime.types
This leads to 406 status code while getting event type. This fix is removing content type negotiation in this case.
=> ARUHA-2746 reconfigure content negotiation

core-common/src/main/java/org/zalando/nakadi/service/subscription/zk/AbstractZkSubscriptionClient.java, core-common/src/main/java/org/zalando/nakadi/service/subscription/zk/ZkSubscriptionClient.java
The problem was introduced as a part of refactoring eliminating the need of additional dependencies. 1 corner case was forgotten
=> ARUHA-2755 Fix problem with the fact that BEGIN is not lexicographicaly comparable

app/src/main/java/org/zalando/nakadi/config/AuthenticationConfig.java, app/src/main/java/org/zalando/nakadi/config/NakadiResourceServerTokenServices.java, app/src/test/java/org/zalando/nakadi/config/NakadiResourceServerTokenServicesTest.java
ARUHA-2714 
The refactoring is made to be able to use several token info endpoints
one after another in case of error and the behavior was tested
intensively.
=> ARUHA-2714 Refactor Authz usage not to return 400 status code

app/src/main/java/org/zalando/nakadi/config/MetricsConfig.java, core-common/src/main/java/org/zalando/nakadi/metrics/NakadiMetricsModule.java, core-common/src/main/java/org/zalando/nakadi/metrics/NakadiMetricsServlet.java
Reduce size of the metrics response short term
Example of the metric
```
"nakadi.eventtypes.xxx.publishing.averageEventSizeInBytes": {
"count": 24,
"max": 186,
"mean": 185.99941606885423,
"min": 174,
"p50": 186,
"p75": 186,
"p95": 186,
"p98": 186,
"p99": 186,
"p999": 186,
"stddev": 0.08370682632688281
}
```
what is actually used
```
m1_rate
count
mean
```
=> reduce size of the metrics response short term

app/src/main/java/org/zalando/nakadi/filters/LoggingFilter.java, core-common/src/main/java/org/zalando/nakadi/domain/Feature.java
ACCESS_LOG lines represent 33% of all the logs from Nakadi. This
information is already available via internal event type
`nakadi.access.log` archived in the  datalake and many other important
operations are instrumented via open tracing, making this log line
redundant.
Since there might be a need to switch access logs back, we are adding
a feature toggle to enable access log. This toggle is turned off by
default meaning that new deployments will have access log turned off
by default.
The feature toggle is checked inside the method and not on the caller code because this method is used in multiple places.
=> Reduce logging by conditionally disabling ACCESS_LOG

app/src/main/java/org/zalando/nakadi/filters/LoggingFilter.java, app/src/main/resources/application.yml
Not logging 5xx would make it difficult to catch bugs as the stack
trace would be lost.
This change also makes successful publishing request to be logged, so turning access log on should be done with care and only when needed, otherwise the log volume could be even bigger.
Do you think I should add another condition on top of these so that successful publishing requests are never logged?
=> Log 5xx even when access log is disabled

app/src/main/java/org/zalando/nakadi/filters/LoggingFilter.java
This commit logs 207's which is considered a server side error and
one of the biggest mistakes in the API design, from my point of
view, given how many clients interpreted it as success in the last 4
years of operating Nakadi. It's such a mistake that even ourselves overlooked
it yesterday when we planned to only log server side errors.
The only type of publishing request that we would like to log are
those where the error is on the server side. Client side errors can be
checked through lightstep and explained in the FAQ.
=> Log 207's and small refactoring

api-metastore/src/main/java/org/zalando/nakadi/config/SchemaValidatorConfig.java, api-metastore/src/main/java/org/zalando/nakadi/validation/schema/CompatibilityModeChangeConstraint.java, api-metastore/src/test/java/org/zalando/nakadi/controller/EventTypeControllerTestCase.java, api-metastore/src/test/java/org/zalando/nakadi/validation/schema/CompatibilityModeChangeConstraintTest.java
https://jira.zalando.net/browse/ARUHA-2804
Users often make mistakes when editing their schemas. Sometimes it's a
typo on a properties name, others it's something more serious that causes events to be
rejected. The rules often do not allowed for such changes to be
undone, as that would mean breaking the compatibility mode (at least
in theory).
But this has led our team to make manual changes to the database
several times as a way to rescue users from dead ends.
Since hacking the database is less than ideal, we are making it
possible for admins (Nakadi admins, not event type admins) to downgrade the compatibility mode, so that users
can fix their schemas and then set the compatibility mode back to what
it was, which they can do on their own.
This is only made available for Nakadi admins, …
=> Allow Nakadi admins to change compatibility mode in unsafe ways

api-metastore/src/main/java/org/zalando/nakadi/service/EventTypeService.java, api-metastore/src/test/java/org/zalando/nakadi/service/EventTypeServiceTest.java
Prior to this fix, when creating a new event type with the following
schema:
```
{
"properties": {
"foo": {
"type": "string",
"pattern": "^(?!\\s*$).+"
}
}
}
```
Would result in 500 and no further explanation to the user. The user
would have to get in contact with the FlowId and we would have to dive
in the logs to find out a stack trace similar to this:
```
com.google.re2j.PatternSyntaxException: error parsing regexp: invalid or unsupported Perl syntax: `(?!`
at com.google.re2j.Parser.parsePerlFlags(Parser.java:1139)
at com.google.re2j.Parser.parseInternal(Parser.java:825)
at com.google.re2j.Parser.parse(Parser.java:802)
at com.google.re2j.RE2.compileImpl(RE2.java:183)
at com.google.re2j.Pattern.compile(Pattern.java:136)
at com.google.re2j.Pattern.compile(Pattern.java:96)
at …
```
=> Fix 500 when creating or updating event types with invalid regex in the schema

acceptance-test/src/acceptance-test/java/org/zalando/nakadi/webservice/SettingsControllerAT.java, api-misc/src/main/java/org/zalando/nakadi/controller/SettingsController.java, core-common/src/main/java/org/zalando/nakadi/domain/FeatureWrapper.java
This endpoint used to reply with 500 when the request body was
invalid.
Now it replies with 400 and some meaningful error that guides the user
towards a fix.
=> Validate request body on POST /settings/features

api-metastore/src/main/java/org/zalando/nakadi/service/EventTypeService.java, api-metastore/src/test/java/org/zalando/nakadi/service/EventTypeServiceTest.java
Prior to this fix it would be possible to refer an external schema in
a schema definition. If the URL would be valid, it would fetch it over
the network. All sorts of problems could happen here:
- invalid URL
- timeout due to server being unresponsive
- other network issues
Besides, loading a schema from an external source could mean that
schema evolution rules could be worked around, by externalizing the
chunk of the schema that would change without any rules, as we do not
verify external schemas.
On top of all this problems, external schemas were never meant to be
supported and this feature made its way in the project since version 0
of Nakadi without the maintainers being aware of it.
After this fix, using external urls will result in 422 with a message
like:
`external url reference is …
=> Block external references in schemas

core-common/src/main/java/org/zalando/nakadi/repository/kafka/KafkaLocationManager.java
the fix narrows down the triggering on brokers change watcher only for the case when list of broker id nodes changed
replicates the broken branch :) https://github.com/zalando/nakadi/pull/1119
```
Currently, broker list changed watcher is recreated on disconnects, which means a lot of watchers created for no reason and later on triggered for the same reason creating even more watchers and so on.
Although, it is clearly seen from the logs, this is hypothesis and the testing is required.
```
=> recreate watcher on brokers change list

docs/_data/nakadi-event-bus-api.yaml, docs/_documentation/faq.md
The default value is 2 days for quite a while, but it was'n reflected everywhere in the documentation. 
This PR removes some obsolete answers and fixes default value in api specification. 
Fixes #1190
=> Change retention time in documentation, remove obsolete answer

acceptance-test/src/acceptance-test/java/org/zalando/nakadi/webservice/UserJourneyAT.java, api-metastore/src/main/java/org/zalando/nakadi/controller/SchemaController.java, api-metastore/src/main/java/org/zalando/nakadi/service/EventTypeService.java, api-metastore/src/main/java/org/zalando/nakadi/service/SchemaService.java, api-metastore/src/test/java/org/zalando/nakadi/controller/EventTypeControllerTest.java, api-metastore/src/test/java/org/zalando/nakadi/controller/EventTypeControllerTestCase.java, api-metastore/src/test/java/org/zalando/nakadi/service/EventTypeServiceTest.java, api-metastore/src/test/java/org/zalando/nakadi/service/SchemaServiceTest.java, docs/_data/nakadi-event-bus-api.yaml
The only way to update a schema so far has been to call `PUT
/event-types/{name}` with the complete definition of the event type in
the body (including the modified schema).
This way of changing schemas has proven to be problematic, as users
could accidentally modify other properties of the event type when
their intention would be to only change the schema.
One example in particular has been causing a lot of problems:
automated schema evolution performed by Nakadi SQL.
Nakadi SQL listens to schema changes made to input event types of
queries and automatically reflects those changes in the schema of the
output event type. It then calls `PUT /event-types/{name}` with the
new schema in order to register it. But this call fails due to
something unrelated to the schema change: the …
=> Register new schema independently from changing other properties

api-metastore/src/main/java/org/zalando/nakadi/service/SchemaEvolutionService.java, api-metastore/src/test/java/org/zalando/nakadi/validation/SchemaEvolutionServiceTest.java, core-common/src/main/java/org/zalando/nakadi/domain/EventType.java
Don't change schema created at time if nothing changes for schema when event type is updated.
> Zalando ticket : ARUHA-2837 (only if appropriate)
Even without no changes to the schema, event type updates would change the schema `created_at` time without version upgrade.
=> Change schema created at time only if new schema

api-metastore/src/main/java/org/zalando/nakadi/controller/SubscriptionController.java, api-metastore/src/main/java/org/zalando/nakadi/service/SubscriptionService.java, core-common/src/main/java/org/zalando/nakadi/service/TracingService.java
Add span for request to fetch subscription statistics. Note that closing of the span is handled in [TracingFilter.java](https://github.com/zalando/nakadi/blob/0f8127af2272d106e1edb6fdba7f3708629097d5/core-common/src/main/java/org/zalando/nakadi/filters/TracingFilter.java#L134). Error code handling for the span is also handled [here](https://github.com/zalando/nakadi/blob/0f8127af2272d106e1edb6fdba7f3708629097d5/core-common/src/main/java/org/zalando/nakadi/filters/TracingFilter.java#L128).
=> Add tracing span for fetch stats request

api-consumption/src/main/java/org/zalando/nakadi/service/subscription/StreamingContext.java, api-consumption/src/main/java/org/zalando/nakadi/service/subscription/state/PartitionData.java, api-consumption/src/main/java/org/zalando/nakadi/service/subscription/state/StreamingState.java, api-consumption/src/test/java/org/zalando/nakadi/service/subscription/state/PartitionDataTest.java, api-consumption/src/test/java/org/zalando/nakadi/service/subscription/state/StreamingStateTest.java
After having a look at heap dump, it is clear where the problem is:
Nakadi consumption uses TreeSet (PartitionData.allCursorsOrdered) to calculate the distance between cursors. Every time cursors are committed or a decision is made to send more data to the client a new subset is created, and once decision is made objects are thrown away, which happens all the time during streaming.
https://github.com/zalando/nakadi/blob/abbabfb0b5598352294bf488a4c852987e51a664/api-consumption/src/main/java/org/zalando/nakadi/service/subscription/state/PartitionData.java#L218
https://github.com/zalando/nakadi/blob/abbabfb0b5598352294bf488a4c852987e51a664/api-consumption/src/main/java/org/zalando/nakadi/service/subscription/state/PartitionData.java#L252
Changing a way to calculate distance will bring …
=> ARUHA-2882: PartitionData generated a lot short lived objects

api-consumption/src/main/java/org/zalando/nakadi/service/ClosedConnectionsCrutch.java
While profiling, I noticed a high number of IOExceptions. Exception rate was over 300 exceptions per second for the duration of the profiling.
```
java.io.IOException.<init>(String)	42,562
java.io.FileInputStream.available()	42,499
sun.nio.cs.StreamDecoder.inReady()	42,499
sun.nio.cs.StreamDecoder.implRead(char[], int, int)	42,499
sun.nio.cs.StreamDecoder.read(char[], int, int)	42,499
java.io.InputStreamReader.read(char[], int, int)	42,499
java.io.BufferedReader.fill()	42,499
java.io.BufferedReader.readLine(boolean)	42,499
java.io.BufferedReader.readLine()	42,499
org.zalando.nakadi.service.ClosedConnectionsCrutch.getCurrentConnections(InputStream)	42,499
```
- read Linux /proc/net/* files fully before processing
- proc files aren't ordinary files and fail when reading
line-by-line with …
=> Eliminate high number of unnecessary java.io.IOExceptions

acceptance-test/src/acceptance-test/java/org/zalando/nakadi/repository/kafka/KafkaRepositoryAT.java, core-common/src/main/java/org/zalando/nakadi/repository/KafkaRepositoryCreator.java, core-common/src/main/java/org/zalando/nakadi/repository/kafka/KafkaTopicRepository.java, core-common/src/test/java/org/zalando/nakadi/repository/kafka/KafkaTopicRepositoryTest.java, core-services/src/test/java/org/zalando/nakadi/service/CursorOperationsServiceTest.java
create meter to track number of short circuiting per broker
example look of the metric
```
"meters": {
"hystrix.short.circuit.{BROKER_ID}_{BROKER_IP}": {
"count": 16,
"m1_rate": 0.38728607837966667,
"units": "events/second"
}
}
```
=> create meter to track number of short circuiting per broker

api-metastore/src/main/java/org/zalando/nakadi/validation/schema/diff/SchemaDiff.java, api-metastore/src/test/resources/invalid-schema-evolution-examples.json, core-common/src/main/java/org/zalando/nakadi/domain/SchemaChange.java, docs/_documentation/using_event-types.md
Changing a schema from empty `{}` to something that is not empty
`{type: string}` should be seen as a type narrowing operation that
doesn't break consumers of forward compatible event types, given the set of events accepted by the
narrowed definition is a subset of the original events. That means
that such a change should be allowed in this direction.
It could be argued that other changes are also type narrowing, as for example `{type:[string,null]}` to `{type:[string]}`, but detecting all possible "type narrowing" changes is a complex problem as it could be posed in a more formal way as "the new schema accepts only a subset of events from the previous schema" which is a computationally difficult problem ( I found some papers years ago). So this is an approximation that handles a specific …
=> Allow for type narrowing under forward compatibility mode

core-services/src/main/java/org/zalando/nakadi/service/publishing/EventPublisher.java
Log full message instead of unusable one for event validation
=> Log full message instead of unusable one for event validation

api-cursors/build.gradle, api-cursors/src/test/java/org/zalando/nakadi/controller/CursorsControllerTest.java, api-metastore/build.gradle, api-metastore/src/test/java/org/zalando/nakadi/controller/EventTypeControllerTest.java, api-metastore/src/test/java/org/zalando/nakadi/controller/PostSubscriptionControllerTest.java, app/src/main/java/org/zalando/nakadi/config/WebConfig.java
With Spring boot 2.3, we need to explicity add
spring-boot-starter-validation for @Valid to work properly
=> Fixing validation in api-cursors

build.gradle, gradle/wrapper/gradle-wrapper.properties, nakadi.sh
There are complications while adopting new gradle version. Moving logic for build and start of Nakadi to bash script to avoid changes in build gradle file functions whenever dsl changes.
=> ARUHA-2915: scripted out nakadi build and start

Dockerfile
According to API guild: 
> An API is published by copying its Open API specification into the reserved /zalando-apis directory of the deployment artifact used to deploy the provisioning service. The directory must only contain self-contained YAML files that each describe one API (exception see MUST only use durable and immutable remote references). We prefer this deployment artifact-based method over the past (now legacy) .well-known/schema-discovery service endpoint-based publishing process, that we only support for backward compatibility reasons.
As we removed twintip, we are adding the API to `/zalando-apis`
=> Copying api to /zalando-apis directory as well

app/build.gradle
When launching the app with plugins, this dependency clashes with
dependencies introduced by the plugins.
=> Remove conflicting dependency

api-consumption/build.gradle, app/build.gradle, app/src/test/java/org/zalando/nakadi/security/AuthenticationTest.java, core-common/build.gradle, core-metastore/build.gradle, core-services/build.gradle
In upgrading to spring boot 2 the default db pool was changed from
tomcat to hikari.
This was a non planned change and in the past we had problems with
hikari, leading us to sticking to tomcat's
https://github.com/zalando/nakadi/commit/8557790b4b5d861f56a3c44e8efb6deac8365236
Since hikari was also not configured, we end up running out of
connections on staging so we need to teardown staging, release a few
connections and then deploy this fix.
This change restores tomcat pool.
=> Replace Hikari by Tomcat pool

acceptance-test/src/acceptance-test/java/org/zalando/nakadi/webservice/hila/HilaAT.java, api-consumption/src/main/java/org/zalando/nakadi/controller/EventStreamController.java, api-consumption/src/main/java/org/zalando/nakadi/controller/SubscriptionStreamController.java, api-consumption/src/main/java/org/zalando/nakadi/service/ClosedConnectionsCrutch.java
The ClosedConnectionsCrutch is likely unnecessary and creates problems with SpringBoot 2 update.
This PR disables it in place to validate this before completely removing ClosedConnectionsCrutch.
=> Disabling connection close crutch to validate springboot2 without it

api-metastore/src/main/java/org/zalando/nakadi/controller/EventTypeController.java, api-metastore/src/main/java/org/zalando/nakadi/service/EventTypeService.java, core-common/src/main/java/org/zalando/nakadi/domain/CleanupPolicy.java, core-common/src/main/java/org/zalando/nakadi/repository/kafka/KafkaTopicConfigFactory.java, core-services/src/main/java/org/zalando/nakadi/service/publishing/EventPublisher.java, core-services/src/main/java/org/zalando/nakadi/service/timeline/TimelineService.java, core-services/src/main/resources/schema_metadata.json, docs/_data/nakadi-event-bus-api.yaml
Since Kafka 0.10.1.0 log compaction and log deletion are no longer
multually exclusive cleanup policies. They can be used in a combined
way as described in the KIP used to design it
https://cwiki.apache.org/confluence/display/KAFKA/KIP-71:+Enable+log+compaction+and+deletion+to+co-exist
This PR adds support for such an option.
=> Support for compact and delete cleanup policy

acceptance-test/src/acceptance-test/java/org/zalando/nakadi/webservice/StorageControllerAT.java
When updating the default storage one has to wait for the zk watcher
to be processed. This may take some time. In fact, we may have a bug
here when the watcher for some reason is missed (for example lost
connectivity to zk and recreation of watcher). But I'm not fixing
Nakadi, instead my goal is to first have more stable tests.
Also using teardown to avoid the failure of this particular test
cascade interfere with other tests which makes it harder to find the
"root cause" of the failures.
=> Fix failing test due to eventual consistency of default storage update

docs/_data/nakadi-event-bus-api.yaml
> Zalando ticket : ARUHA-2982 
Endpoint to delete an event from a log compacted event-type is missing documentation. This is added in this PR.
=> Documented deletion of log compacted event-type

acceptance-test/build.gradle, api-consumption/build.gradle, app/build.gradle, core-common/build.gradle, core-metastore/build.gradle, core-services/build.gradle
We are going to wait for jetty upgrade and not force the upgrade of
one of its dependencies.
=> Revert change to jakarta websocket api

api-metastore/src/main/java/org/zalando/nakadi/config/SchemaValidatorConfig.java, api-metastore/src/main/java/org/zalando/nakadi/validation/schema/CompatibilityModeChangeConstraint.java, api-metastore/src/test/java/org/zalando/nakadi/controller/EventTypeControllerTestCase.java, api-metastore/src/test/java/org/zalando/nakadi/validation/schema/CompatibilityModeChangeConstraintTest.java
Users often want to make incompatible changes to schema by removing
required properties or any other sort of change that has the potential
of causing consumers to break.
Often they are the sole consumer of that data or they have already
aligned with downstream service owners that such change will be
handled gracefully.
They have the confidence that making such changes is the least
disruptive way of delivering something and want to do it.
Our team ends up acting a bottleneck.
This change grants them with such freedom to change.
=> Allow event type admins and nakadi admins to edit schema compatibility

api-metastore/src/main/java/org/zalando/nakadi/service/SchemaService.java, api-metastore/src/test/java/org/zalando/nakadi/service/SchemaServiceTest.java
> Zalando ticket : ARUHA-2225 
The new endpoint for addition of a schema (`POST /event-types/{et}/schemas`) to an event-type doesn't publish to audit log or the event-type log event-types. The changes ensure that in case if the new schema version is different from the previous, an event is published to the event-type log and audit log event types
=> ARUHA-2225: Publish to Audit log and Event Type log for POST /event-types/{et}/schemas

acceptance-test/src/acceptance-test/java/org/zalando/nakadi/webservice/UserJourneyAT.java, core-services/src/main/java/org/zalando/nakadi/service/RepartitioningService.java
Repartitioning an event type is a complex operation that requires
changing multiple database tables and zookeeper nodes. Since at least
two different storages have to be modified in order to perform a
repartitioning, we cannot do it atomically.
This means that if in the middle of the process it eventually fails,
the changes would be left half done.
Implementing some kind of "rollback" is not a good idea because the
rollback itself can fail and leave the state in an even more obscure
state.
In situations like this, the cleanest solution is to go for an
indempotent change.
I checked all the code and from the tests I performed, it works
incrementally, in the sense that it always "adds" structures when if
finds something missing.
This means we can run this same command multiple times and it …
=> Indempotent repartitioning

core-common/src/main/java/org/zalando/nakadi/domain/StrictJsonParser.java, core-common/src/test/java/org/zalando/nakadi/domain/BatchItemTest.java
Added support for control characters in custom implementation of JSON parser. The commit provides validation of unicode control characters and throws exception whenever it can not parse incoming events. Accroding to JSON spec[1] only the following characters should be escaped: from '\u0000' to '\u001F'.
[1]: https://www.ietf.org/rfc/rfc4627.txt, chapter 2.5. Strings
=> validate control characters while parsing events

core-common/src/main/java/org/zalando/nakadi/enrichment/EnrichmentsRegistry.java, core-common/src/main/java/org/zalando/nakadi/enrichment/MetadataEnrichmentStrategy.java, core-services/src/test/java/org/zalando/nakadi/enrichment/MetadataEnrichmentStrategyTest.java, docs/_data/nakadi-event-bus-api.yaml
> Zalando ticket : ARUHA-2896
Adding `published_by` field to metadata with the id of the publisher; 
the subject that published this specific event to Nakadi.
=> Adding published_by to metadata

delivery.yaml
> Zalando ticket : ARUHA-3086
Adding `-pr` to the image name of the docker images built from a pull request to identify them easily.
=> Using different image name for PR build

delivery.yaml
The build is failing currently with the following error:
```
2020-11-25T14:44:52.350Z /usr/local/lib/python3.5/dist-packages/paramiko/transport.py:33: CryptographyDeprecationWarning: Python 3.5 support will be dropped in the next release of cryptography. Please upgrade your Python.
2020-11-25T14:44:54.357Z   from cryptography.hazmat.backends import default_backend
2020-11-25T14:44:54.357Z Traceback (most recent call last):
2020-11-25T14:44:54.357Z   File "/usr/local/lib/python3.5/dist-packages/jsonschema/__init__.py", line 31, in <module>
2020-11-25T14:44:54.357Z     from importlib import metadata
2020-11-25T14:44:54.357Z ImportError: cannot import name 'metadata'
2020-11-25T14:44:54.357Z 
2020-11-25T14:44:54.357Z During handling of the above exception, another exception occurred: …
```
=> Fix acceptance test build

docs/_data/nakadi-event-bus-api.yaml
> Zalando ticket : ARUHA / issues / 118
There is a mismatch between the [documentation](https://nakadi.io/manual.html#definition_Problem) and the implementation.
In the documentation [type key](https://nakadi.io/manual.html#definition_Problem*type) looks like a mandatory one (can see a red star next to it) but it is absent in the response from the server.
As a result, a library implementation might incorrectly rely on this field (e.g. _kanadi_ that considers that the key is a mandatory one and cannot parse the problem response (but interprets it as a different type of error) ).
examples of the response:
```json
{"title":"Forbidden","status":403,"detail":"Access on READ subscription:e1eeeb6d-1819-48de-924e-ded2fe983c9e denied"}
{"title":"Conflict","status":409,"detail":"Resetting …
```
=> fix mismatch between the documentation and the implementation for problem-json

acceptance-test/build.gradle, acceptance-test/src/acceptance-test/java/org/zalando/nakadi/repository/db/StorageDbRepositoryTest.java, api-consumption/build.gradle, api-cursors/build.gradle, api-misc/build.gradle, api-misc/src/test/java/org/zalando/nakadi/controller/StoragesControllerTest.java, app/build.gradle, app/src/test/java/org/zalando/nakadi/config/NakadiConfigTest.java, build.gradle, core-common/build.gradle, core-common/src/main/java/org/zalando/nakadi/domain/storage/ZookeeperConnectionType.java, core-common/src/main/java/org/zalando/nakadi/repository/zookeeper/ZooKeeperHolder.java, core-common/src/main/java/org/zalando/nakadi/service/subscription/zk/AbstractZkSubscriptionClient.java, core-common/src/main/java/org/zalando/nakadi/service/subscription/zk/ZkSubscriptionImpl.java, core-common/src/test/java/org/zalando/nakadi/domain/storage/ZookeeperConnectionTest.java, core-metastore/build.gradle, core-services/build.gradle, core-services/src/test/java/org/zalando/nakadi/service/StorageServiceTest.java
> Zalando ticket : ARUHA-3237
Incompatible versions of zookeeper and curator causes some runtime exceptions (`java.lang.NoSuchFieldError: addr`), which are fixed by upgrading curator to latest compatible version. Exhibitor support had to be removed when curator is upgraded.
=> Removed exhibitor support, upgrading curator to 5.1.0

core-services/src/main/java/org/zalando/nakadi/service/publishing/EventsProcessor.java, core-services/src/main/java/org/zalando/nakadi/service/publishing/NamedThreadFactory.java, core-services/src/test/java/org/zalando/nakadi/service/publishing/EventsProcessorTest.java
There is inoptimal thread usage for kpi and supplementary message publishing.
One or several threads may actually block whole the processing flow.
In order to avoid it intermediate batcher thread was introduced, with the only purpose of batching requests.
In case if publishing is stuck, assembled batches are dropped with error message.
=> Use more optimal way of publishing events to internal event types, to reduce the chance of overload.

Dockerfile, acceptance-test/build.gradle, api-consumption/build.gradle, api-cursors/build.gradle, api-metastore/build.gradle, api-misc/build.gradle, api-publishing/build.gradle, app/build.gradle, build.gradle, core-common/build.gradle, core-metastore/build.gradle, core-services/build.gradle, delivery.yaml, gradle/wrapper/gradle-wrapper.properties
https://jira.zalando.net/browse/ARUHA-3111
This PR makes the least changes necessary to build and run Nakadi on
Java 11.
- uses approved base image
https://cloud.docs.zalando.net/howtos/compliant-images/#use-of-allowed-docker-base-images
- upgraded gradle to 6.7.1 which introduced `toolchain`
https://docs.gradle.org/current/userguide/toolchains.html which helps
us make sure that the same java version is used everywhere
- included an extra dependency (unfortunatelly) to fix springboot
dependency which is no longer part of default java module
https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-with-Java-9-and-above
This way the app builds and passes acceptance tests. I'm not sure this
is production ready yet as there could be changes in GC, for
example. Some work is still …
=> Building and running on Java 11

core-metastore/src/main/java/org/zalando/nakadi/cache/SubscriptionCache.java
> Zalando ticket : team-aruha/issues/470
When a subscription is created without the read permissions for the client, client is not able commit cursors as expected. 
But the cursor commit is forbidden even after the permission is granted.
- The subscription object is fetched using SubscriptionCache.getSubscription method.
- The SubscriptionCache uses a guava LoadingCache with expireAfterAccess configured.
- The default value for expireAfterAccess is 300000ms, that is 5min.
- This means that the value is evicted from cache if it is not accessed for 5min.
- This also means that the value can stay in cache forever, if there is no 5min window without any access.
- The bug is probably facing this scenario as the client will keep retrying to commit.
- The above scenario alone cannot be the cause …
=> Bugfix: using expireAfterWrite to avoid caching forever

acceptance-test/src/acceptance-test/java/org/zalando/nakadi/webservice/InvalidRequestAT.java, app/src/main/java/org/zalando/nakadi/filters/RequestRejectedFilter.java
This is going to be addressed by https://github.com/spring-projects/spring-security/issues/7568
> Zalando ticket : team-aruha/521
=> Respond with status 400 for invalid requests handled by spring security firewall

Dockerfile
That makes it easier to stay on top of the latest security release by just re-triggering the build pipeline.
=> Use latest base docker image

delivery.yaml
Use critical-large VMs to speed up build
=> Use critical-large VMs to speed up build

api-metastore/src/main/java/org/zalando/nakadi/controller/advice/PartitionsExceptionHandler.java, api-metastore/src/test/java/org/zalando/nakadi/controller/PartitionsControllerTest.java
atm nakadi will return 503 http status code if consumed_offset argument is unknown to nakadi. instead it should return 422 unprocessable entity.
=> return 422 status when consumed offset is nonsense

api-metastore/src/main/java/org/zalando/nakadi/controller/PostSubscriptionController.java, api-metastore/src/main/java/org/zalando/nakadi/controller/advice/PostSubscriptionExceptionHandler.java, api-metastore/src/test/java/org/zalando/nakadi/controller/PostSubscriptionControllerTest.java
when the same subscription was created by several requests at almost the same time the first request gets 201 http status code, but the second - 503 status code. the expected response status code in such case is 409 conflict.
=> return 409 http status if subscription exists

core-common/src/main/java/org/zalando/nakadi/domain/StrictJsonParser.java, core-common/src/test/java/org/zalando/nakadi/domain/StrictJsonParserTest.java, core-services/src/test/java/org/zalando/nakadi/validation/JSONSchemaValidationTest.java
> Zalando ticket : team-aruha#565
`StringJsonParser` does not complain for numbers that start with `.` and they are parsed to double by `Double.valueOf`
=> Reject number formats for numbers that start with `.`

acceptance-test/src/acceptance-test/java/org/zalando/nakadi/repository/kafka/KafkaTestHelper.java, build.gradle, core-common/build.gradle, core-common/src/main/java/org/zalando/nakadi/repository/kafka/KafkaTopicRepository.java
Some time ago kafka 2.7.0 was released. This PR gets rid of spring-boot kafka-clients dependency and adds dependency to a `2.7.0` kafka client version .
=> Update kafka-clients dependency.

README.md, core-common/src/main/java/org/zalando/nakadi/service/subscription/zk/AbstractZkSubscriptionClient.java, core-common/src/main/java/org/zalando/nakadi/service/subscription/zk/NewZkSubscriptionClient.java
> Zalando ticket : team-aruha/issues/692
Handling KeeperException.NodeExistsException when creating individual
children of subscription ZNode. This can happen during concurrent
initialization of subscription ZNode by multiple instances. We can
safely ignore this exception as two concurrent initialization should
ideally produce the same set of children.
=> Migrate subscription to idempotent approach

api-consumption/src/main/java/org/zalando/nakadi/service/subscription/StreamingContext.java, core-common/src/main/java/org/zalando/nakadi/service/subscription/zk/NewZkSubscriptionClient.java, core-common/src/main/java/org/zalando/nakadi/service/subscription/zk/ZkSubscriptionClient.java, core-common/src/test/java/org/zalando/nakadi/service/subscription/zk/NewZkSubscriptionClientTest.java
the commit changes used locking mechanism of rebalance function. the change removes  usage of global curator lock in favor of using optimistic locking meaning: 1)read topology with zk node version 2)prepare change set 3)try to write to zk node with the read version number in step 1 if failed retry. the obsolete logic related to hash generation for sessions transfer was removed.
=> rebalance uses optimistic locking

acceptance-test/src/acceptance-test/java/org/zalando/nakadi/webservice/hila/SubscriptionAT.java, api-consumption/src/main/java/org/zalando/nakadi/service/subscription/StreamingContext.java, api-consumption/src/main/java/org/zalando/nakadi/service/subscription/state/ClosingState.java, api-consumption/src/main/java/org/zalando/nakadi/service/subscription/state/StartingState.java, api-consumption/src/main/java/org/zalando/nakadi/service/subscription/state/StreamingState.java, api-cursors/src/main/java/org/zalando/nakadi/service/CursorsService.java, core-common/src/main/java/org/zalando/nakadi/service/subscription/zk/AbstractZkSubscriptionClient.java, core-common/src/main/java/org/zalando/nakadi/service/subscription/zk/NewZkSubscriptionClient.java, core-common/src/main/java/org/zalando/nakadi/service/subscription/zk/ZkSubscriptionClient.java, core-services/src/main/java/org/zalando/nakadi/service/RepartitioningService.java, core-services/src/main/java/org/zalando/nakadi/service/SubscriptionInitializer.java
methods which used `runLocked` method were migrated to optimistic locking. in this commit `runLocked] method is removed leaving only not locking methods to update subscription states
=> remove nakadi zookeeper lock call

acceptance-test/src/acceptance-test/java/org/zalando/nakadi/repository/kafka/KafkaRepositoryAT.java, core-common/src/main/java/org/zalando/nakadi/repository/kafka/KafkaLocationManager.java, core-common/src/main/java/org/zalando/nakadi/repository/kafka/KafkaSettings.java
In order to utilize kafka feature of closest replica consumption, the `client.rack` property should become available to for modification. 
This PR exposes the property as a spring property with name `nakadi.kafka.client.rack`
=> Be able to set client.rack for KafkaConsumer

acceptance-test/src/acceptance-test/java/org/zalando/nakadi/webservice/hila/HilaRebalanceAT.java, api-consumption/src/main/java/org/zalando/nakadi/service/subscription/StreamingContext.java, api-consumption/src/main/java/org/zalando/nakadi/service/subscription/SubscriptionRebalancer.java, api-consumption/src/main/java/org/zalando/nakadi/service/subscription/state/StartingState.java, api-consumption/src/test/java/org/zalando/nakadi/service/subscription/SubscriptionRebalancerTest.java, core-services/src/main/java/org/zalando/nakadi/service/SubscriptionInitializer.java
In order to synchronize behavior of several instances, there is an optimistic lock is in use.
Unfortunately one place was not handled properly - registration of the streaming session.
The problem is that streaming code is allowing to have more streaming sessions, than there are partitions, or have more than 1 streaming connections for manually assigned partition.
This causes some problems - after unsuccessful rebalance (obviously rebalance is saying that it can't stream 2 partitions to 3 connections) some of streaming connections are dying.
In order to avoid that, there should be 2 changes made:
1. Session should be registered in optimistic manner (check, register, check. If not - session must be removed, https://github.com/zalando/nakadi/blob/master/api-consumption/src/main/java/org/zalan …
=> better track inability to join streaming on consumption

acceptance-test/src/acceptance-test/java/org/zalando/nakadi/webservice/CursorsServiceAT.java, api-consumption/src/main/java/org/zalando/nakadi/service/subscription/StreamingContext.java, api-consumption/src/main/java/org/zalando/nakadi/service/subscription/state/CleanupState.java, api-cursors/src/main/java/org/zalando/nakadi/service/CursorsService.java, api-metastore/src/main/java/org/zalando/nakadi/service/SubscriptionService.java, core-common/src/main/java/org/zalando/nakadi/repository/zookeeper/CuratorFrameworkRotator.java, core-common/src/main/java/org/zalando/nakadi/repository/zookeeper/ZooKeeperHolder.java, core-common/src/test/java/org/zalando/nakadi/repository/zookeeper/CuratorFrameworkRotatorTest.java
at the moment when zk client is taken it is not always closed which violaties a good practice to release whatever you acquired. it also prevents rotating curator framework from working properly because it is taken, but never returned.
=> close zk client when it was taken

acceptance-test/src/acceptance-test/java/org/zalando/nakadi/webservice/CursorsServiceAT.java, acceptance-test/src/acceptance-test/java/org/zalando/nakadi/webservice/hila/HilaRepartitionAT.java, api-consumption/src/test/java/org/zalando/nakadi/service/subscription/state/StreamingStateTest.java, core-common/src/main/java/org/zalando/nakadi/service/subscription/zk/NewZkSubscriptionClient.java, core-common/src/main/java/org/zalando/nakadi/service/subscription/zk/ZkSubscriptionClient.java, core-common/src/test/java/org/zalando/nakadi/service/subscription/zk/NewZkSubscriptionClientTest.java, core-common/src/test/java/org/zalando/nakadi/service/subscription/zk/ZkSubscriptionClientTest.java
since migration to optimistic locking(https://github.com/zalando/nakadi/pull/1280) there is no need to have session hash to perform rebalance
=> remove unused session hash

acceptance-test/src/acceptance-test/java/org/zalando/nakadi/webservice/hila/HilaRebalanceAT.java, acceptance-test/src/acceptance-test/java/org/zalando/nakadi/webservice/hila/HilaRepartitionAT.java, app/src/main/java/org/zalando/nakadi/config/AuthenticationConfig.java
> Zalando ticket : https://github.bus.zalan.do/aruha/team-aruha/issues/82
The DefaultTokenInfoRequestExecutor treats not being able to validate a
token, probably because the tokenInfo endpoint is not working, as the
token not being valid. Adding NakadiTokenInfoRequestExecutor to
differentiate the problems with tokenInfo endpoint and throw a
ServiceTemporarilyUnavailableException exception when the tokenInfo is
not working.
=> 503 when token info down

core-common/src/main/java/org/zalando/nakadi/repository/kafka/KafkaTopicRepository.java, core-common/src/test/java/org/zalando/nakadi/repository/kafka/KafkaTopicRepositoryTest.java
> Zalando ticket : 764
At the time when Nakadi requests partition information from Kafka Producer, it can happen that a partition can have no broker as a leader. In this case, chances are that the event will not get published by Kafka Producer.
Currently, Nakadi throws a null pointer exception that fails the entire batch.
=> Leaderless partitions should not fail publishing

settings.gradle
The `core-publishing` module is no present in the Nakadi codebase now.
The `core-publishing` entry in the settings.gradle is simply creating
empty directory that is not committed to the repo and generating an
empty Jar file as well. Removing this entry to cleanup the
`settings.gradle`.
=> Removing core-publishing module from settings.gradle

api-consumption/src/main/java/org/zalando/nakadi/service/subscription/StreamingContext.java, api-consumption/src/test/java/org/zalando/nakadi/service/subscription/StreamingContextTest.java
This restores the `sessionRegistered` flag, but makes sure to set it early and
to clean it before attempting to delete the node in ZooKeeper.
Zalando ticket : 788
=> Be prepared for multiple calls to unregister session

api-consumption/src/main/java/org/zalando/nakadi/service/subscription/StreamingContext.java
In case ZooKeeper client has a problem we might not actually delete the
session's node, so let it try another time if needed by not clearing the flag
just yet.
Zalando ticket : 788
=> Fine-tune unregisterSession

app/src/main/java/org/zalando/nakadi/service/job/ExclusiveJobWrapper.java, core-common/src/main/java/org/zalando/nakadi/service/subscription/zk/AbstractZkSubscriptionClient.java, core-common/src/test/java/org/zalando/nakadi/service/subscription/zk/NewZkSubscriptionClientTest.java
The background attempts to retry the delete operations were causing more harm
than good.
We do not rely on the deletes to always work as the nodes are ephemeral and
will be removed eventually within the next ZooKeeper client rotation interval.
=> Stop relying on Curator's guarantees

api-consumption/src/main/java/org/zalando/nakadi/service/subscription/state/StreamingState.java
The 'failed to write data to output' state is known to happen often, but it's
OK.  Don't log the full exception trace in this case.
=> Less noisy logging in StreamingState

acceptance-test/src/acceptance-test/java/org/zalando/nakadi/webservice/EventTypeAT.java, core-common/src/main/java/org/zalando/nakadi/domain/EventTypeBase.java
> Zalando ticket : team-aruha/issues/752
When annotations or labels is missing in the input, the existing value
should be preserved. This fix remove creation of empty annotation and
label objects when they are missing in the imput, thereby preserving the
existing values.
=> Bugfix: Do not overwrite annotations and labels when missing.

docs/_data/nakadi-event-bus-api.yaml
Minor editorial update to make it consistent with API Guideline definition (see https://github.com/zalando/restful-api-guidelines/pull/659) and to avoid misunderstandings still observed in production.
Just an update of field descriptions in API definition -- no semantic or code changes, no test needed, but re-deployment of API spec.
=> Update: API definition of occurred_at vs. received_at event attributes

docs/_data/nakadi-event-bus-api.yaml
* Removed "Work in progress" from labels and annotations.
* Mentioning that the prefix "nakadi.io" is reserved for the internal use of nakadi.
=> Updated the API documentation about Labels and Annotations

api-metastore/src/main/java/org/zalando/nakadi/controller/PartitionsController.java, api-metastore/src/test/java/org/zalando/nakadi/controller/PartitionsControllerTest.java, core-common/src/main/java/org/zalando/nakadi/view/EventTypePartitionView.java
Remove some outdated code (generation of response code, usage of incorrect DTO) in `event-types/{et}/partitions*` calls
=> Remove some stale code

api-metastore/src/main/java/org/zalando/nakadi/controller/CursorOperationsController.java, api-metastore/src/main/java/org/zalando/nakadi/controller/PartitionsController.java, api-metastore/src/test/java/org/zalando/nakadi/controller/PartitionsControllerTest.java
Removed auth checks for READ operation on 
- /event-types/{name}/partitions
- /event-types/{name}/cursor-distances
End point /subscriptions/{id}/stats is unchanged as it is using only View authorization already.
Authorization for View Operation are still done.
=> Removed READ authorization check for some metadata endpoints

api-metastore/src/main/java/org/zalando/nakadi/config/SchemaValidatorConfig.java, api-metastore/src/main/java/org/zalando/nakadi/validation/schema/CompatibilityModeChangeConstraint.java, api-metastore/src/main/java/org/zalando/nakadi/validation/schema/PartitionStrategyConstraint.java, api-metastore/src/test/java/org/zalando/nakadi/controller/EventTypeControllerTest.java, api-metastore/src/test/java/org/zalando/nakadi/controller/EventTypeControllerTestCase.java, api-metastore/src/test/java/org/zalando/nakadi/validation/schema/PartitionStrategyConstraintTest.java
Right now nakadi admins are pretty limited in the actions that may be executed. 
This PR allows nakadi admins to change event type partitioning strategy to any value.
=> Allow to change partitioning strategy to nakadi admins

core-common/src/main/java/org/zalando/nakadi/metrics/EventTypeMetrics.java
Spikes in traffic are not always correlated in increas of number of events
published.  These new metrics should provide more direct correlation, as they
are based on batch size in bytes, not in the number of events.
=> Add two more publishing metrics based on batch size (in bytes)

api-consumption/src/main/java/org/zalando/nakadi/service/subscription/state/StartingState.java, core-common/src/main/java/org/zalando/nakadi/exceptions/runtime/NoStreamingSlotsAvailable.java
Sometimes it might be useful to know what subscription was it.
=> Add subscription id to the "no free slots" log

docs/_data/nakadi-event-bus-api.yaml
Docs only: make it clear that POST /subscriptions will not update an existing subscription
In an [internal discussion](https://chat.google.com/room/AAAALJjUd9k/7gM7kMlsUa8) some confusion was noticed about the behavior
of the `POST /subscriptions` endpoint when a subscription with the same keys
already exists (specifically about the cursors).
This change should make this a bit clearer, adding a bit of text to the endpoint
and the subscription object definition.
=> docs: Create does not update a subscription

core-common/src/main/java/org/zalando/nakadi/service/subscription/zk/AbstractZkSubscriptionClient.java
The message to remove is never used, and is executed many times a second, flooding logs with info level (while it is more of a trace level). 
Instead of changing the level it was intentionally removed.
=> log less useless messages

app/src/main/java/org/zalando/nakadi/config/AuthenticationConfig.java
Fix copy/paste problem in `AuthenticationConfig` class.
=> Fix typo: getLocalTokenInfoUrl()

app/src/main/java/org/zalando/nakadi/filters/LoggingFilter.java
No reason not to use the function defined for this purpose.
=> Use isAccessLogEnabled()

.gitignore, acceptance-test/src/acceptance-test/java/org/zalando/nakadi/repository/kafka/KafkaRepositoryAT.java, acceptance-test/src/acceptance-test/java/org/zalando/nakadi/repository/kafka/KafkaTestHelper.java, acceptance-test/src/acceptance-test/java/org/zalando/nakadi/webservice/EventTypeAT.java, acceptance-test/src/acceptance-test/java/org/zalando/nakadi/webservice/PartitionsControllerAT.java, core-common/src/main/java/org/zalando/nakadi/domain/BatchItem.java, core-common/src/main/java/org/zalando/nakadi/domain/EventOwnerHeader.java, core-common/src/main/java/org/zalando/nakadi/repository/kafka/KafkaFactory.java, core-common/src/main/java/org/zalando/nakadi/repository/kafka/KafkaLocationManager.java, core-common/src/main/java/org/zalando/nakadi/repository/kafka/KafkaTopicRepository.java, core-common/src/test/java/org/zalando/nakadi/domain/EventOwnerHeaderTest.java, core-common/src/test/java/org/zalando/nakadi/repository/kafka/KafkaFactoryTest.java, core-common/src/test/java/org/zalando/nakadi/repository/kafka/KafkaTopicRepositoryTest.java
Nakadi needs to use byte serializers in order to work with binary data, the change is tech refactoring as precondition for binary formats in Nakadi
=> use ByteArraySerializer for producer

docs/_documentation/using_consuming-events-hila.md
Docs only: make it clear that POST /subscriptions will not update an existing subscription
It turns out that I missed this file in #1350.
(This is for https://nakadi.io/manual.html#creating-subscriptions)
=> docs: POST /subscriptions doesn't update (part 2)

acceptance-test/src/acceptance-test/java/org/zalando/nakadi/repository/kafka/KafkaRepositoryAT.java, core-common/src/main/java/org/zalando/nakadi/repository/kafka/KafkaLocationManager.java, core-common/src/main/java/org/zalando/nakadi/repository/kafka/KafkaSettings.java
at the moment it is not possible to set kafka client compression type using env var, it is hardcoded value of lz4
=> provide Kafka Client compression type via env var

core-common/src/main/java/org/zalando/nakadi/repository/kafka/KafkaTopicRepository.java
the change brings clarity on which exception occured in case of timeout
=> indicate which exception occured in case of timeout

docs/_data/nakadi-event-bus-api.yaml
It was referring to `partition_resolution_strategy`, which does not exist.
=> Fix typo in API desc EventType.partition_key_fields

acceptance-test/src/acceptance-test/java/org/zalando/nakadi/repository/kafka/KafkaRepositoryAT.java, app/src/main/resources/application.yml, core-common/src/main/java/org/zalando/nakadi/repository/kafka/KafkaLocationManager.java, core-common/src/main/java/org/zalando/nakadi/repository/kafka/KafkaSettings.java
Enabling idempotent producer requires `retries` to be set to a value greater
than 0.  The default value is effectively "endless retries", but we might want
to stop trying earlier, so make it configurable and set it to a small value
for now.
=> Make kafka producer retries setting configurable

app/src/main/resources/application.yml, core-common/src/main/java/org/zalando/nakadi/repository/kafka/KafkaLocationManager.java
Looks like it has a negative effect on Kafka G1 Old gen usage.
=> Disable idempotent producer

core-common/src/main/java/org/zalando/nakadi/repository/kafka/KafkaCursor.java
Profiling showed that `org.zalando.nakadi.repository.kafka.KafkaCursor.toNakadiOffset` is one of the hotspots. This can be seen in JFR/JMC's allocation profiling. For example:
```
java.util.regex.Pattern.matcher(CharSequence)
java.util.Formatter.parse(String)
java.util.Formatter.format(Locale, String, Object[])
java.util.Formatter.format(String, Object[])
java.lang.String.format(String, Object[])
org.zalando.nakadi.repository.kafka.KafkaCursor.toNakadiOffset(long)
```
`java.lang.String.format` is very unefficient and should be avoided in hotspots. This PR replaces the usage of `String.format` with `StringUtils.leftPad` in `KafkaCursor.toNakadiOffset`.
=> Replace slow String.format call with alternative implementation using StringUtils.leftPad

core-common/build.gradle
According to the release notes https://github.com/facebook/zstd/releases/tag/v1.5.2:
> This release also corrects a performance regression that was introduced in v1.5.0 that slows down compression of very small data when using the streaming API. Issue https://github.com/facebook/zstd/issues/2966 tracks that topic.
Closes #1399
=> Bump zstd library to 1.5.2

core-common/src/test/java/org/zalando/nakadi/repository/kafka/KafkaRecordDeserializerTest.java
1. It seems that "similar" is "almost equal".
2. A failing test report is more helpful.
=> Assert equality of JSONObject::toMap instead of similar()

core-services/src/main/java/org/zalando/nakadi/service/SchemaService.java, core-services/src/main/java/org/zalando/nakadi/validation/EventValidatorBuilder.java, core-services/src/main/java/org/zalando/nakadi/validation/JsonSchemaEnrichment.java, core-services/src/test/java/org/zalando/nakadi/service/SchemaServiceTest.java, core-services/src/test/java/org/zalando/nakadi/validation/JsonSchemaEnrichmentTest.java, core-services/src/test/resources/compatible-additional-item-schema.json
Internal ticket no: 1146
Due to a recent change, schema validation was being perfomed on effective schema accidentally. This change fixes the `effectiveSchema()` method so that it does not mutate input parameters.
=> Fix incorrect schema validation during compatible mode

core-services/src/main/java/org/zalando/nakadi/service/AvroSchemaCompatibility.java
It seems to be less confusing this way.
=> Swap order of reader and writer in avro compatibility checks

core-common/src/main/java/org/zalando/nakadi/util/CompressionBodyRequestFilter.java, core-common/src/test/java/org/zalando/nakadi/util/CompressionBodyRequestFilterTest.java
- Override block reading methods for efficiency
- Delegate `isReady/isFinished/setReadListener` to the wrapped stream
=> More effecient reading of compressed request body

app/src/main/java/org/zalando/nakadi/filters/LoggingFilter.java
Some user agents set the Content-Length header, but not all.  Use request and
response wrapper class together with counting input/output stream wrappers.
=> Reliably track request and response content length

docs/_data/nakadi-event-bus-api.yaml
While generating example of api definition the values that are used to provide several examples are leading to a weirdly-looking value with ` ,` in the middle. The better approach to avoid it - use single example
=> Make example in api definition better-looking

api-consumption/src/main/java/org/zalando/nakadi/controller/SubscriptionStreamController.java
The common cases are spamming the logs with useless stacktraces.
Follow-up on: #1302
=> Avoid logging stacktrace on streaming exceptions

core-services/src/main/java/org/zalando/nakadi/partitioning/PartitionResolver.java, core-services/src/main/java/org/zalando/nakadi/partitioning/RandomPartitionStrategy.java, core-services/src/test/java/org/zalando/nakadi/partitioning/RandomPartitionStrategyTest.java
The `Random` class is synchronized, but we don't need that for our use case.
=> Use ThreadLocalRandom for partitioning

Dockerfile, delivery.yaml, docker-compose.yml
Switch to JRE Eclipse Temurin 11 + Use Zalando Container Registry
Add support for multi-arch OCI
=> Switch to JRE Eclipse Temurin 11 + Use Zalando Container Registry

api-metastore/src/test/java/org/zalando/nakadi/controller/EventTypeControllerTestCase.java, core-common/build.gradle, core-common/src/main/java/org/zalando/nakadi/domain/EventTypeStatistics.java, core-common/src/main/java/org/zalando/nakadi/repository/kafka/KafkaConfig.java, core-common/src/main/java/org/zalando/nakadi/repository/kafka/PartitionsCalculator.java, core-common/src/test/java/org/zalando/nakadi/repository/kafka/PartitionsCalculatorTest.java
Remove partition count logic that depended on messagePerMinute and messageSize from default statistics
=> Update partition count logic

core-services/src/main/java/org/zalando/nakadi/service/timeline/TimelineService.java, core-services/src/test/java/org/zalando/nakadi/service/timeline/TimelineServiceTest.java
When there are multiple active timelines across different Kafka clusters, repartitioning breaks.
=> Quickfix for an edge case where repartition breaks

core-common/src/main/java/org/zalando/nakadi/metrics/NakadiMetricsModule.java, core-services/src/main/java/org/zalando/nakadi/service/publishing/EventPublisher.java, core-services/src/test/java/org/zalando/nakadi/service/publishing/EventPublisherTest.java
Measure how many partitioning keys are published per batch. It should help to understand the latencies in case Nakadi publishes events by keys in order (sequential)
=> metrics to measure paritioning keys per batch

api-consumption/src/main/java/org/zalando/nakadi/service/subscription/state/PartitionData.java
Extend log message to include the offset just compared.
@tanvir002700 noted in an internal chat a situation (running Nakadi locally)
where this error message is raised. When trying to look into it, I noticed that the
offset printed as part of the error message is not too helpful:
Nakadi is comparing `offset` and `sentOffset`, but was logging `sentOffset` and `commitOffset`.
This PR adds `offset` to the log message, hopefully making it easier to debug problems when this occurs.
=> fix log message for commits in the future

core-common/src/main/java/org/zalando/nakadi/metrics/EventTypeMetrics.java, core-common/src/main/java/org/zalando/nakadi/metrics/NakadiMetricsModule.java, core-services/src/main/java/org/zalando/nakadi/service/publishing/EventPublisher.java, core-services/src/test/java/org/zalando/nakadi/service/publishing/EventPublisherTest.java
This reverts commit 88ce0b1963336c3b7bb5f96b3e249db0921b9bb5 and 980f874af13fa1e796224d5863e460d91def0140, because test of the metrics was done and they are not needed anymore
=> Revert "metrics to measure paritioning keys per batch (#1478)"

core-common/src/main/java/org/zalando/nakadi/util/CompressionBodyRequestFilter.java, core-common/src/test/java/org/zalando/nakadi/util/CompressionBodyRequestFilterTest.java
at the moment nakadi throws 503 in case content encoding is set to gzip and the content is not gzip format. the commit changes the behaviour that nakadi responds with 400 in case of the content is not gzip format. it is harder to achieve for zstd because zstdinput stream does not validate the content on the start, the desicion is to keep it (the pubslishing will fail and user connection will be abrupted)
=> respond 'bad request' if content is not gzip

acceptance-test/src/acceptance-test/java/org/zalando/nakadi/repository/kafka/KafkaRepositoryAT.java, api-metastore/src/test/java/org/zalando/nakadi/controller/EventTypeControllerTestCase.java, app/src/main/resources/application.yml, core-common/src/main/java/org/zalando/nakadi/config/NakadiSettings.java, core-common/src/main/java/org/zalando/nakadi/repository/KafkaRepositoryCreator.java, core-common/src/main/java/org/zalando/nakadi/repository/kafka/KafkaFactory.java, core-common/src/test/java/org/zalando/nakadi/repository/kafka/KafkaFactoryTest.java, core-services/src/test/java/org/zalando/nakadi/service/publishing/EventPublisherTest.java
A Kafka producer is single-threaded.  With our setup it makes sense to have more than one of them active, for better utilization of resources.
Internal ticket: 1298
=> Multiple active Kafka producers

core-common/src/main/java/org/zalando/nakadi/repository/KafkaRepositoryCreator.java
Seems like an oversight that we were creating two of them per topic repository.
=> Don't create extra KafkaLocationManager

acceptance-test/src/acceptance-test/java/org/zalando/nakadi/repository/kafka/KafkaRepositoryAT.java, acceptance-test/src/acceptance-test/java/org/zalando/nakadi/webservice/hila/HilaAT.java, acceptance-test/src/acceptance-test/java/org/zalando/nakadi/webservice/hila/HilaRepartitionAT.java, api-metastore/src/test/java/org/zalando/nakadi/controller/EventTypeControllerTestCase.java, api-publishing/src/main/java/org/zalando/nakadi/EventPublishingController.java, app/src/main/resources/application.yml, core-common/src/main/java/org/zalando/nakadi/config/NakadiSettings.java, core-common/src/main/java/org/zalando/nakadi/repository/KafkaRepositoryCreator.java, core-common/src/main/java/org/zalando/nakadi/repository/kafka/KafkaFactory.java, core-common/src/main/java/org/zalando/nakadi/repository/kafka/KafkaLocationManager.java, core-common/src/main/java/org/zalando/nakadi/repository/kafka/KafkaSettings.java, core-common/src/main/java/org/zalando/nakadi/repository/kafka/KafkaTopicRepository.java, core-common/src/main/java/org/zalando/nakadi/service/TracingService.java, core-common/src/main/java/org/zalando/nakadi/util/SLOBuckets.java, core-common/src/test/java/org/zalando/nakadi/repository/kafka/KafkaFactoryTest.java, core-common/src/test/java/org/zalando/nakadi/repository/kafka/KafkaTopicRepositoryTest.java, core-services/src/test/java/org/zalando/nakadi/service/publishing/EventPublisherTest.java
This is the evolution of #1488, where we already had multiple producers.
=> Dedicate a Kafka producer to each of the publishing SLO buckets

core-common/src/main/java/org/zalando/nakadi/domain/BatchItem.java, core-common/src/main/java/org/zalando/nakadi/repository/kafka/KafkaTopicRepository.java, core-common/src/test/java/org/zalando/nakadi/repository/kafka/KafkaTopicRepositoryTest.java
at the moment nakadi manually checks for the leader, that's not necessary because kafka producer does it for us. it also helps to keep the code clean and prepare for the future changes.
=> remove excessive check for the leader

core-services/src/main/java/org/zalando/nakadi/service/publishing/EventPublisher.java, core-services/src/test/java/org/zalando/nakadi/service/publishing/EventPublisherTest.java
We need to see how it grows over time to better understand the publisher performance degradation.
=> Count unique `event-type:partition` instances

core-services/src/main/java/org/zalando/nakadi/service/SchemaService.java
Its helpful for users if they see more meaningful errors that can point to the problem in their schema.
=> Add more detail to schema validation errors

acceptance-test/src/acceptance-test/java/org/zalando/nakadi/repository/kafka/KafkaRepositoryAT.java, api-metastore/src/main/java/org/zalando/nakadi/service/SubscriptionTimeLagService.java, api-metastore/src/test/java/org/zalando/nakadi/controller/EventTypeControllerTestCase.java, app/src/main/resources/application.yml, core-common/src/main/java/org/zalando/nakadi/config/NakadiSettings.java, core-common/src/main/java/org/zalando/nakadi/repository/KafkaRepositoryCreator.java, core-common/src/main/java/org/zalando/nakadi/repository/kafka/KafkaFactory.java, core-common/src/test/java/org/zalando/nakadi/repository/kafka/KafkaFactoryTest.java, core-services/src/main/java/org/zalando/nakadi/service/timeline/MultiTimelineEventConsumer.java, core-services/src/test/java/org/zalando/nakadi/service/publishing/EventPublisherTest.java
at the moment time lag service generates hundreds of consumers to calculate lag, because Kafka consumer is created per partition. the change brings pool of consumers which should avoid constant generation of new consumers.
=> pool kafka consumers for timelag checker, only for test

acceptance-test/src/acceptance-test/java/org/zalando/nakadi/webservice/hila/SubscriptionAT.java, core-common/src/main/java/org/zalando/nakadi/domain/Subscription.java
In subscription update API, when performing update if the new subscription had annotation/label value set then they were ignored. This PR fixes this and adds a test case to verify.
=> Persist annotations/labels on subscription update

app/src/main/resources/application.yml, core-common/src/main/java/org/zalando/nakadi/repository/kafka/KafkaFactory.java
1. For misc we always want to use the consumer pool to reduce the rate of creating consumers.
2. For the actual consumption stack we will be creating consumers normally.
=> Use Kafka consumer pool always, if it is there

core-common/src/main/java/org/zalando/nakadi/repository/kafka/KafkaFactory.java
=> Fix call to `getConsumer()` w/o client id not being pooled

api-metastore/src/main/java/org/zalando/nakadi/service/SubscriptionTimeLagService.java, api-metastore/src/test/java/org/zalando/nakadi/service/SubscriptionTimeLagServiceTest.java, app/src/main/resources/application.yml, core-common/src/main/java/org/zalando/nakadi/repository/KafkaRepositoryCreator.java, core-common/src/main/java/org/zalando/nakadi/repository/kafka/KafkaFactory.java, core-common/src/test/java/org/zalando/nakadi/repository/kafka/KafkaFactoryTest.java
the commit creates a pool of nakadi multi-timeline consumers to avoid excessive heap allocations on Kafka
that was especially possible because of prio refactoring #1516 and #1517
=> multi-timeline consumer pool for subscription lag

api-metastore/src/main/java/org/zalando/nakadi/service/SubscriptionTimeLagService.java, api-metastore/src/test/java/org/zalando/nakadi/service/SubscriptionTimeLagServiceTest.java, app/src/main/resources/application.yml, core-common/src/main/java/org/zalando/nakadi/repository/KafkaRepositoryCreator.java, core-common/src/main/java/org/zalando/nakadi/repository/kafka/KafkaFactory.java, core-common/src/test/java/org/zalando/nakadi/repository/kafka/KafkaFactoryTest.java, docker-compose.yml
the commit creates a pool of nakadi multi-timeline consumers to avoid excessive heap allocations on Kafka
that was especially possible because of prio refactoring https://github.com/zalando/nakadi/pull/1516 and https://github.com/zalando/nakadi/pull/1517
=> multi-timeline consumer pool 

api-metastore/src/main/java/org/zalando/nakadi/service/SubscriptionTimeLagService.java, api-metastore/src/test/java/org/zalando/nakadi/service/SubscriptionTimeLagServiceTest.java, app/src/main/resources/application.yml, core-common/src/main/java/org/zalando/nakadi/repository/KafkaRepositoryCreator.java, core-common/src/main/java/org/zalando/nakadi/repository/kafka/KafkaFactory.java, core-common/src/test/java/org/zalando/nakadi/repository/kafka/KafkaFactoryTest.java, docker-compose.yml
Reverts zalando/nakadi#1520
The solution is incomplete due to consumers being created often in the middle layer for checking earlies/newest offsets within partition.  We will have to find a different approach, but for now stick with the consumer pool at the bottom layer that covers every use.
=> Revert "multi-timeline consumer pool"

api-consumption/src/main/java/org/zalando/nakadi/service/subscription/state/PartitionData.java, api-consumption/src/main/java/org/zalando/nakadi/service/subscription/state/StreamingState.java, docker-compose.yml
Provide number of skipped events due to retention time when stream is opened
example:
```
{"cursor":{...},"events":[...],"info":{"debug":"Skipped events due to retention time passed, count: 1"}}
```
=> skipped events

acceptance-test/src/acceptance-test/java/org/zalando/nakadi/repository/kafka/KafkaRepositoryAT.java, core-common/src/main/java/org/zalando/nakadi/repository/kafka/KafkaLocationManager.java, core-common/src/main/java/org/zalando/nakadi/repository/kafka/KafkaSettings.java, core-common/src/test/java/org/zalando/nakadi/repository/kafka/KafkaLocationManagerTest.java, docker-compose.yml
Introduce `SECURITY_PROTOCOL`, `SASL_MECHANISM`, `KAFKA_USERNAME` and `KAFKA_PASSWORD` Nakadi settings that will allow Nakadi to configure Kafka clients with security SASL Plain username + password.
Nakadi discovers the list of Brokers by looking in all registered storages entries in Zookeeper, and iterates `/brokers/ids` to discover every broker IP address and Port. This PR introduces `PREFERRED_LISTENER_PORT` setting that allow Nakadi to connect to different listeners in Kafka(previously would connect to the port available in Zookeeper entry, which is the first port of all available listeners, and also an internal Zookeeper structure).
=> Implement optional settings that enable Nakadi security

api-metastore/src/main/java/org/zalando/nakadi/model/AuthorizationAttributeQueryParser.java, api-metastore/src/main/java/org/zalando/nakadi/service/SubscriptionService.java, build.gradle
Update `org.apache.zookeeper` dependency to `3.6.1` (to reduce noisy logging) which includes fix for:
https://issues.apache.org/jira/browse/ZOOKEEPER-4376
This change should be compatible with the Zookeeper server `3.6.1`.
=> Update zookeeper client

core-common/src/main/java/org/zalando/nakadi/repository/kafka/KafkaTopicRepository.java
Neither `NotLeaderOrFollower` nor `Timeout` is a good reason for resetting the producer.
=> Relax Kafka producer reset cases

core-services/src/main/java/org/zalando/nakadi/cache/EventTypeCache.java
at the moment if value was evicted and load from database fails cache wont have a value, that will create unavailability on the publishing path. the commit changes that behaviour to have value ecivted from the cache only in case the value was successfully loaded
=> evict cache value only if load is successful

app/src/main/java/org/zalando/nakadi/config/AuthenticationConfig.java, app/src/main/java/org/zalando/nakadi/config/NakadiResourceServerTokenServices.java, app/src/test/java/org/zalando/nakadi/config/NakadiResourceServerTokenServicesTest.java
In Nakadi, there is logic to retry load token info first from local token and then fallback to remote token info on failure. This logic does not account for when the local token info fails with timeout/IO exception. This PR introduces fix so that it accounts for IO exception and retries remote token info.
=> allow fallback to remote on IO error

acceptance-test/src/acceptance-test/java/org/zalando/nakadi/webservice/EventTypeAT.java, core-common/src/main/java/org/zalando/nakadi/exceptions/runtime/EventOwnerExtractionException.java, core-services/src/main/java/org/zalando/nakadi/service/SchemaService.java, core-services/src/main/java/org/zalando/nakadi/service/publishing/EventOwnerExtractorFactory.java, core-services/src/main/java/org/zalando/nakadi/service/publishing/EventPublisher.java, core-services/src/main/java/org/zalando/nakadi/service/publishing/check/EventOwnerSelectorCheck.java, core-services/src/test/java/org/zalando/nakadi/service/SchemaServiceTest.java, core-services/src/test/java/org/zalando/nakadi/service/publishing/EventOwnerExtractorTest.java, core-services/src/test/resources/schema-with-retailer-id.json
- Validate that the field is present when creating/updating event types
- Log a warning if the field is still missing or `null` when publishing events
Internal ticket: 1431
=> Validate `event_owner_selector` path refers to a field in the schema

core-common/src/main/java/org/zalando/nakadi/validation/ISO4217CurrencyCodeValidator.java, core-common/src/test/java/org/zalando/nakadi/validation/ISO4217CurrencyCodeValidatorTest.java, core-services/src/main/java/org/zalando/nakadi/validation/EventValidatorBuilder.java
Changes `ISO4217CurrencyCodeValidator` to a proper schema (format) validator (instead of logging invalid values) for alphabetic ISO 4217 currency codes.
This is follow up of #1529.
Goal: reject publishing events with event type schemas' containing `iso-4217` format.
The feature is not feature toggled (there is some inverse dependency of the `core-common` and the sub-project containing `FeatureToggleService`. For simplicity of implementation, this change assumes that there are no publishers violating this (new) restriction.
=> Enforce alphabetic ISO-4217 currency format validation

acceptance-test/src/acceptance-test/java/org/zalando/nakadi/repository/kafka/KafkaRepositoryAT.java, app/src/main/resources/application.yml, core-common/src/main/java/org/zalando/nakadi/repository/kafka/KafkaLocationManager.java, core-common/src/main/java/org/zalando/nakadi/repository/kafka/KafkaSettings.java
The main objective is to enable retries, which we can only safely do when using the idempotence feature.
This change only enables us to configure idempotent producer with retries, but doesn't change the current default settings.
=> Use idempotent producer once again to enable safe retries

core-services/src/main/java/org/zalando/nakadi/service/SchemaService.java, core-services/src/test/java/org/zalando/nakadi/service/SchemaServiceTest.java
Change JSON event-type creation/validation to throw client error (`422`) instead of server error (`5xx`) on unsupported/unknown meta-schema URLs (`"$schema": "..."` in schema-JSON).
=> Return client error on unknown meta schema

docs/_data/nakadi-event-bus-api.yaml
Make the update `cleanup_policy` documentation in sync with implementation:
https://github.com/zalando/nakadi/blob/964ca19d5c5e96a314f44122c1f7178e18be09ce/api-metastore/src/main/java/org/zalando/nakadi/service/EventTypeService.java#L286-L289
=> Update documentation note for allowed/supported event types' `cleanup_policy` updates.

core-common/src/main/java/org/zalando/nakadi/service/TracingService.java, core-services/src/main/java/org/zalando/nakadi/service/publishing/BinaryEventPublisher.java, core-services/src/main/java/org/zalando/nakadi/service/publishing/EventPublisher.java
To allow the publishers to learn about their batch size distribution.
Using the same name as in `nakadi.batch.published` event: https://github.com/zalando/nakadi/blob/master/core-common/src/main/resources/avro-schema/nakadi.batch.published.avsc#L24
=> Add `number_of_events` tag to `publish_events` spans

api-publishing/src/main/java/org/zalando/nakadi/EventPublishingController.java, core-services/src/main/java/org/zalando/nakadi/service/publishing/BinaryEventPublisher.java, core-services/src/main/java/org/zalando/nakadi/service/publishing/EventPublisher.java
Turns out we don't always have the span in the binary publisher (due to it being used for internal KPI events publishing).
=> Move setting of `number_of_events` tag to controller

acceptance-test/src/acceptance-test/java/org/zalando/nakadi/webservice/hila/HilaAT.java, acceptance-test/src/acceptance-test/java/org/zalando/nakadi/webservice/utils/TestStreamingClient.java, api-consumption/src/main/java/org/zalando/nakadi/service/subscription/state/ClosingState.java, api-consumption/src/main/java/org/zalando/nakadi/service/subscription/state/StreamingState.java
the fix ensures the closing state does not lose failed commits in case the stream is closed before commit timeout reached
=> store failed commit on exit

api-cursors/src/main/java/org/zalando/nakadi/service/CursorsService.java, core-common/src/main/java/org/zalando/nakadi/service/subscription/zk/ZkSubscriptionClient.java, core-common/src/test/java/org/zalando/nakadi/service/subscription/zk/ZkSubscriptionClientTest.java, core-services/src/main/java/org/zalando/nakadi/service/SubscriptionValidationService.java
* Add support submitting DLQ refeed offsets for subscription api
* Allows to add new event types to subscription's topology (stored in Zookeeper)
Note: this is shared code for verified PoC (#1554) and the planned rollout approach #1558.
=> Add support submitting DLQ refeed offsets for subscription api

acceptance-test/src/acceptance-test/java/org/zalando/nakadi/webservice/hila/HilaAT.java, acceptance-test/src/acceptance-test/java/org/zalando/nakadi/webservice/utils/TestStreamingClient.java, api-consumption/src/main/java/org/zalando/nakadi/service/subscription/state/StreamingState.java
The current behaviour that Auto DLQ goes back to normal mode once it found one bad event.  It can happen that there are more events after that bad one. Current behaviour will create longer bad events identification time.
Internal ticket: 1537
=> Feed events one by one until the end of problematic batch

api-consumption/src/main/java/org/zalando/nakadi/service/subscription/StreamingContext.java, api-consumption/src/main/java/org/zalando/nakadi/service/subscription/SubscriptionStreamerFactory.java, api-consumption/src/test/java/org/zalando/nakadi/service/subscription/StreamingContextTest.java, app/src/main/java/org/zalando/nakadi/service/job/DlqRedriveEventTypeAttachmentJob.java, core-common/src/main/java/org/zalando/nakadi/service/subscription/zk/NewZkSubscriptionClient.java, core-common/src/main/java/org/zalando/nakadi/service/subscription/zk/SubscriptionRebalancer.java, core-common/src/main/java/org/zalando/nakadi/service/subscription/zk/ZkSubscriptionClient.java, core-common/src/test/java/org/zalando/nakadi/service/subscription/zk/SubscriptionRebalancerTest.java
This change rebalances subscription's topology among current sessions dynamically, upon attaching the DLQ event type to the subscription's topology.
This is considered to be more graceful behavior (towards consuming applications), compared to the current (workaround, #1579) approach where the sessions got stopped (forcing consuming applications to reconnect).
=> Rebalance subscription's sessions on DLQ event type attachment to topology

api-publishing/src/main/java/org/zalando/nakadi/PublishingResultConverter.java, core-common/src/main/java/org/zalando/nakadi/domain/BatchItem.java, core-common/src/main/java/org/zalando/nakadi/domain/BatchItemResponse.java, core-services/src/test/java/org/zalando/nakadi/service/publishing/EventPublisherTest.java
Expose partition in partial success reponses.
Zalando ticket : ARUHA-1619
Currently if an event fails to be published it returns a response of the following format:
```
HTTP/1.1 207 Multi-Status
...
[
{
"eid": "669B7E68-7654-4733-B3A9-BF36B41E4E59",
"publishing_status": "submitted",
"step": "publishing",
"detail": ""
},
{
"eid": "26f29c33-a9e2-421f-80fb-1696ee2d60d9",
"publishing_status": "failed", <-- NOTICE: failed event
"step": "publishing",
"detail": "internal error"
}
]
```
with this change each event's response record will contain a `partition` field with the partition number i.e. the response would look like:
```
HTTP/1.1 207 Multi-Status
...
[
{
"eid": "669B7E68-7654-4733-B3A9-BF36B41E4E59",
"publishing_status": "submitted",
"partition": "3", <-- newly exposed field
"step": …
```
=> Expose partition in BatchItemResponse (useful for 207s)

api-consumption/src/main/java/org/zalando/nakadi/service/EventStream.java, api-consumption/src/main/java/org/zalando/nakadi/service/subscription/StreamingContext.java, api-consumption/src/test/java/org/zalando/nakadi/service/subscription/StreamingContextTest.java, api-publishing/src/main/java/org/zalando/nakadi/EventPublishingController.java, core-common/src/main/java/org/zalando/nakadi/domain/HeaderTag.java, core-common/src/main/java/org/zalando/nakadi/domain/KafkaHeaderTagSerde.java, core-common/src/main/java/org/zalando/nakadi/repository/kafka/KafkaTopicRepository.java, core-common/src/main/java/org/zalando/nakadi/service/TracingService.java, core-common/src/test/java/org/zalando/nakadi/domain/KafkaHeaderTagSerializerTest.java, core-services/src/main/java/org/zalando/nakadi/service/publishing/BinaryEventPublisher.java, core-services/src/main/java/org/zalando/nakadi/service/publishing/EventPublisher.java, core-services/src/test/java/org/zalando/nakadi/service/publishing/EventPublisherTest.java
1. Reuse `HeaderTag` for adding the debug header.
2. Use `EnumMap` for slightly more efficiency.
3. Log it when we detect misplaced event.
=> Log debug topic id header for misplaced events
