local-test/start-local-kafka.sh
nakadi/test/test_common.py

I think it 8 partitions for test kafka will be enough

decreased amount of partitions in test kafka

---

.gitignore
.travis.yml
nakadi/event_stream.py
nakadi/hack.py
nakadi/kafka_pool.py
nakadi/swagger.yaml
nakadi/test/test_common.py
nakadi/test/test_hack.py
nakadi/test/test_streaming.py
nakadi/utils/request_helpers.py
requirements.txt
run_local.py

@valgog @tmuehl Please take a look

Stream from multiple partitions

---

nakadi/swagger.yaml

I have reformatted the file and cleaned up the Markdown a little bit

reformat Swagger file and clean up markdown

---

nakadi/event_stream.py

Besides that move duplicated code which creates batch into separate function

Do not decode-encode json when building batch

---

nakadi/hack.py
nakadi/swagger.yaml
nakadi/test/test_hack.py

@CyberDem0n @jkliff @tmuehl @valgog

added endpoint to post batch of events

---

nakadi/config.py
nakadi/event_stream.py
nakadi/hack.py
nakadi/metrics.py
nakadi/test/test_common.py
nakadi/test/test_hack.py
nakadi/test/test_streaming.py

Monitoring

---

README.md

Rewritten the README file to better reflect our current understanding of the project

Rewritten the README file

---

nakadi/config.py
nakadi/hack.py
nakadi/test/test_common.py

@CyberDem0n @tmuehl @valgog @jkliff

fixed #40 added possibility to push from several applications

---

nakadi/swagger.yaml

Adopt to the swagger file what is actually implemented in the python version
@valgog @v-stepanov @jkliff @CyberDem0n

Change the swagger to what is actually implemented

---

.travis.yml

<a href='#crh-start'></a><a href='#crh-data-%7B%22approved%22%3A%20%7B%22https%3A//github.com/valgog%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/448014%3Fv%3D3%22%7D%7D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/zalando/nakadi/pull/45%23issuecomment-164790767%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222015-12-15T15%3A03%3A27Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/448014%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/valgog%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%2C%20%22processed%22%3A%20%5B%22https%3A//github.com/zalando/nakadi/pull/45%23issuecommen …

simplified travis file

---

src/main/java/de/zalando/aruha/nakadi/controller/TopicsController.java

<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/zalando/nakadi/pull/47%23issuecomment-166312493%22%2C%20%22https%3A//github.com/zalando/nakadi/pull/47%23issuecomment-166575533%22%2C%20%22https%3A//github.com/zalando/nakadi/pull/47%23issuecomment-166576106%22%2C%20%22https%3A//github.com/zalando/nakadi/pull/47%23discussion_r48148211%22%2C%20%22https%3A//github.com/zalando/nakadi/pull/47%23discussion_r48148241%22%2C%20%22https%3A//github.com/zalando/nakadi/pull/47%23discussion_r48155753%22%2C%20%22https%3A//github.com/zalando/nakadi/pull/47%23discussion_r48160189%22%2C%20%22https%3A//github.com/zalando/nakadi/pull/47%23discussion_r48185911%22%2C%20%22https%3A//github.com/zalando/nakadi/pull/47%23discussion_r48186003%22%5D%2C%20%22comments%22%3A% …

Fix endpoints urls

---

.travis.yml
README.MD
build.gradle
src/acceptance-test/java/de/zalando/aruha/nakadi/webservice/EventStreamReadingAT.java

@jkliff @tmuehl @valgog @CyberDem0n please take a look
<a href='#crh-start'></a><a href='#crh-data-%7B%22approved%22%3A%20%7B%22https%3A//github.com/tmuehl%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6663328%3Fv%3D3%22%7D%7D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/zalando/nakadi/pull/49%23issuecomment-166891753%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222015-12-23T13%3A17%3A24Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6663328%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/tmuehl%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%2C%20%22processed%22%3A%20%5B%22 …

Travis ci for nakadi jvm

---

src/acceptance-test/java/de/zalando/aruha/nakadi/webservice/BaseAT.java
src/acceptance-test/java/de/zalando/aruha/nakadi/webservice/EchoControllerAT.java
src/acceptance-test/java/de/zalando/aruha/nakadi/webservice/EventStreamReadingAT.java
src/acceptance-test/java/de/zalando/aruha/nakadi/webservice/HealthCheckAT.java

The idea was to create integration tests also for LoLA functionality we currently have. But as we think about throwing away LoLA, I would not like to spend time on writing tests for it.
So it's just a health check test and small refactoring.
@valgog @CyberDem0n @tmuehl @jkliff
<a href='#crh-start'></a><a href='#crh-data-%7B%7D'></a>
<a href='https://www.codereviewhub.com/'><img src='http://www.codereviewhub.com/site/github-bar.png' height=40></a>
<a href='https://www.codereviewhub.com/zalando/nakadi/pull/51?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/zalando/nakadi/pull/51'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
<a href='#crh-end'></a>

ARUHA-45 created test for healthcheck endpoint; refactored tests;

---

.travis.yml

First try to transport coverage data to Codacy

Transport of coverage data to Codacy

---

build.gradle
src/acceptance-test/java/de/zalando/aruha/nakadi/repository/kafka/KafkaRepositoryTest.java
src/main/java/de/zalando/aruha/nakadi/config/NakadiConfig.java
src/main/java/de/zalando/aruha/nakadi/repository/KafkaRepositorySettings.java
src/main/java/de/zalando/aruha/nakadi/repository/TopicRepository.java
src/main/java/de/zalando/aruha/nakadi/repository/kafka/KafkaRepository.java
src/main/java/de/zalando/aruha/nakadi/repository/kafka/KafkaRepositorySettings.java
src/main/java/de/zalando/aruha/nakadi/repository/zookeeper/ZooKeeperHolder.java
src/main/resources/application.yml

@jkliff @valgog @rcillo @tmuehl @CyberDem0n 
Please review

Aruha 51 topics creation

---

api/nakadi-event-bus-api.yaml

* Simplified the API by removing the Topic API compleatly
* Made changes to address comments from the code review

Removed Topic API from the specification

---

src/acceptance-test/java/de/zalando/aruha/nakadi/webservice/EventTypeAT.java
src/main/java/de/zalando/aruha/nakadi/controller/EventTypeController.java
src/test/java/de/zalando/aruha/nakadi/controller/EventTypeControllerTest.java

Change underscore to dash.
This is a very simple change. Just opened a PR so you are aware that I changed something in the `nakadi-jvm` branch.

ARUHA-50 fix event type api

---

build.gradle
src/main/java/de/zalando/aruha/nakadi/domain/ConsumedEvent.java
src/main/java/de/zalando/aruha/nakadi/service/EventStream.java
src/main/java/de/zalando/aruha/nakadi/validation/EventValidation.java
src/test/java/de/zalando/aruha/nakadi/utils/TestUtils.java
src/test/java/de/zalando/aruha/nakadi/validation/JSONSchemaValidationTest.java

@v-stepanov @rcillo @jkliff @CyberDem0n @valgog 
Please review

Use Findbugs to detect potential bugs (and fix detected issues)

---

build.gradle
src/main/java/de/zalando/aruha/nakadi/Application.java
src/main/java/de/zalando/aruha/nakadi/FlowIdRequestFilter.java
src/main/java/de/zalando/aruha/nakadi/FlowIdUtils.java
src/main/java/de/zalando/aruha/nakadi/config/WebConfig.java
src/main/resources/log4j.properties

@v-stepanov @CyberDem0n @rcillo @jkliff @valgog Please review

ARUHA-89 Implement Flow-Ids

---

build.gradle
src/main/java/de/zalando/aruha/nakadi/config/NakadiConfig.java
src/main/java/de/zalando/aruha/nakadi/config/WebConfig.java

@v-stepanov @CyberDem0n @rcillo Please review

ARUHA-77 Use real database EventType repository

---

src/main/java/de/zalando/aruha/nakadi/controller/EventTypeController.java
src/main/java/de/zalando/aruha/nakadi/repository/EventTypeRepository.java
src/main/java/de/zalando/aruha/nakadi/repository/db/EventTypeDbRepository.java
src/test/java/de/zalando/aruha/nakadi/controller/EventTypeControllerTest.java

@v-stepanov @CyberDem0n @rcillo Please review

ARUHA-91 Implement "/event-types/<eventType>" entrypoint

---

src/acceptance-test/java/de/zalando/aruha/nakadi/repository/kafka/KafkaRepositoryAT.java
src/acceptance-test/java/de/zalando/aruha/nakadi/webservice/EventStreamReadingAT.java
src/acceptance-test/java/de/zalando/aruha/nakadi/webservice/MetricsAT.java
src/acceptance-test/java/de/zalando/aruha/nakadi/webservice/PartitionsControllerAT.java
src/acceptance-test/java/de/zalando/aruha/nakadi/webservice/utils/JsonTestHelper.java
src/acceptance-test/java/de/zalando/aruha/nakadi/webservice/utils/KafkaTestHelper.java
src/main/java/de/zalando/aruha/nakadi/config/NakadiConfig.java
src/main/java/de/zalando/aruha/nakadi/controller/EventStreamController.java
src/main/java/de/zalando/aruha/nakadi/controller/PartitionsController.java
src/main/java/de/zalando/aruha/nakadi/repository/InMemoryTopicRepository.java
src/main/java/de/zalando/aruha/nakadi/repository/TopicRepository.java
src/main/java/de/zalando/aruha/nakadi/repository/kafka/KafkaRepository.java
src/test/java/de/zalando/aruha/nakadi/controller/EventPublishingControllerTest.java
src/test/java/de/zalando/aruha/nakadi/controller/EventStreamControllerTest.java
src/test/java/de/zalando/aruha/nakadi/controller/PartitionsControllerTest.java
src/test/java/de/zalando/aruha/nakadi/repository/kafka/KafkaRepositoryTest.java
src/test/java/de/zalando/aruha/nakadi/utils/JsonTestHelper.java

@tmuehl @rcillo @CyberDem0n please review

aruha 62 expose kafka info

---

senza.yaml

In addition to that parametrize KMS key identifier in order to create
policy which allows to decrypt values.

Parametrize database connection url and password

---

src/main/java/de/zalando/aruha/nakadi/repository/db/EventTypeDbRepository.java

@CyberDem0n @rcillo @v-stepanov @valgog @jkliff Please review

ARUHA-93 Fix Postgres 9.4 incompatibility

---

src/main/java/de/zalando/aruha/nakadi/controller/EventStreamController.java
src/main/java/de/zalando/aruha/nakadi/controller/EventTypeController.java
src/main/java/de/zalando/aruha/nakadi/controller/PartitionsController.java

@v-stepanov @CyberDem0n @jkliff @rcillo Please review

ARUHA-94 Enhance logging verbosity

---

src/main/java/de/zalando/aruha/nakadi/FlowIdRequestFilter.java

ARUHA-98 Include FlowId in Response Header

---

src/acceptance-test/java/de/zalando/aruha/nakadi/webservice/UserJourneyAT.java
src/test/resources/sample-event-type-update.json
src/test/resources/sample-event-type.json

Acceptance test for M1 please review
@tmuehl @CyberDem0n @rcillo @jkliff

ARUHA-58: added user journey acceptance test for M1

---

senza.yaml

* Limit LB traffic to HTTPS
* Add logrotation

Improve senza config

---

src/acceptance-test/java/de/zalando/aruha/nakadi/repository/db/EventTypeDbRepositoryTest.java
src/acceptance-test/java/de/zalando/aruha/nakadi/webservice/RealEnvironmentAT.java
src/acceptance-test/java/de/zalando/aruha/nakadi/webservice/UserJourneyAT.java

@rcillo @jkliff @CyberDem0n @tmuehl 
Please review
I added possibility to run User Journey Test against real environment and the test was successful for our sandbox stack.

ARUHA-58: added possibility to run against real environment

---

senza.yaml

... to be able to reuse one db for different stacks
@CyberDem0n @rcillo @v-stepanov @jkliff Please review

Make the db user configurable

---

build.gradle
senza.yaml
src/acceptance-test/java/de/zalando/aruha/nakadi/repository/db/EventTypeDbRepositoryTest.java
src/acceptance-test/java/de/zalando/aruha/nakadi/webservice/EventTypeAT.java
src/main/java/de/zalando/aruha/nakadi/config/AuthenticationConfig.java
src/main/java/de/zalando/aruha/nakadi/config/JsonConfig.java
src/main/java/de/zalando/aruha/nakadi/config/NakadiConfig.java
src/main/java/de/zalando/aruha/nakadi/config/RepositoriesConfig.java
src/main/java/de/zalando/aruha/nakadi/config/SecurityConfiguration.java
src/main/java/de/zalando/aruha/nakadi/config/SecuritySettings.java
src/main/java/de/zalando/aruha/nakadi/config/WebConfig.java
src/main/java/de/zalando/aruha/nakadi/repository/db/EventTypeDbRepository.java
src/main/resources/application.yml
src/test/java/de/zalando/aruha/nakadi/controller/EventPublishingControllerTest.java
src/test/java/de/zalando/aruha/nakadi/controller/EventStreamControllerTest.java
src/test/java/de/zalando/aruha/nakadi/controller/EventTypeControllerTest.java
src/test/java/de/zalando/aruha/nakadi/controller/PartitionsControllerTest.java
src/test/java/de/zalando/aruha/nakadi/security/AuthenticationTest.java
src/test/java/de/zalando/aruha/nakadi/security/BasicModeAuthenticationTest.java
src/test/java/de/zalando/aruha/nakadi/security/Endpoint.java
src/test/java/de/zalando/aruha/nakadi/security/EndpointsSecurityTest.java
src/test/java/de/zalando/aruha/nakadi/security/FullModeAuthenticationTest.java
src/test/java/de/zalando/aruha/nakadi/security/OffModeAuthenticationTest.java

@rcillo @tmuehl @jkliff @CyberDem0n Please review

Aruha 56 oauth scopes

---

src/main/java/de/zalando/aruha/nakadi/validation/EventBodyMustRespectSchema.java
src/test/java/de/zalando/aruha/nakadi/validation/JSONSchemaValidationTest.java

When an event has multiple validation errors then we concatenate all of
then in a single message.

aruha-63 improve validation error messages

---

senza.yaml
src/main/java/de/zalando/aruha/nakadi/config/AuthenticationConfig.java
src/main/java/de/zalando/aruha/nakadi/config/SecuritySettings.java
src/main/resources/application.yml

@tmuehl @jkliff @CyberDem0n @rcillo please review

parametrized token info url

---

src/test/java/de/zalando/aruha/nakadi/security/BasicModeAuthenticationTest.java
src/test/java/de/zalando/aruha/nakadi/security/FullModeAuthenticationTest.java
src/test/java/de/zalando/aruha/nakadi/security/OffModeAuthenticationTest.java

@CyberDem0n @rcillo @tmuehl @jkliff 
I had to disable this tests for now as they very often time out on travis.
I will switch them back after I fix that.

temporary disabled oauth tests

---

api/nakadi-event-bus-api.yaml

ARUHA-115 remove root_eid, adjust parent_eids

---

src/acceptance-test/java/de/zalando/aruha/nakadi/repository/db/EventTypeDbRepositoryTest.java
src/acceptance-test/java/de/zalando/aruha/nakadi/webservice/EventTypeAT.java
src/acceptance-test/java/de/zalando/aruha/nakadi/webservice/UserJourneyAT.java
src/main/java/de/zalando/aruha/nakadi/config/JsonConfig.java
src/main/java/de/zalando/aruha/nakadi/domain/EventCategory.java
src/main/java/de/zalando/aruha/nakadi/domain/EventType.java
src/test/java/de/zalando/aruha/nakadi/controller/EventTypeControllerTest.java
src/test/resources/sample-event-type-update.json
src/test/resources/sample-event-type.json

...in the json fields.
And introduced the `EventCategory`.
@v-stepanov @rcillo @jkliff @CyberDem0n @bocytko Please review
Fixes #135

ARUHA-110 Enforce lower case enum constants

---

src/acceptance-test/java/de/zalando/aruha/nakadi/repository/db/EventTypeCacheTest.java
src/main/java/de/zalando/aruha/nakadi/config/NakadiConfig.java
src/main/java/de/zalando/aruha/nakadi/config/RepositoriesConfig.java
src/main/java/de/zalando/aruha/nakadi/controller/EventPublishingController.java
src/main/java/de/zalando/aruha/nakadi/repository/EventTypeRepository.java
src/main/java/de/zalando/aruha/nakadi/repository/db/EventTypeCache.java
src/main/java/de/zalando/aruha/nakadi/repository/db/EventTypeCachedRepository.java
src/main/java/de/zalando/aruha/nakadi/validation/EventTypeValidator.java
src/main/java/de/zalando/aruha/nakadi/validation/EventValidation.java
src/test/java/de/zalando/aruha/nakadi/controller/EventPublishingControllerTest.java

Continues https://github.com/zalando/nakadi/pull/142

Aruha 104 validator cache

---

.travis.yml
src/test/java/de/zalando/aruha/nakadi/security/BasicModeAuthenticationTest.java
src/test/java/de/zalando/aruha/nakadi/security/FullModeAuthenticationTest.java
src/test/java/de/zalando/aruha/nakadi/security/OffModeAuthenticationTest.java

@tmuehl @rcillo @CyberDem0n @jkliff 
Please review
- That should fix blinking tests problem (At least I run it 6 times in a row and that was successful)
- I also enabled back the codacy as it is working fine now.

Aruha 111 fix spring tests on travis

---

src/test/java/de/zalando/aruha/nakadi/security/AuthenticationTest.java
src/test/java/de/zalando/aruha/nakadi/service/EventStreamTest.java

@CyberDem0n @tmuehl @jkliff @rcillo 
Please review
While authentication tests were `@Ignored` they became broken :) 
So this is just a small fix.

ARUHA-111 fixed authentication tests

---

build.gradle
src/main/java/de/zalando/aruha/nakadi/config/NakadiConfig.java

Aruha 120 jvm instrumentation

---

senza.yaml

@CyberDem0n @tmuehl @rcillo @jkliff please review

parametrized replica factor

---

src/main/java/de/zalando/aruha/nakadi/config/NakadiConfig.java
src/main/java/de/zalando/aruha/nakadi/controller/EventPublishingController.java
src/main/java/de/zalando/aruha/nakadi/controller/EventStreamController.java
src/main/java/de/zalando/aruha/nakadi/metrics/MetricUtils.java
src/test/java/de/zalando/aruha/nakadi/controller/EventPublishingControllerTest.java
src/test/java/de/zalando/aruha/nakadi/controller/EventStreamControllerTest.java

Introduced the following metrics per event type:
* Timer for successful publishing (including counter)
* Counter for the number of events failed to publish
* Counter for the current number of consumers

Aruha 120 per eventtype metrics

---

src/main/java/de/zalando/aruha/nakadi/config/AuthenticationConfig.java
src/main/java/de/zalando/aruha/nakadi/metrics/MetricUtils.java

@v-stepanov @rcillo @CyberDem0n @jkliff Please review

Aruha 121 metrics for token validation

---

.travis.yml

That will improve the speed of build on travis as it will run unit and acceptance tests in parallel
@rcillo @jkliff @tmuehl @CyberDem0n please review

Try parallelize build on travis

---

README.md

I removed references to the Python prototype and also added some example API calls to enable quick experiments with Nakadi.

Added examples to readme

---

api/nakadi-event-bus-api.yaml

@rcillo @v-stepanov @jkliff @CyberDem0n Please review

ARUHA-131 smaller suggestions to the api documentation

---

README.md

@rcillo @v-stepanov @jkliff @CyberDem0n @sezera Please review

ARUHA-153 Remove Authorization header for localhost calls

---

senza.yaml

@rcillo @v-stepanov @CyberDem0n @jkliff Please review and say yes! :)

ARUHA-155 Scale aws instances more pessimistic

---

src/main/java/de/zalando/aruha/nakadi/controller/EventStreamController.java
src/main/java/de/zalando/aruha/nakadi/repository/EventConsumer.java
src/main/java/de/zalando/aruha/nakadi/repository/kafka/NakadiKafkaConsumer.java
src/test/java/de/zalando/aruha/nakadi/repository/kafka/NakadiKafkaConsumerTest.java

@tmuehl @rcillo @jkliff @CyberDem0n @antban 
just a small bugfix (kafka consumer was not closed properly), please review

ARUHA-160 Added closing of kafka consumer when stream is closed

---

api/nakadi-event-bus-api.yaml
src/main/java/de/zalando/aruha/nakadi/controller/EventTypeController.java
src/main/java/de/zalando/aruha/nakadi/domain/EventType.java
src/main/java/de/zalando/aruha/nakadi/validation/EventValidation.java
src/test/java/de/zalando/aruha/nakadi/controller/EventTypeControllerTest.java
src/test/java/de/zalando/aruha/nakadi/validation/JSONSchemaValidationTest.java

@v-stepanov @rcillo @jkliff @CyberDem0n @antban please review
This one is to be merged into the release-branch and nakadi-jvm.

Aruha 161 make schema required

---

src/main/java/de/zalando/aruha/nakadi/domain/BatchItem.java
src/main/java/de/zalando/aruha/nakadi/repository/kafka/KafkaTopicRepository.java
src/main/java/de/zalando/aruha/nakadi/service/EventPublisher.java
src/test/java/de/zalando/aruha/nakadi/repository/kafka/KafkaTopicRepositoryTest.java

Same as #208 but pointing to the right branch now. We decided not to include this fix in the previous release since it's not critical.

Aruha 112 timeout message

---

README.md

Updated example requests

---

Dockerfile
senza.yaml

@rcillo @antban please review
That will give the possibility to set Xmx/Xms (and other jvm params) when deploying nakadi

ARUHA-172: Made java opts configurable through senza file and dockerfile

---

src/acceptance-test/java/de/zalando/aruha/nakadi/webservice/PartitionsControllerAT.java

Dmitriy found out that this test can fail. I believe it fails if it runs as the very first one after the kafka topic was created. This is a fix.
@antban @rcillo @jkliff please review

fix for test that was failing sometimes

---

api/nakadi-event-bus-api.yaml

1. proper specify format for eid as uuid
2. proper specify format for X-nakadi-cursor header
3. correct status code for event type creation

aruha-186 API doc improvements

---

src/main/resources/application.yml

ARUHA-192: enabled auth logging; enabled nakadi debug logging;

---

senza.yaml
src/main/java/de/zalando/aruha/nakadi/controller/EventStreamController.java

And use tcp elb listener, instead of http elb (http elb does not inform about client connection close)

ARUHA-193 Do not use ELB connection caching on streaming responses

---

api/nakadi-event-bus-api.yaml

@antban @rcillo @jkliff 
Please take a look. The endpoints for committing/exposing offsets of subscription.
We didn't really discuss it yet, so this is more like a PR to start a discussion about that.

ARUHA-190: added endpoints to commit/expose offsets

---

src/main/java/de/zalando/aruha/nakadi/metrics/EventTypeMetrics.java

ARUHA-197: changed response code counters to meters

---

README.md

rendered copy here: https://github.com/dehora/nakadi/blob/dehora/226-1/README.md#nakadi-event-broker

Provide a project overview in the README

---

build.gradle
database/nakadi/10_data/04_tables/02_subscription.sql
src/acceptance-test/java/de/zalando/aruha/nakadi/repository/db/AbstractDbRepositoryTest.java
src/acceptance-test/java/de/zalando/aruha/nakadi/repository/db/EventTypeDbRepositoryTest.java
src/acceptance-test/java/de/zalando/aruha/nakadi/repository/db/SubscriptionDbRepositoryTest.java
src/main/java/de/zalando/aruha/nakadi/config/JsonConfig.java
src/main/java/de/zalando/aruha/nakadi/domain/Subscription.java
src/main/java/de/zalando/aruha/nakadi/exceptions/DuplicatedSubscriptionException.java
src/main/java/de/zalando/aruha/nakadi/exceptions/NoSuchSubscriptionException.java
src/main/java/de/zalando/aruha/nakadi/repository/db/AbstractDbRepository.java
src/main/java/de/zalando/aruha/nakadi/repository/db/EventTypeDbRepository.java
src/main/java/de/zalando/aruha/nakadi/repository/db/SubscriptionDbRepository.java

Aruha 202 subscription persistence

---

Dockerfile

This update contains security fixes.
Fixes #252

aruha-212 update docker base image

---

build.gradle
src/main/java/de/zalando/aruha/nakadi/config/NakadiConfig.java
src/main/java/de/zalando/aruha/nakadi/config/RepositoriesConfig.java
src/main/java/de/zalando/aruha/nakadi/util/FeatureToggleService.java
src/main/resources/application.yml
src/test/java/de/zalando/aruha/nakadi/util/FeatureToggleServiceTest.java

@rcillo @antban @jkliff 
Please review

Aruha 233 feature toggle

---

api/nakadi-event-bus-api.yaml

A collection of tweaks and edits to the API definition mostly to optimise for reading in the documentation or via the Swagger UI.

ARUHA-240: Edits to API definition

---

src/acceptance-test/java/de/zalando/aruha/nakadi/webservice/CompressedEventPublishingAT.java
src/main/java/de/zalando/aruha/nakadi/config/WebConfig.java
src/main/java/de/zalando/aruha/nakadi/util/GzipBodyRequestFilter.java

@tmuehl @rcillo @antban @jkliff Please review

Aruha 237 uncompress request body

---

src/main/java/de/zalando/aruha/nakadi/controller/SubscriptionController.java
src/test/java/de/zalando/aruha/nakadi/controller/SubscriptionControllerTest.java

ARUHA-230: fixed status code; fixed appropriate test;

---

api/nakadi-event-bus-api.yaml

Fix https://github.com/zalando/nakadi/pull/290/files#r67856122

aruha-257 fix accidentally removed endpoint definition

---

src/main/java/de/zalando/aruha/nakadi/service/CursorsCommitService.java
src/test/java/de/zalando/aruha/nakadi/service/CursorsCommitServiceTest.java

@antban @rcillo @jkliff please review.

Aruha 238 fix short circuit bug

---

src/acceptance-test/java/de/zalando/aruha/nakadi/webservice/hila/HilaAT.java
src/acceptance-test/java/de/zalando/aruha/nakadi/webservice/hila/StreamBatch.java
src/acceptance-test/java/de/zalando/aruha/nakadi/webservice/utils/NakadiTestUtils.java
src/acceptance-test/java/de/zalando/aruha/nakadi/webservice/utils/TestStreamingClient.java
src/main/java/de/zalando/aruha/nakadi/service/subscription/KafkaClient.java
src/main/java/de/zalando/aruha/nakadi/service/subscription/state/PartitionData.java
src/main/java/de/zalando/aruha/nakadi/service/subscription/state/StreamingState.java
src/test/java/de/zalando/aruha/nakadi/utils/TestUtils.java

@antban @rcillo @jkliff 
Please review. 
This fixes double-event bug; problem with empty batch sent at the end; problem with being not possible to commit very first event; + some acceptance tests

@Aruha 259 hila event delivered twice

---

src/main/java/de/zalando/aruha/nakadi/service/subscription/state/StreamingState.java

ARUHA-272: fixed bug with window not sliding

---

src/acceptance-test/java/de/zalando/aruha/nakadi/webservice/hila/HilaAT.java
src/acceptance-test/java/de/zalando/aruha/nakadi/webservice/hila/HilaRebalanceAT.java
src/acceptance-test/java/de/zalando/aruha/nakadi/webservice/hila/StreamBatch.java
src/acceptance-test/java/de/zalando/aruha/nakadi/webservice/utils/NakadiTestUtils.java
src/test/java/de/zalando/aruha/nakadi/utils/TestUtils.java

@antban @adyach @rcillo please review
do you know any other interesting use-cases to test here?

Aruha 267 hila acceptance tests

---

requirements.txt

ARUHA-275 removed unused python file

---

.travis.yml

jpm4j works again, I switched on codacy back
@adyach @v1ctor @antban @rcillo please review

ARUHA-283: switched on codacy back

---

src/acceptance-test/java/de/zalando/aruha/nakadi/webservice/hila/HilaAT.java
src/main/java/de/zalando/aruha/nakadi/service/subscription/ExactWeightRebalancer.java
src/main/java/de/zalando/aruha/nakadi/service/subscription/StreamParameters.java
src/main/java/de/zalando/aruha/nakadi/service/subscription/StreamingContext.java
src/main/java/de/zalando/aruha/nakadi/service/subscription/model/Partition.java
src/main/java/de/zalando/aruha/nakadi/service/subscription/model/Session.java
src/main/java/de/zalando/aruha/nakadi/service/subscription/state/CleanupState.java
src/main/java/de/zalando/aruha/nakadi/service/subscription/state/ClosingState.java
src/main/java/de/zalando/aruha/nakadi/service/subscription/state/PartitionData.java
src/main/java/de/zalando/aruha/nakadi/service/subscription/state/StreamingState.java
src/main/java/de/zalando/aruha/nakadi/service/subscription/zk/CuratorZkSubscriptionClient.java
src/test/java/de/zalando/aruha/nakadi/service/subscription/ExactWeightRebalancerTest.java

Improved null handling
@antban @v1ctor @adyach @rcillo please review

Aruha 266 null handling strategy

---

api/nakadi-event-bus-api.yaml
src/main/java/de/zalando/aruha/nakadi/domain/BatchFactory.java
src/main/java/de/zalando/aruha/nakadi/enrichment/Enrichment.java
src/main/java/de/zalando/aruha/nakadi/enrichment/EnrichmentStrategy.java
src/main/java/de/zalando/aruha/nakadi/enrichment/MetadataEnrichmentStrategy.java
src/main/java/de/zalando/aruha/nakadi/repository/db/EventTypeCache.java
src/main/java/de/zalando/aruha/nakadi/service/EventPublisher.java
src/test/java/de/zalando/aruha/nakadi/enrichment/EnrichmentTest.java
src/test/java/de/zalando/aruha/nakadi/enrichment/MetadataEnrichmentStrategyTest.java
src/test/java/de/zalando/aruha/nakadi/service/EventPublisherTest.java
src/test/java/de/zalando/aruha/nakadi/utils/TestUtils.java

Added partition parameter for metadata + fixed tests
@v-stepanov @v1ctor @antban @rcillo

ARUHA-225: Include the partition the event was written to in metadata

---

database/migration/R2016_07_12/aruha-253-fix-default-statistics.sql

aruha-253 version migration to fix default statistics

---

api/nakadi-event-bus-api.yaml

latest stuff for High Level API
@jkliff @rcillo @antban @adyach @v1ctor please review
After this PR I will make a global PR for the whole HILA and after that we will go to API guild

Aruha 190 hila api latest

---

api/nakadi-event-bus-api.yaml
src/main/resources/application.yml

ARUHA-141: fixed max retention time + api

---

MAINTAINERS
src/main/resources/application.yml

ARUHA-303: Add maintainers file

---

src/acceptance-test/java/org/zalando/nakadi/webservice/SubscriptionAT.java
src/main/java/org/zalando/nakadi/controller/SubscriptionController.java
src/test/java/org/zalando/nakadi/controller/SubscriptionControllerTest.java

@adyach @v1ctor @antban @rcillo please review

Aruha 309 get subscription

---

build.gradle

@antban @v1ctor @rcillo @adyach please review

ARUHA-310: removed extra logging of ATs

---

src/main/java/org/zalando/nakadi/config/SecurityConfiguration.java
src/test/java/org/zalando/nakadi/security/AuthenticationTest.java

@adyach @v1ctor @rcillo @antban please review

ARUHA-314: secured new endpoints with scopes

---

api/nakadi-event-bus-api.yaml

@rcillo @v1ctor @adyach @antban please review

ARUHA-335: small API adjustments

---

src/main/java/org/zalando/nakadi/domain/BatchItem.java
src/main/java/org/zalando/nakadi/repository/kafka/KafkaTopicRepository.java
src/test/java/org/zalando/nakadi/repository/kafka/KafkaTopicRepositoryTest.java

@rcillo @antban @adyach @v1ctor please review

Aruha 357 fix response code when failed

---

src/main/java/org/zalando/nakadi/exceptions/InvalidStreamIdException.java
src/main/java/org/zalando/nakadi/service/CursorsService.java
src/main/java/org/zalando/nakadi/service/subscription/zk/ZkSubscriptionNode.java
src/test/java/org/zalando/nakadi/controller/SubscriptionControllerTest.java
src/test/java/org/zalando/nakadi/service/CursorsServiceTest.java

https://github.com/zalando/nakadi/pull/412

ARUHA-344: validate sessions

---

src/main/resources/log4j.properties

Our previous log format used to look like this:
```
Sep 15 15:34:51 ip-10-246-4-222 docker/f27592b3a708[817]: [2016-09-15 15:34:51.528] MIVVr0eASeby3Pl5vrtFKvQ3 boot - 6 DEBUG [http-nio-8080-exec-52] --- org.springframework.security.web.access.intercept.FilterSecurityInterceptor: RunAsManager did not change Authentication object
```
It has some problems:
1. the date time misses timezone.
2. %x NDC (flow-id) is not properly delimited. It prints "null" sometimes.
3. what does "boot" mean?
4. %X{context} prints nothing.
5. PID is not used because there is always a single process inside docker image.
6. log level comes after a variable number of patterns (if MDC %X is or is not printed, for example)
7. finally the message. Can be multiline.
We changed it so that an example would look like: …

aruha-351 modify log format

---

api/nakadi-event-bus-api.yaml
src/acceptance-test/java/org/zalando/nakadi/webservice/SubscriptionAT.java
src/acceptance-test/java/org/zalando/nakadi/webservice/utils/NakadiTestUtils.java
src/main/java/org/zalando/nakadi/controller/CursorsController.java
src/main/java/org/zalando/nakadi/domain/Cursor.java
src/main/java/org/zalando/nakadi/domain/ItemsWrapper.java
src/main/java/org/zalando/nakadi/domain/SubscriptionCursor.java
src/test/java/org/zalando/nakadi/controller/CursorsControllerTest.java

@adyach @v1ctor @rcillo @antban 
please review

Aruha 370 fix commit endpoint and api

---

src/acceptance-test/java/org/zalando/nakadi/webservice/SubscriptionAT.java
src/main/java/org/zalando/nakadi/service/EventTypeService.java
src/main/java/org/zalando/nakadi/service/Result.java
src/test/java/org/zalando/nakadi/controller/EventTypeControllerTest.java

@v1ctor @adyach @rcillo @antban please review

Aruha 374 restrict eventtype deletion

---

api/nakadi-event-bus-api.yaml
src/acceptance-test/java/org/zalando/nakadi/webservice/SubscriptionAT.java
src/acceptance-test/java/org/zalando/nakadi/webservice/UserJourneyAT.java
src/main/java/org/zalando/nakadi/controller/SubscriptionController.java
src/main/java/org/zalando/nakadi/service/WebResult.java
src/test/java/org/zalando/nakadi/controller/SubscriptionControllerTest.java

@v1ctor @rcillo @adyach @antban please review

ARUHA-373: changed deletion status code to 204

---

api/nakadi-event-bus-api.yaml
src/main/java/org/zalando/nakadi/domain/SubscriptionEventTypeStats.java

ARUHA-389: changed client_id to stream_id

---

src/acceptance-test/java/org/zalando/nakadi/webservice/hila/HilaAT.java
src/main/java/org/zalando/nakadi/service/CursorsService.java

@antban @v1ctor @rcillo @adyach please review

ARUHA-390: changed -1 to BEGIN

---

README.md

Minor fixes to the Subscription API related documentation

Minor fixes to README file

---

README.md

Update subscription details in the readme.

---

api/nakadi-event-bus-api.yaml

- add oauth2 to _registry/validation-strategies_
- add oauth2 to _registry/enrichment-strategies_
- add oauth2 to _registry/partition-strategies_

Add missing OAuth2 to registry

---

.travis.yml

Do some more cache and installation improvements

Some more improvements in travis-ci configuration

---

api/nakadi-event-bus-api.yaml

Added oauth2 information to `/event-types` and `/event-types/{name}`

Add OAuth2 to event-types

---

.travis.yml

Do some improvements in gradle usage

ARUHA-411 Improve gradle support in travis-ci

---

api/nakadi-event-bus-api.yaml

I would like to send this api to guild but first it will be nice to have an agreement within the team. So you are welcome to comment.

aruha-355: changed api according to guidlines and task validation

---

src/main/java/org/zalando/nakadi/validation/schema/FixedSchemaChangeConstraint.java
src/test/java/org/zalando/nakadi/validation/schema/FixedSchemaChangeConstraintTest.java

When upgrading a schema it's required to change the schema at the same time.

Fix schema upgrade

---

api/nakadi-event-bus-api.yaml
build.gradle
src/acceptance-test/java/org/zalando/nakadi/webservice/ConsumerLimitingCleaningServiceAT.java
src/acceptance-test/java/org/zalando/nakadi/webservice/ConsumerLimitingServiceAT.java
src/acceptance-test/java/org/zalando/nakadi/webservice/EventStreamReadingAT.java
src/main/java/org/zalando/nakadi/controller/EventStreamController.java
src/main/java/org/zalando/nakadi/exceptions/ConnectionSlotOccupiedException.java
src/main/java/org/zalando/nakadi/exceptions/NoConnectionSlotsException.java
src/main/java/org/zalando/nakadi/service/ConnectionSlot.java
src/main/java/org/zalando/nakadi/service/ConsumerLimitingCleanService.java
src/main/java/org/zalando/nakadi/service/ConsumerLimitingCleaningService.java
src/main/java/org/zalando/nakadi/service/ConsumerLimitingService.java
src/main/java/org/zalando/nakadi/util/FeatureToggleService.java
src/main/resources/application.yml
src/test/java/org/zalando/nakadi/controller/EventStreamControllerTest.java

@antban @rcillo @adyach @v1ctor @sergkam please review
(It was not yet tested properly, i will create a separate stack and will test it there, so if you notice some bug in the code - let me know :)
I have no idea how this small feature could grow to 700 lines on code :(
Concept document moved to wiki: https://github.com/zalando/nakadi/wiki/Too-much-consumers-from-a-single-application

Aruha 456 block consumers

---

src/acceptance-test/java/org/zalando/nakadi/webservice/BlockEventPublishingAT.java
src/acceptance-test/java/org/zalando/nakadi/webservice/hila/HilaAT.java
src/main/java/org/zalando/nakadi/config/ValidatorConfig.java
src/main/java/org/zalando/nakadi/validation/schema/CategoryChangeConstraint.java
src/test/java/org/zalando/nakadi/validation/schema/CategoryChangeConstraintTest.java

Category changes should not be allowed since it completely changes the
validation rules.

aruha-400 block category changes

---

src/main/java/org/zalando/nakadi/service/ConsumerLimitingService.java

@lmontrieux @adyach @rcillo @antban please review.
Here I fixed error message and added logging.

ARUHA-456: fixed error message for client; added logging;

---

checkstyle.xml
src/acceptance-test/java/org/zalando/nakadi/domain/StreamMetadata.java
src/acceptance-test/java/org/zalando/nakadi/webservice/hila/HilaAT.java
src/acceptance-test/java/org/zalando/nakadi/webservice/hila/StreamBatch.java
src/main/java/org/zalando/nakadi/domain/Cursor.java
src/main/java/org/zalando/nakadi/domain/EventTypeSchema.java
src/main/java/org/zalando/nakadi/domain/EventTypeStatistics.java
src/main/java/org/zalando/nakadi/domain/Subscription.java
src/main/java/org/zalando/nakadi/domain/SubscriptionBase.java
src/main/java/org/zalando/nakadi/domain/SubscriptionCursor.java
src/main/java/org/zalando/nakadi/domain/Topic.java
src/main/java/org/zalando/nakadi/repository/kafka/KafkaCursor.java
src/main/java/org/zalando/nakadi/repository/kafka/KafkaPartitionsCalculator.java
src/main/java/org/zalando/nakadi/service/ClosedConnectionsCrutch.java
src/main/java/org/zalando/nakadi/service/ConnectionSlot.java
src/main/java/org/zalando/nakadi/service/EventStreamConfig.java
src/main/java/org/zalando/nakadi/service/subscription/model/Partition.java
src/main/java/org/zalando/nakadi/service/subscription/model/Session.java
src/main/java/org/zalando/nakadi/util/FlowIdUtils.java

@lmontrieux @antban @rcillo @adyach please review

ARUHA-517: made braces required by checkstyle

---

src/main/java/org/zalando/nakadi/controller/EventStreamController.java
src/main/java/org/zalando/nakadi/repository/zookeeper/ZkChildrenCache.java
src/main/java/org/zalando/nakadi/service/ConsumerLimitingService.java

@adyach @antban @rcillo @lmontrieux please review

ARUHA-512: fixed consumers limiting bug

---

database/migration/2016_12_20/timeline_db.sql
database/migration/aruha-522-timelines.sql
database/nakadi/10_data/04_tables/04_storage.sql
database/nakadi/10_data/04_tables/05_timeline.sql
src/acceptance-test/java/org/zalando/nakadi/repository/db/AbstractDbRepositoryTest.java
src/acceptance-test/java/org/zalando/nakadi/repository/db/EventTypeDbRepositoryTest.java
src/acceptance-test/java/org/zalando/nakadi/repository/db/StorageDbRepositoryTest.java
src/acceptance-test/java/org/zalando/nakadi/repository/db/TimelineDbRepositoryTest.java
src/main/java/org/zalando/nakadi/domain/Storage.java
src/main/java/org/zalando/nakadi/domain/Timeline.java
src/main/java/org/zalando/nakadi/repository/db/AbstractDbRepository.java
src/main/java/org/zalando/nakadi/repository/db/EventTypeDbRepository.java
src/main/java/org/zalando/nakadi/repository/db/StorageDbRepository.java
src/main/java/org/zalando/nakadi/repository/db/SubscriptionDbRepository.java
src/main/java/org/zalando/nakadi/repository/db/TimelineDbRepository.java

Covered things: 
- Migration scripts
- CRD Storage
- CRUD Timeline

ARUHA-522 Prepare database for timelines

---

src/acceptance-test/java/org/zalando/nakadi/repository/kafka/KafkaRepositoryAT.java
src/main/java/org/zalando/nakadi/repository/kafka/KafkaLocationManager.java
src/main/java/org/zalando/nakadi/repository/kafka/KafkaSettings.java
src/main/resources/application.yml

This PR sets enable.auto.commit to false

ARUHA-633 Disable consumer offset auto commit

---

src/main/java/org/zalando/nakadi/filters/LoggingFilter.java

Sorry for this random PR, I just was browsing the logs and realized that there are no query params logged. And I also did what I always wanted: I added "statusCode" prefix to make searching for specific status code easier.

ARUHA-646: added query params to logging;

---

.zappr.yaml

https://techjira.zalando.net/browse/ARUHA-655

ARUHA-655: add zappr for compliance

---

README.md

aruha-674: fixed code coverage branch

aruha-674: fixed code coverage branch

---

api/nakadi-event-bus-api.yaml
docker-compose.yml
src/acceptance-test/java/org/zalando/nakadi/repository/kafka/KafkaRepositoryAT.java
src/acceptance-test/java/org/zalando/nakadi/webservice/hila/HilaAT.java
src/acceptance-test/java/org/zalando/nakadi/webservice/hila/SubscriptionAT.java
src/acceptance-test/java/org/zalando/nakadi/webservice/hila/SubscriptionLoadAT.java
src/acceptance-test/java/org/zalando/nakadi/webservice/utils/NakadiTestUtils.java
src/acceptance-test/java/org/zalando/nakadi/webservice/utils/TestStreamingClient.java
src/main/java/org/zalando/nakadi/config/NakadiSettings.java
src/main/java/org/zalando/nakadi/domain/SubscriptionBase.java
src/main/java/org/zalando/nakadi/domain/SubscriptionEventTypeStats.java
src/main/java/org/zalando/nakadi/service/subscription/SubscriptionService.java
src/main/resources/application.yml
src/test/java/org/zalando/nakadi/controller/EventTypeControllerTest.java
src/test/java/org/zalando/nakadi/controller/SubscriptionControllerTest.java
src/test/java/org/zalando/nakadi/service/EventPublisherTest.java

ARUHA-588 Support multiple event types streaming in subscription api

---

src/acceptance-test/java/org/zalando/nakadi/webservice/BaseAT.java
src/acceptance-test/java/org/zalando/nakadi/webservice/TimelinesControllerAT.java
src/test/java/org/zalando/nakadi/controller/StoragesControllerTest.java
src/test/java/org/zalando/nakadi/controller/TimelinesControllerTest.java
src/test/java/org/zalando/nakadi/repository/TopicRepositoryHolderTest.java
src/test/java/org/zalando/nakadi/service/timeline/TimelineServiceTest.java

Added tests for controller and service

ARUHA-527: tests for timelines CRUD

---

src/main/java/org/zalando/nakadi/domain/Version.java
src/test/java/org/zalando/nakadi/domain/VersionTest.java

issue-585 fix major version bump

---

src/acceptance-test/java/org/zalando/nakadi/webservice/utils/TestStreamingClient.java

This PR bring fix for failing from time to time test, the problem was in the implementation of the streaming client, which was hanging while closing the stream, but the connection was closed from Nakadi side and commit timeout expired thus it was not possible to commit cursors.

aruha-694: HIlaAT.whenStreamTimeoutReachedPossibleToCommit fix

---

src/main/java/org/zalando/nakadi/validation/schema/diff/StringSchemaDiff.java
src/test/resources/org/zalando/nakadi/validation/invalid-schema-evolution-examples.json

issue-596 fix pattern comparison

---

.zappr.yaml

https://techjira.zalando.net/browse/ARUHA-655?focusedCommentId=1730631&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-1730631

aruha-655 require 2 approvals

---

.travis.yml

ARUHA-737 get rid of jpm in travis build

---

src/main/java/org/zalando/nakadi/service/EventTypeService.java
src/test/java/org/zalando/nakadi/controller/EventTypeControllerTest.java

issue-614: process duplicated event type exception

---

src/main/java/org/zalando/nakadi/service/timeline/TimelineSyncImpl.java

ARUHA-715 In case when nakadi looses connection to zk, ephemeral nodes are deleted. In this case there will be notification in timeline api `versionChanged`, but all ephemeral nodes could be deleted at that moment. In order to fix it, TimelineSyncImpl will try to recreate node while writing new information in zk.

ARUHA-715 Recreate version node if is was deleted because of found.

---

src/acceptance-test/java/org/zalando/nakadi/repository/kafka/KafkaRepositoryAT.java
src/acceptance-test/java/org/zalando/nakadi/repository/kafka/KafkaTestHelper.java
src/acceptance-test/java/org/zalando/nakadi/webservice/EventTypeAT.java
src/acceptance-test/java/org/zalando/nakadi/webservice/TimelinesControllerAT.java
src/acceptance-test/java/org/zalando/nakadi/webservice/utils/NakadiTestUtils.java
src/main/java/org/zalando/nakadi/controller/EventTypeController.java
src/main/java/org/zalando/nakadi/exceptions/runtime/TopicConfigException.java
src/main/java/org/zalando/nakadi/repository/TopicRepository.java
src/main/java/org/zalando/nakadi/repository/kafka/KafkaTopicRepository.java
src/main/java/org/zalando/nakadi/service/EventTypeService.java
src/test/java/org/zalando/nakadi/controller/EventTypeControllerTest.java

aruha-386: Event type retention time not reflected in Kafka

---

src/acceptance-test/java/org/zalando/nakadi/webservice/EventTypeAT.java

aruha-748: fixed nondeterministic test

aruha-748: fixed nondeterministic test

---

src/main/java/org/zalando/nakadi/service/subscription/state/StreamingState.java

ARUHA-762 Do not move border time for partitions that are in releasing state

---

src/acceptance-test/java/org/zalando/nakadi/webservice/EventStreamReadingAT.java
src/main/java/org/zalando/nakadi/service/CursorsService.java

https://techjira.zalando.net/browse/ARUHA-777

aruha-777: check cursors are not empty

---

api/nakadi-event-bus-api.yaml
src/main/java/org/zalando/nakadi/controller/SubscriptionStreamController.java
src/main/java/org/zalando/nakadi/service/EventStreamConfig.java
src/main/java/org/zalando/nakadi/service/subscription/StreamParameters.java
src/test/java/org/zalando/nakadi/controller/EventStreamControllerTest.java
src/test/java/org/zalando/nakadi/controller/SubscriptionStreamControllerTest.java
src/test/java/org/zalando/nakadi/service/subscription/state/StreamingStateTest.java

https://techjira.zalando.net/browse/ARUHA-758

ARUHA-758: batch_limit=0 is not allowed anymore

---

.zappr.yaml

This project is currently non compliant, even though we followed all the
instructions on how to properly setup zappr.
I have been instructed by the team responsible that I should remove
everything else but the 2 necessary lines with X-Zalando-Team and
X-Zalando-Type.

aruha-747 fix zappr violations

---

.zappr.yaml

Still trying to hammer zappr to work.

aruha-747 tyring to fix zappr again with something else

---

.zappr.yaml

https://techjira.zalando.net/browse/ARUHA-747
The linter likes it this way.

aruha-747 zappr generated by compliance team

---

README.md
src/main/java/org/zalando/nakadi/validation/SchemaEvolutionService.java
src/main/java/org/zalando/nakadi/validation/schema/diff/CombinedSchemaDiff.java
src/test/java/org/zalando/nakadi/validation/SchemaEvolutionServiceTest.java
src/test/resources/org/zalando/nakadi/validation/invalid-schema-evolution-examples.json

This PR is a different approach to https://github.com/zalando/nakadi/pull/630
Instead of blocking all not semantical changes (changes to schema that have no impact to validation), we are going to accept them and bump patch version.

Aruha 677 versioning dummy changes

---

database/migration/aruha-771-subscription-hash.sql

https://techjira.zalando.net/browse/ARUHA-771

ARUHA-771: updated migration script

---

src/acceptance-test/java/org/zalando/nakadi/webservice/UserJourneyAT.java

https://techjira.zalando.net/browse/ARUHA-806

ARUHA-806: Fixed User Journey test

---

src/main/java/org/zalando/nakadi/controller/EventPublishingController.java

https://techjira.zalando.net/browse/ARUHA-792

Aruha 792 log slos

---

src/main/java/org/zalando/nakadi/controller/EventTypeController.java
src/main/java/org/zalando/nakadi/service/EventTypeService.java
src/main/java/org/zalando/nakadi/validation/EventTypeOptionsValidator.java
src/test/java/org/zalando/nakadi/controller/EventTypeControllerTest.java
src/test/java/org/zalando/nakadi/utils/EventTypeTestBuilder.java

aruha-786: retention time fixes

---

src/main/java/org/zalando/nakadi/service/subscription/state/StreamingState.java

when stream switches from state where everything was committed to state with something is uncommitted.

ARUHA-802 Update lastCommitTime for subscription

---

src/main/java/org/zalando/nakadi/config/SecurityConfiguration.java
src/test/java/org/zalando/nakadi/security/AuthenticationTest.java

https://techjira.zalando.net/browse/ARUHA-583

ARUHA-583: fixed endpoint security config

---

src/main/java/org/zalando/nakadi/service/CursorsService.java
src/main/java/org/zalando/nakadi/service/subscription/SubscriptionService.java
src/main/java/org/zalando/nakadi/service/subscription/state/StreamingState.java
src/main/java/org/zalando/nakadi/service/subscription/zk/AbstractZkSubscriptionClient.java
src/main/java/org/zalando/nakadi/service/subscription/zk/NewZkSubscriptionClient.java
src/main/java/org/zalando/nakadi/service/subscription/zk/OldSubscriptionFormatException.java
src/main/java/org/zalando/nakadi/service/subscription/zk/OldZkSubscriptionClient.java
src/main/java/org/zalando/nakadi/service/subscription/zk/ZkSubscriptionClient.java
src/main/java/org/zalando/nakadi/view/SubscriptionCursorWithoutToken.java

ARUHA-834
There were several bugs found: 
1. Incorrect log record
2. Incorrect SubscriptionCursorWithoutToken representation (additional field added)
3. /stats and /cursors endpoint for subscription is not migrating to new format

ARUHA-834 Fix bugs related to ARUHA-753

---

api/nakadi-event-bus-api.yaml

[ARUHA-836](https://techjira.zalando.net/browse/ARUHA-836) fix typos

ARUHA-836 Fix typos in swagger file

---

src/main/java/org/zalando/nakadi/service/subscription/StreamingContext.java
src/main/java/org/zalando/nakadi/service/subscription/state/ClosingState.java

ARUHA-850 Be able to terminate state machine in case of exceptions in onExit calls

---

docs/Timelines.md

The process of creating a Timeline involves coordination of all Nakadi
instances using many different concurrent programming techniques:
barriers, locks and async notifications.
It's a non trivial process and for that reason we wrote how it works in
English. We believe that it might help new developers to understand how
it works and also help with knowledge sharing.
It focuses mostly on the structures used and not the actual code, which
developer should be able to read without any problem.

Document timeline creation process

---

api/nakadi-event-bus-api.yaml
src/main/java/org/zalando/nakadi/domain/SubscriptionBase.java
src/test/java/org/zalando/nakadi/controller/PostSubscriptionControllerTest.java

https://techjira.zalando.net/browse/ARUHA-838

ARUHA-838: Added validation of empty consumer group

---

src/main/java/org/zalando/nakadi/controller/EventPublishingController.java
src/main/java/org/zalando/nakadi/validation/RFC3339DateTimeValidator.java
src/test/java/org/zalando/nakadi/validation/RFC3339DateTimeValidatorTest.java

ARUHA-817 Validate occured_at in a more accurate way

---

src/acceptance-test/java/org/zalando/nakadi/webservice/EventTypeAT.java
src/main/java/org/zalando/nakadi/domain/EventTypeAuthorization.java
src/main/java/org/zalando/nakadi/domain/EventTypeAuthorizationAttribute.java
src/main/java/org/zalando/nakadi/domain/EventTypeBase.java
src/main/java/org/zalando/nakadi/service/AuthorizationValidator.java
src/main/java/org/zalando/nakadi/service/EventTypeService.java
src/test/java/org/zalando/nakadi/controller/EventTypeControllerTest.java
src/test/java/org/zalando/nakadi/service/AuthorizationValidatorTest.java
src/test/java/org/zalando/nakadi/service/EventTypeServiceTest.java

https://techjira.zalando.net/browse/ARUHA-765

Aruha 765 et creation auth

---

src/main/java/org/zalando/nakadi/partitioning/HashPartitionStrategy.java
src/main/java/org/zalando/nakadi/partitioning/HashPartitionStrategyCrutch.java
src/main/java/org/zalando/nakadi/partitioning/PartitionResolver.java
src/main/java/org/zalando/nakadi/partitioning/StringHash.java
src/main/resources/application.yml
src/test/java/org/zalando/nakadi/partitioning/HashPartitionStrategyCrutchTest.java
src/test/java/org/zalando/nakadi/partitioning/HashPartitionStrategyTest.java
src/test/java/org/zalando/nakadi/partitioning/PartitionResolverTest.java
src/test/java/org/zalando/nakadi/partitioning/StringHashTest.java

https://techjira.zalando.net/browse/ARUHA-854

Aruha 854 hash partitioning problem

---

CONDUCT.md

Add conduct.md for opensource compliance

---

src/main/java/org/zalando/nakadi/controller/EventTypeController.java
src/main/java/org/zalando/nakadi/service/AuthorizationValidator.java
src/main/java/org/zalando/nakadi/service/EventTypeService.java
src/test/java/org/zalando/nakadi/controller/EventTypeAuthorizationTest.java

aruha-932: check admin permission when delete et

---

api/nakadi-event-bus-api.yaml

ARUHA-756 fix typos in description

ARUHA-756 Fix Typos

---

github/PULL_REQUEST_TEMPLATE.md

In order to remind developers about the minimum requirements for a pull
request, we are adding a template.
In case your PR does not require deployment notes, for example, just remove it. It would at least mean that you made a conscious decision not to include this data other than forgot about it.

Template for Pull Request

---

src/main/java/org/zalando/nakadi/controller/CursorsController.java
src/main/java/org/zalando/nakadi/exceptions/InvalidStreamIdException.java
src/main/java/org/zalando/nakadi/service/CursorsService.java

And refactor InvalidStreamException, use different base exception

ARUHA-869 Log InvalidStreamException with different log level

---

CHANGELOG.md

https://techjira.zalando.net/browse/ARUHA-912

ARUHA-912: release;

---

docs/_config.yml
docs/_documentation/faq.md
docs/_documentation/getting-started.md
docs/_documentation/recipes.md
docs/_includes/sidebar.html
docs/_sass/_base.scss
docs/_sass/_content.scss
docs/_sass/_parameters.scss
docs/_sass/_sidebar.scss
docs/_sass/_vendor/_syntax-highlight.scss
docs/index.html

ARUHA-906: Merge Documentation
https://techjira.zalando.net/browse/ARUHA-906
Mobile responsive layout implementation and some visual improvements in documentation.

ARUHA-906: Docs responsive layout and styling

---

CHANGELOG.md

ARUHA-979: version for release

ARUHA-979: created version;

---

CHANGELOG.md

aruha-1083 release commit

---

README.md

[ARUHA-XXX: Name of ticket](link to ticket)
A few sentences describing the overall goals of the pull request's
commits.

aruha-1033: test

---

CODE_OF_CONDUCT.md

ARUHA-931: https://techjira.zalando.net/browse/ARUHA-931 Add Code of conduct
Add Code of conduct and correct indention
commits.

Correct Code of conduct

---

docs/_documentation/intro.md
docs/_documentation/using_clients.md
docs/_documentation/using_consuming-events-hila.md
docs/_sass/_content.scss

https://github.com/zalando/nakadi/issues/749
It should
- Fix link to API
- Remove unnecessary link to itself
- Make the links clickable in the "Clients" table and add some styling
- Tests: Not required
- Documentation: Not required
- CHANGELOG: Not required

#749 Fix broken links and add tables style

---

CHANGELOG.md
src/main/java/org/zalando/nakadi/controller/EventStreamController.java
src/main/java/org/zalando/nakadi/filters/LoggingFilter.java
src/main/java/org/zalando/nakadi/util/GzipBodyRequestFilter.java

[ARUHA-1168: Log usage of request body compression](https://techjira.zalando.net/browse/ARUHA-1168)
Added logging of POST requests with compressed body.
<none>

ARUHA-1168: added logging of POST requests with compressed body;

---

CHANGELOG.md

[ARUHA-1168: Log usage of request body compression](https://techjira.zalando.net/browse/ARUHA-1168)
created release version
After deployment we need to update parsers in Scalyr to support new fields in access log

ARUHA-1168: created release version;

---

CHANGELOG.md

aruha-998
[ARUHA-XXX: Name of ticket](link to ticket)
A few sentences describing the overall goals of the pull request's
commits.

aruha-998: release version

---

README.md

[ARUHA-XXX: Name of ticket](link to ticket)
A few sentences describing the overall goals of the pull request's
commits.

aruha-1033: change

---

src/acceptance-test/java/org/zalando/nakadi/repository/kafka/KafkaTestHelper.java
src/main/java/org/zalando/nakadi/repository/kafka/KafkaTopicRepository.java

[ARUHA-1181: Use rack awareness kafka feature in a safe way]
Use rack awareness kafka feature in a safe way
Nakadi change should be deployed before adding rack_id on kafka side.

ARUHA-1181 Use RackAwareMode.Safe while creating topics

---

src/main/java/org/zalando/nakadi/service/timeline/TimelineService.java
src/test/java/org/zalando/nakadi/service/timeline/TimelineServiceTest.java

[ARUHA-984: update et cache on timeline creation](https://techjira.zalando.net/browse/ARUHA-984)

aruha-984: update et cache on timeline creation

---

CHANGELOG.md

[ARUHA-1181: Release version created]

ARUHA-1181 Bump CHANGELOG.md

---

CHANGELOG.md

aruha-984: updated changelog

---

CHANGELOG.md

changelog for 2.2.7

---

CHANGELOG.md

aruha-1203: changelog

---

docs/_documentation/using_clients.md

[ARUHA-774: Add nakacli CLI client to the client list](https://github.com/zalando/nakadi/issues/774)
I've added a row mentioning the project.
Nothing special

Added nakacli CLI client

---

CHANGELOG.md
src/main/java/org/zalando/nakadi/service/subscription/SubscriptionService.java
src/main/java/org/zalando/nakadi/service/subscription/zk/ZkSubscriptionNode.java
src/test/java/org/zalando/nakadi/service/subscription/zk/ZkSubscriptionNodeTest.java

[ARUHA-1313](https://techjira.zalando.net/browse/ARUHA-1313)
Fixed subscription /stats endpoint
Deploy and enjoy

Aruha 1313

---

CHANGELOG.md
docs/_data/nakadi-event-bus-api.yaml
src/acceptance-test/java/org/zalando/nakadi/webservice/BaseAT.java
src/acceptance-test/java/org/zalando/nakadi/webservice/StorageControllerAT.java
src/main/java/org/zalando/nakadi/config/NakadiConfig.java
src/main/java/org/zalando/nakadi/controller/StoragesController.java
src/main/java/org/zalando/nakadi/domain/DefaultStorage.java
src/main/java/org/zalando/nakadi/service/StorageService.java
src/main/java/org/zalando/nakadi/service/timeline/TimelineService.java
src/main/resources/application.yml
src/test/java/org/zalando/nakadi/config/NakadiConfigTest.java
src/test/java/org/zalando/nakadi/controller/StoragesControllerTest.java
src/test/java/org/zalando/nakadi/security/AuthenticationTest.java
src/test/java/org/zalando/nakadi/service/StorageServiceTest.java
src/test/java/org/zalando/nakadi/service/timeline/TimelineServiceTest.java

[aruha-1211: Prescale Kafka](https://techjira.zalando.net/browse/ARUHA-1211)
The ability to change default timeline storage at runtime and by providing env var.

aruha-1211: change default storage

---

src/main/java/org/zalando/nakadi/config/AuthenticationConfig.java
src/main/java/org/zalando/nakadi/config/SecuritySettings.java
src/main/java/org/zalando/nakadi/util/FeatureToggleService.java
src/main/resources/application.yml

[ARUHA-1322: Timeout waiting for connection from pool](https://techjira.zalando.net/browse/ARUHA-1322)
Tests if the change helps to avoid the error

aruha-1322: set max per route open connections to 20

---

CHANGELOG.md

aruha-1322: changelog.md

---

src/acceptance-test/java/org/zalando/nakadi/webservice/EventTypeAT.java
src/main/java/org/zalando/nakadi/service/timeline/TimelineService.java
src/test/java/org/zalando/nakadi/service/timeline/TimelineServiceTest.java

[ARUHA-1335: Not possible to delete event type](https://techjira.zalando.net/browse/ARUHA-1335)

aruha-1335: take all timelines not only active

---

CHANGELOG.md

[ARUHA-1347: Add release notes]

Add release notes header for v2.3.2

---

CHANGELOG.md

ARUHA-1342, ARUHA-1375, ARUHA-1373
Changelog for release

prepare release 2.3.3

---

src/acceptance-test/java/org/zalando/nakadi/webservice/CursorsServiceAT.java
src/main/java/org/zalando/nakadi/domain/NakadiCursor.java
src/main/java/org/zalando/nakadi/domain/Storage.java
src/main/java/org/zalando/nakadi/domain/Timeline.java
src/main/java/org/zalando/nakadi/repository/MultiTimelineEventConsumer.java
src/main/java/org/zalando/nakadi/repository/kafka/KafkaTopicRepository.java
src/main/java/org/zalando/nakadi/service/CursorOperationsService.java
src/main/java/org/zalando/nakadi/service/CursorsService.java
src/main/java/org/zalando/nakadi/service/NakadiCursorComparator.java
src/main/java/org/zalando/nakadi/service/StaticStorageWorkerFactory.java
src/main/java/org/zalando/nakadi/service/converter/CursorConverterImpl.java
src/main/java/org/zalando/nakadi/service/converter/VersionOneConverter.java
src/main/java/org/zalando/nakadi/service/subscription/StreamingContext.java
src/main/java/org/zalando/nakadi/service/subscription/SubscriptionStreamerFactory.java
src/main/java/org/zalando/nakadi/service/subscription/state/ClosingState.java
src/main/java/org/zalando/nakadi/service/subscription/state/PartitionData.java
src/main/java/org/zalando/nakadi/service/subscription/state/State.java
src/main/java/org/zalando/nakadi/service/subscription/state/StreamingState.java
src/main/java/org/zalando/nakadi/service/timeline/TimelineService.java
src/test/java/org/zalando/nakadi/service/NakadiCursorComparatorTest.java
src/test/java/org/zalando/nakadi/service/converter/VersionOneConverterTest.java
src/test/java/org/zalando/nakadi/service/subscription/state/PartitionDataTest.java
src/test/java/org/zalando/nakadi/service/subscription/state/StreamingStateTest.java

[ARUHA-1330: Fix nakadi-cursors comparison and usage of finished timelinest]
2 points to review
- jumping between cursors in cursorconverter
- comparing NakadiCursors with external Comparator
Changelog will be added later, cause anyway I will have merge conflicts.

ARUHA-1330 Fix nakadi-cursors comparison and usage of finished timelines

---

CHANGELOG.md

[ARUHA-1387 Release notes for 2.3.4]

Release notes 2.3.4

---

CHANGELOG.md
src/main/java/org/zalando/nakadi/service/EventTypeService.java
src/main/java/org/zalando/nakadi/service/NakadiKpiPublisher.java
src/main/resources/application.yml
src/test/java/org/zalando/nakadi/controller/EventTypeControllerTestCase.java
src/test/java/org/zalando/nakadi/service/EventTypeServiceTest.java

[ARUHA-1311: Nakadi collects the metric](https://techjira.zalando.net/browse/ARUHA-1311)
This functionality sends KPI metrics for event-types modifications
Feature toggle should be ON.
Should not influence performance as the ET modifications happen not so often.

Aruha 1311 collect et metrics

---

src/main/java/org/zalando/nakadi/controller/CursorsController.java

ARUHA-1398: Reduce logging when user commits with unknown stream ID
HOTFIX - when user commits with unknown stream ID, only log exception message

ARUHA-1398 reduce logging when user committed with unknown stream ID

---

CHANGELOG.md
src/main/java/org/zalando/nakadi/validation/SchemaEvolutionService.java
src/main/java/org/zalando/nakadi/validation/schema/CategoryChangeConstraint.java
src/main/java/org/zalando/nakadi/validation/schema/EnrichmentStrategyConstraint.java
src/main/java/org/zalando/nakadi/validation/schema/PartitionKeyFieldsConstraint.java
src/main/java/org/zalando/nakadi/validation/schema/SchemaEvolutionIncompatibility.java

[ARUHA-1360: Be able to change EventType category from NONE to BUSINESS]
Some people want to be able to change event type category from NONE to BUSINESS.
The simplest way to do it is to allow this change in nakadi

ARUHA-1360 Add crutch for being able to change category of event type from NONE to BUSINESS

---

CHANGELOG.md
src/main/java/org/zalando/nakadi/service/subscription/SubscriptionService.java
src/main/resources/application.yml
src/test/java/org/zalando/nakadi/controller/SubscriptionControllerTest.java
src/test/java/org/zalando/nakadi/service/EventTypeServiceTest.java
src/test/java/org/zalando/nakadi/service/SubscriptionServiceTest.java
src/test/java/org/zalando/nakadi/utils/TestUtils.java

[ARUHA-1428: Collect data as Nakadi event](https://techjira.zalando.net/browse/ARUHA-1428)
Added publishing of subscription log events. Will be used to calculate new subscription count KPI.
-

ARUHA-1428: Added submitting of subscription log events;

---

CHANGELOG.md

[ARUHA-1397: Changes for release creation]

ARUHA-1397 Changelog modification for release

---

CHANGELOG.md
build.gradle
src/main/resources/schema.json

Revert "ARUHA-1275 upgrade json-schema version"

---

src/main/java/org/zalando/nakadi/service/EventTypeService.java
src/test/java/org/zalando/nakadi/service/EventTypeServiceTest.java

[ARUHA-1449: Collect data as Nakadi event](https://techjira.zalando.net/browse/ARUHA-1449)
Nakaid KPI extension for tracking feature adoption

ARUHA-1449: Collect data as Nakadi event

---

CHANGELOG.md
src/main/java/org/zalando/nakadi/validation/schema/diff/ArraySchemaDiff.java
src/main/java/org/zalando/nakadi/validation/schema/diff/CombinedSchemaDiff.java
src/main/java/org/zalando/nakadi/validation/schema/diff/EnumSchemaDiff.java
src/main/java/org/zalando/nakadi/validation/schema/diff/NumberSchemaDiff.java
src/main/java/org/zalando/nakadi/validation/schema/diff/ObjectSchemaDiff.java
src/main/java/org/zalando/nakadi/validation/schema/diff/ReferenceSchemaDiff.java
src/main/java/org/zalando/nakadi/validation/schema/diff/SchemaDiff.java
src/main/java/org/zalando/nakadi/validation/schema/diff/SchemaDiffState.java
src/main/java/org/zalando/nakadi/validation/schema/diff/StringSchemaDiff.java
src/test/java/org/zalando/nakadi/validation/schema/SchemaDiffTest.java
src/test/resources/org/zalando/nakadi/validation/recursive-schema.json

ARUHA-1455 Allow recursive schema validation
Rucursive schemas were dying with stack overflow exception. Right now it should be possible to create and update event types with recursion in the schema

ARUHA-1455 Allow recursive schema validation

---

CHANGELOG.md
docs/_data/nakadi-event-bus-api.yaml
src/acceptance-test/java/org/zalando/nakadi/webservice/hila/HilaAT.java
src/main/java/org/zalando/nakadi/controller/CursorsController.java
src/main/java/org/zalando/nakadi/service/CursorsService.java
src/main/java/org/zalando/nakadi/service/subscription/state/StartingState.java
src/main/java/org/zalando/nakadi/view/EventTypePartitionView.java

ARUHA-1457 Initialize subscription on patch request.
In case, if client wants to PATCH subscription before streaming (initialization of cursors) nakadi will initialize cursors beforehands
No additional stuff to do

ARUHA-1457 Initialize subscription on patch request.

---

CHANGELOG.md
src/main/java/org/zalando/nakadi/controller/EventPublishingController.java
src/main/java/org/zalando/nakadi/controller/EventStreamController.java
src/main/java/org/zalando/nakadi/controller/SubscriptionStreamController.java
src/main/java/org/zalando/nakadi/security/Client.java
src/main/java/org/zalando/nakadi/security/ClientResolver.java
src/main/java/org/zalando/nakadi/security/NakadiClient.java
src/main/java/org/zalando/nakadi/service/EventStream.java
src/main/java/org/zalando/nakadi/service/EventStreamConfig.java
src/main/java/org/zalando/nakadi/service/subscription/StreamParameters.java
src/main/java/org/zalando/nakadi/service/subscription/StreamingContext.java
src/main/java/org/zalando/nakadi/service/subscription/state/StreamingState.java
src/test/java/org/zalando/nakadi/controller/EventStreamControllerTest.java
src/test/java/org/zalando/nakadi/controller/PostSubscriptionControllerTest.java
src/test/java/org/zalando/nakadi/controller/SubscriptionControllerTest.java
src/test/java/org/zalando/nakadi/service/EventPublisherTest.java
src/test/java/org/zalando/nakadi/service/EventStreamTest.java
src/test/java/org/zalando/nakadi/service/subscription/StreamParametersTest.java
src/test/java/org/zalando/nakadi/service/subscription/state/StreamingStateTest.java

The realm is needed to distinguish an employee from an application.
https://techjira.zalando.net/browse/ARUHA-1406

KPI token realm

---

CHANGELOG.md

[ARUHA-1457 : Add release changelog record]

ARUHA-1457 Add release record

---

CHANGELOG.md
build.gradle
src/main/resources/schema.json

Also revert one change in the meta-schema as a result
Second attempt at upgrading the json-schema library, after a regression was found in URI validation

ARUHA-1275 Upgrade json-schema, take 2

---

src/main/resources/application.yml

ARUHA-1488
Changed default features for local env

aruha-1488: changed list of features for local env

---

src/main/java/org/zalando/nakadi/config/AuthenticationConfig.java
src/main/java/org/zalando/nakadi/config/SecurityConfiguration.java
src/main/java/org/zalando/nakadi/service/FeatureToggleServiceZk.java
src/test/java/org/zalando/nakadi/security/RealmModeAuthenticationTest.java

ARUHA-602: Server does not implement Problem JSON for auth errors
Changed error response according Problem Json, when the user is not authorised 
Implement proper logic to support in Nakadi UI

aruha-602: return correct problem json response

---

CHANGELOG.md
src/main/java/org/zalando/nakadi/config/NakadiConfig.java
src/main/java/org/zalando/nakadi/service/NakadiKpiPublisher.java
src/test/java/org/zalando/nakadi/service/NakadiKpiPublisherTest.java

Thread safe usage of MessageDigest
> Zalando ticket : aruha-1518
Thread safe usage of MessageDigest

aruha-1518: thread safe usage of MessageDigest

---

CHANGELOG.md

Release 2.5.9

---

src/main/java/org/zalando/nakadi/service/subscription/state/StreamingState.java

ARUHA-1634 Add detailed log message in case if hake uncommitted timeout happen

ARUHA-1634 Add detailed log message in case if hake uncommitted timeout happen

---

build.gradle

> Zalando ticket : ARUHA-1641
Update curator library, in preparation to upgrade of zookeeper.

ARUHA-1641 Update curator version

---

CHANGELOG.md

ARUHA-1674 Add changelog for release

ARUHA-1674 Add changelog for release

---

CHANGELOG.md

Release 2.7.3
After deploying this version, updates to monitoring data collection are be required.

Release 2.7.3

---

CHANGELOG.md

https://techjira.zalando.net/browse/ARUHA-1739

Release 2.7.5

---

CHANGELOG.md

Changelog record for ARUHA-1750

---

src/main/java/org/zalando/nakadi/controller/PartitionsController.java

ARUHA-1750 
There was a typo in method leading to incorrect stats behavior. Now it is fixed.

ARUHA-1750 Fix typo

---

build.gradle

Remove code not related to opensource project

Remove code not related to opensource project

---

src/acceptance-test/java/org/zalando/nakadi/repository/kafka/KafkaRepositoryAT.java
src/acceptance-test/java/org/zalando/nakadi/repository/kafka/KafkaTestHelper.java
src/main/java/org/zalando/nakadi/exceptions/runtime/TopicConfigException.java
src/main/java/org/zalando/nakadi/repository/KafkaRepositoryCreator.java
src/main/java/org/zalando/nakadi/repository/NakadiTopicConfig.java
src/main/java/org/zalando/nakadi/repository/TopicRepository.java
src/main/java/org/zalando/nakadi/repository/kafka/KafkaTopicConfig.java
src/main/java/org/zalando/nakadi/repository/kafka/KafkaTopicConfigBuilder.java
src/main/java/org/zalando/nakadi/repository/kafka/KafkaTopicConfigFactory.java
src/main/java/org/zalando/nakadi/repository/kafka/KafkaTopicRepository.java
src/main/java/org/zalando/nakadi/service/timeline/TimelineService.java
src/main/resources/application.yml
src/test/java/org/zalando/nakadi/controller/EventTypeControllerTest.java
src/test/java/org/zalando/nakadi/repository/kafka/KafkaTopicRepositoryTest.java
src/test/java/org/zalando/nakadi/service/CursorOperationsServiceTest.java

> Zalando ticket : ARUHA-1757
This enables setting custom properties for compacted topics:
"segment.ms", "segment.bytes", "min.compaction.lag.ms"
-

Aruha 1757 additional topic properties

---

CHANGELOG.md
build.gradle
docker-compose.yml

> Zalando ticket: ARUHA-1798
Upgrade Kafka client library to 1.1.0
Use Kafka 1.1.0 image in docker-compose

ARUHA-1798 Upgrade Kafka client library to 1.1.0

---

CHANGELOG.md

Fix the date in `CHANGELOG.md` for release

Fix date in CHANGELOG.md

---

src/main/java/org/zalando/nakadi/controller/PostSubscriptionController.java

ARUHA-1681 Fix after merge

---

src/main/java/org/zalando/nakadi/service/AuthorizationValidator.java

ARUHA-1681 Fix npe while committing cursors

ARUHA-1681 Fix npe while committing cursors

---

src/main/java/org/zalando/nakadi/controller/CursorsController.java
src/main/java/org/zalando/nakadi/filters/LoggingFilter.java
src/main/java/org/zalando/nakadi/service/ClosedConnectionsCrutch.java
src/main/java/org/zalando/nakadi/service/CursorsService.java
src/main/java/org/zalando/nakadi/service/EventPublisher.java
src/main/java/org/zalando/nakadi/service/EventStream.java
src/main/java/org/zalando/nakadi/service/subscription/LogPathBuilder.java
src/main/java/org/zalando/nakadi/service/subscription/StreamingContext.java
src/main/java/org/zalando/nakadi/service/subscription/SubscriptionService.java
src/main/java/org/zalando/nakadi/service/subscription/SubscriptionStreamerFactory.java
src/main/java/org/zalando/nakadi/service/subscription/state/State.java
src/main/java/org/zalando/nakadi/service/subscription/state/StreamingState.java
src/main/java/org/zalando/nakadi/service/subscription/zk/AbstractZkSubscriptionClient.java
src/main/resources/log4j.properties
src/test/java/org/zalando/nakadi/service/subscription/StreamingContextTest.java
src/test/java/org/zalando/nakadi/service/subscription/state/StreamingStateTest.java

Reduce size of logs of nakadi

---

docs/_documentation/using_clients.md

Add Kanadi (Scala Nakadi client) to the documentation

Add Kanadi client to documentation

---

src/main/java/org/zalando/nakadi/controller/EventTypeController.java
src/main/resources/application.yml
src/test/java/org/zalando/nakadi/controller/EventTypeControllerTest.java

removed newline from warning message

removed newline from warning message

---

README.md

updated kafka version in doc

---

src/main/java/org/zalando/nakadi/service/BlacklistService.java

Remove logging for something that should not be logged

Remove logging for something that should not be logged

---

docs/_sass/_components/_tabs.scss

> Zalando ticket : ARUHA-1993
When you open a link to specific endpoint - you don't see the list of status codes as it is out of bounds.
-

ARUHA-1993: Fixed status code list layout;

---

docs/_data/nakadi-event-bus-api.yaml
src/main/java/org/zalando/nakadi/config/NakadiSettings.java
src/main/java/org/zalando/nakadi/controller/SubscriptionStreamController.java
src/main/java/org/zalando/nakadi/service/CursorsService.java
src/main/java/org/zalando/nakadi/service/subscription/StreamParameters.java
src/main/java/org/zalando/nakadi/view/UserStreamParameters.java
src/main/resources/application.yml
src/test/java/org/zalando/nakadi/service/subscription/StreamParametersTest.java

ARUHA-1978 Be able to specify commit timeout less than 60 seconds

ARUHA-1978 Be able to specify commit timeout less than 60 seconds

---

src/main/java/org/zalando/nakadi/service/subscription/zk/AbstractZkSubscriptionClient.java
src/main/java/org/zalando/nakadi/service/subscription/zk/NewZkSubscriptionClient.java

> Zalando ticket : ARUHA-1996 (only if appropriate)
Added a Warning message and retires for 101 status code

Fix subscription disconnection because of race conditions

---

build.gradle
src/main/resources/application.yml

Revert hikari db pool

---

src/main/java/org/zalando/nakadi/validation/MetadataValidator.java
src/main/java/org/zalando/nakadi/validation/RFC3339DateTimeValidator.java

> Zalando ticket : ARUHA-623
https://jira.zalando.net/browse/ARUHA-623

fixed the validation logging message

---

database/migration/aruha-1265-fix-data-type.sql
database/nakadi/10_data/04_tables/06_authorization.sql
src/main/java/org/zalando/nakadi/repository/db/AuthorizationDbRepository.java

ARUHA-1265 Use correct type for nakadi admins az_operation

ARUHA-1265 Use correct type for nakadi admins az_operation

---

build.gradle

Upgrade Apache Commons Lang3 to 3.8.1

---

.gitignore
build.gradle
src/acceptance-test/java/org/zalando/nakadi/repository/kafka/KafkaRepositoryAT.java
src/main/java/org/zalando/nakadi/repository/kafka/KafkaLocationManager.java
src/main/java/org/zalando/nakadi/repository/kafka/KafkaSettings.java
src/main/java/org/zalando/nakadi/repository/kafka/KafkaTopicRepository.java
src/main/resources/application.yml
src/main/resources/log4j.properties

Updated Kafka client to 2.1.0 and fixed refresh of bootstrap servers

updated kafka client

---

src/main/java/org/zalando/nakadi/config/ValidatorConfig.java
src/main/java/org/zalando/nakadi/domain/SchemaChange.java
src/main/java/org/zalando/nakadi/validation/SchemaEvolutionService.java
src/test/java/org/zalando/nakadi/validation/SchemaEvolutionServiceTest.java

ARUHA-2114 Comparison operation for schema changes should always work on non-null values

ARUHA-2114 Comparison operation for schema changes should always work on non-null values

---

src/main/java/org/zalando/nakadi/repository/MultiTimelineEventConsumer.java

ARUHA-2110 Do not close streaming connections in case of kafka address change

ARUHA-2110 Do not close streaming connections in case of kafka address change

---

docs/_data/nakadi-event-bus-api.yaml

Remove incorrect documentation

Remove incorrect documentation

---

src/main/java/org/zalando/nakadi/domain/ResourceImpl.java

ARUHA-2123: fixed all_data_access constant;

ARUHA-2123: fixed all_data_access constant;

---

src/main/java/org/zalando/nakadi/domain/ResourceAuthorization.java
src/main/java/org/zalando/nakadi/service/AdminService.java

Fixes CME caused by java 8 stream api by using an ImmutableList for cached admins.

Fix CME by using Immutablelist for cached admins

---

src/main/java/org/zalando/nakadi/repository/zookeeper/ZooKeeperHolder.java

ARUHA-2138 Fix shuffling, use different error handling policy for curator

Aruha 2138

---

build.gradle
src/main/java/org/zalando/nakadi/filters/LoggingFilter.java
src/main/java/org/zalando/nakadi/service/subscription/state/StreamingState.java

Log complete exception instead of the message as message is `null` before flush of batch in case client closed connection. (relevant commit: [d90d28d](https://github.com/zalando/nakadi/commit/d90d28d1f1dd41b4b339c7d5cf8c61f9d0adcf43))

Log complete exception in case of IOException

---

build.gradle

https://jira.zalando.net/browse/ARUHA-2262
This ticket has been validated and is read to be merged on master.

Validation rdecillo

---

build.gradle

Reverts zalando/nakadi#1040
This introduced a regression on consumption path which needs to be fixed. From the logs `org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is java.lang.AbstractMethodError: com.fasterxml.jackson.databind.ser.std.ReferenceTypeSerializer.withResolved(Lcom/fasterxml/jackson/databind/BeanProperty;Lcom/fasterxml/jackson/databind/jsontype/TypeSerializer;Lcom/fasterxml/jackson/databind/JsonSerializer;Lcom/fasterxml/jackson/databind/util/NameTransformer;Lcom/fasterxml/jackson/annotation/JsonInclude$Include;)Lcom/fasterxml/jackson/databind/ser/std/ReferenceTypeSerializer;`
Funny thing is that it passed all tests and publishing works fine.

Revert "Validation rdecillo"

---

build.gradle

As a continuation from the protected branches saga, I'm trying this time to merge the changes from a validation branch into master.

Libraries updates

---

src/main/java/org/zalando/nakadi/controller/SubscriptionStreamController.java
src/test/java/org/zalando/nakadi/controller/SubscriptionOutputImplTest.java

Return 409 on request during cursor reset
https://nakadi.io/manual.html#/subscriptions/subscription_id/events_get

return 409 on request during cursor reset

---

src/main/java/org/zalando/nakadi/controller/advice/NakadiProblemExceptionHandler.java

Do not throw 500 on client connection close, during data transmit

Do not throw 500 on client connection close

---

src/main/java/org/zalando/nakadi/controller/SubscriptionStreamController.java

INC-44977: hacky throttle for stups_zalos;

INC-44977: hacky throttle for stups_zalos;

---

src/main/java/org/zalando/nakadi/controller/SubscriptionStreamController.java

INC-44977: reverted changes;

---

src/main/java/org/zalando/nakadi/controller/advice/CursorsExceptionHandler.java

> Zalando ticket : [ARUHA-2289](https://jira.zalando.net/browse/ARUHA-2289)
Handles exception with 422. Causes some 503's on live.

Handle UnableProcessException with 422

---

src/main/java/org/zalando/nakadi/service/subscription/StreamingContext.java
src/main/java/org/zalando/nakadi/service/subscription/state/StartingState.java

log time taken to open the stream and rebalance

log time taken to open the stream and rebalance

---

src/main/java/org/zalando/nakadi/repository/kafka/KafkaLocationManager.java

ARUHA-2326: added extra logging;

ARUHA-2326: added extra logging;

---

src/main/java/org/zalando/nakadi/service/subscription/StreamingContext.java
src/main/java/org/zalando/nakadi/service/subscription/state/StartingState.java

Revert "log time taken to open the stream and rebalance"

---

src/main/java/org/zalando/nakadi/repository/KafkaRepositoryCreator.java
src/main/java/org/zalando/nakadi/repository/zookeeper/ZooKeeperHolder.java
src/main/java/org/zalando/nakadi/repository/zookeeper/ZookeeperConfig.java
src/main/resources/application.yml

Lower zookeeper session timeout

lower zookeeper session timeout

---

src/acceptance-test/java/org/zalando/nakadi/webservice/hila/SubscriptionAT.java
src/main/java/org/zalando/nakadi/service/subscription/zk/AbstractZkSubscriptionClient.java

ARUHA-2330: Delete zk lock node when deleting subscription;

ARUHA-2330: Delete zk lock node when deleting subscription;

---

src/main/java/org/zalando/nakadi/repository/zookeeper/ZooKeeperHolder.java

take connection string from exhib client

take connection string from exhib client

---

src/main/java/org/zalando/nakadi/repository/zookeeper/ZookeeperLock.java

constant timeout on lock retry

constant timeout on lock retry

---

src/acceptance-test/java/org/zalando/nakadi/webservice/CursorsServiceAT.java
src/main/java/org/zalando/nakadi/repository/zookeeper/ZooKeeperHolder.java
src/main/java/org/zalando/nakadi/service/subscription/state/CleanupState.java
src/main/java/org/zalando/nakadi/service/subscription/zk/AbstractZkSubscriptionClient.java
src/main/java/org/zalando/nakadi/service/subscription/zk/NewZkSubscriptionClient.java
src/main/java/org/zalando/nakadi/service/subscription/zk/SubscriptionClientFactory.java
src/main/java/org/zalando/nakadi/service/subscription/zk/ZkSubscriptionClient.java

create curator ensemble and close curator for short commit timeout

create curator ensemble and close curator for short commit timeout

---

src/main/java/org/zalando/nakadi/service/subscription/state/CleanupState.java

close zk session after unregistering session

close zk session after unregistering session

---

src/acceptance-test/java/org/zalando/nakadi/repository/kafka/KafkaRepositoryAT.java
src/main/java/org/zalando/nakadi/repository/kafka/KafkaLocationManager.java
src/main/java/org/zalando/nakadi/repository/kafka/KafkaSettings.java
src/main/resources/application.yml

ARUHA-2414 Increase kafka buffer size

ARUHA-2414 Increase kafka buffer size

---

src/main/java/org/zalando/nakadi/service/AuthorizationValidator.java

Fix mistake of not checking the authorization at all.

Fix mistake of not checking new authorization at all

---

docs/_documentation/using_authorization.md

> Zalando ticket : [ARUHA-2464](https://jira.zalando.net/browse/ARUHA-2464)
Update documentation for subscription authorization.

Update using authorization to reflect subscription authorization

---

src/main/java/org/zalando/nakadi/repository/kafka/KafkaFactory.java

Remove comment for having to set client id.

Remove comment for upgrade action

---

src/main/java/org/zalando/nakadi/controller/CursorOperationsController.java
src/main/java/org/zalando/nakadi/controller/CursorsController.java
src/main/java/org/zalando/nakadi/controller/SchemaController.java
src/main/java/org/zalando/nakadi/domain/PaginationWrapper.java

I found some things that we declare, but never use. They should go away.

Remove unused variables

---

src/main/java/org/zalando/nakadi/service/EventTypeService.java
src/test/java/org/zalando/nakadi/controller/EventTypeControllerTest.java
src/test/java/org/zalando/nakadi/controller/EventTypeControllerTestCase.java
src/test/java/org/zalando/nakadi/service/EventTypeServiceTest.java
src/test/java/org/zalando/nakadi/service/NakadiAuditLogPublisherTest.java
src/test/java/org/zalando/nakadi/utils/EventTypeTestBuilder.java

> Zalando ticket : ARUHA-2533 
https://jira.zalando.net/browse/ARUHA-2534
In order to self increase the partitions, we need to allow users to increase the number of partitions with certain conditions.

Allow users to increase partitions

---

docs/_data/nakadi-event-bus-api.yaml
src/main/java/org/zalando/nakadi/filters/LoggingFilter.java
src/main/java/org/zalando/nakadi/service/AuthorizationValidator.java
src/main/java/org/zalando/nakadi/service/EventPublisher.java
src/main/java/org/zalando/nakadi/service/TracingService.java
src/test/java/org/zalando/nakadi/service/EventPublisherTest.java

Added span context to exchanged in headers
Zalando ticket: ARUHA-2467
Description
This PR  limits tracing only to the validation layer and publishing to Kafka and allows the passing of trace context in headers. 
https://jira.zalando.net/browse/ARUHA-2547

Added span context to exchanged in headers

---

src/main/java/org/zalando/nakadi/filters/LoggingFilter.java
src/main/java/org/zalando/nakadi/repository/kafka/KafkaTopicRepository.java
src/main/java/org/zalando/nakadi/service/EventPublisher.java
src/main/java/org/zalando/nakadi/service/TracingService.java

Zalando ticket: ARUHA-2467
Minor fixes
https://jira.zalando.net/browse/ARUHA-2547

minor fixes in the publishing tracing

---

src/acceptance-test/java/org/zalando/nakadi/webservice/CursorsServiceAT.java
src/main/java/org/zalando/nakadi/config/WebConfig.java
src/main/java/org/zalando/nakadi/controller/CursorsController.java
src/main/java/org/zalando/nakadi/controller/EventPublishingController.java
src/main/java/org/zalando/nakadi/controller/SubscriptionStreamController.java
src/main/java/org/zalando/nakadi/filters/LoggingFilter.java
src/main/java/org/zalando/nakadi/filters/TracingFilter.java
src/main/java/org/zalando/nakadi/repository/kafka/KafkaTopicRepository.java
src/main/java/org/zalando/nakadi/service/CursorsService.java
src/main/java/org/zalando/nakadi/service/EventPublisher.java
src/main/java/org/zalando/nakadi/service/TracingService.java
src/main/java/org/zalando/nakadi/service/subscription/StreamingContext.java
src/main/java/org/zalando/nakadi/service/subscription/SubscriptionStreamerFactory.java
src/main/java/org/zalando/nakadi/service/subscription/state/CleanupState.java
src/main/java/org/zalando/nakadi/service/subscription/state/ClosingState.java
src/main/java/org/zalando/nakadi/service/subscription/state/StartingState.java
src/main/java/org/zalando/nakadi/service/subscription/state/StreamingState.java
src/test/java/org/zalando/nakadi/controller/CursorsControllerTest.java
src/test/java/org/zalando/nakadi/service/CursorsServiceTest.java

https://jira.zalando.net/browse/ARUHA-2547
This PR adds tracing for the consumption and committing of data to Nakadi. This would give the publisher the visibility of their events when publishing to Nakadi.

Added tracing for subscription and commit end points

---

src/main/java/org/zalando/nakadi/controller/SubscriptionStreamController.java
src/main/java/org/zalando/nakadi/filters/TracingFilter.java
src/main/java/org/zalando/nakadi/service/subscription/SubscriptionStreamerFactory.java

Minor fixes in open tracing operation names and log for stream parameters

minor changes in tracing

---

src/acceptance-test/java/org/zalando/nakadi/repository/kafka/KafkaRepositoryAT.java
src/acceptance-test/java/org/zalando/nakadi/webservice/CursorsServiceAT.java
src/main/java/org/zalando/nakadi/controller/CursorsController.java
src/main/java/org/zalando/nakadi/controller/EventPublishingController.java
src/main/java/org/zalando/nakadi/controller/SubscriptionStreamController.java
src/main/java/org/zalando/nakadi/filters/TracingFilter.java
src/main/java/org/zalando/nakadi/repository/TopicRepository.java
src/main/java/org/zalando/nakadi/repository/kafka/KafkaTopicRepository.java
src/main/java/org/zalando/nakadi/service/CursorsService.java
src/main/java/org/zalando/nakadi/service/EventPublisher.java
src/main/java/org/zalando/nakadi/service/TracingService.java
src/main/java/org/zalando/nakadi/service/subscription/state/CleanupState.java
src/main/java/org/zalando/nakadi/service/subscription/state/ClosingState.java
src/main/java/org/zalando/nakadi/service/subscription/state/StartingState.java
src/main/java/org/zalando/nakadi/service/subscription/state/StreamingState.java
src/test/java/org/zalando/nakadi/repository/kafka/KafkaTopicRepositoryTest.java
src/test/java/org/zalando/nakadi/service/CursorsServiceTest.java
src/test/java/org/zalando/nakadi/service/EventPublisherTest.java

Fixes for Open Tracing. 
- Removed maps for tags
- Removed scopes and converted them to Spans
- Changed tracing logging from `warning` to `debug`

Removed log messages and removed scopes

---

docs/_documentation/using_repartitioning.md

Repartitioning documentation

---

src/main/java/org/zalando/nakadi/controller/SubscriptionStreamController.java
src/main/java/org/zalando/nakadi/service/subscription/SubscriptionStreamerFactory.java

Small PR to add additional tags for the stream span

added additional tags for stream span

---

src/main/java/org/zalando/nakadi/repository/kafka/HystrixKafkaCircuitBreaker.java
src/main/java/org/zalando/nakadi/repository/kafka/KafkaTopicRepository.java
src/test/java/org/zalando/nakadi/repository/kafka/KafkaTopicRepositoryTest.java

Revert "added circuit breaker changes and test"

---

delivery.yaml

The file is added only for tests to figure out if it is possible to build image with cdp

Add delivery.yaml

---

src/main/java/org/zalando/nakadi/repository/EventTypeRepository.java
src/main/java/org/zalando/nakadi/repository/db/CachingEventTypeRepository.java
src/main/java/org/zalando/nakadi/repository/db/EventTypeDbRepository.java
src/main/java/org/zalando/nakadi/service/EventTypeService.java
src/main/java/org/zalando/nakadi/service/RepartitioningService.java
src/main/java/org/zalando/nakadi/service/job/TimelineCleanupJob.java
src/main/java/org/zalando/nakadi/service/timeline/TimelineService.java
src/test/java/org/zalando/nakadi/controller/EventTypeControllerTest.java
src/test/java/org/zalando/nakadi/repository/db/CachingEventTypeRepositoryTest.java
src/test/java/org/zalando/nakadi/service/EventTypeServiceTest.java
src/test/java/org/zalando/nakadi/service/job/TimelineCleaningJobTest.java

ARUHA-2637 for some reason it is not allowing to create event type...

Revert "Merge pull request #1126 from zalando/ARUHA-2637"

---

src/main/java/org/zalando/nakadi/service/timeline/TimelineSyncImpl.java

ARUHA-2640: timeout for lock

---

src/acceptance-test/java/org/zalando/nakadi/webservice/hila/HilaDeleteEventsAT.java

The test action were different from the test description.
This pull request is to make the test behave the way it is described

Update AT test to match description

---

src/main/java/org/zalando/nakadi/service/subscription/StreamingContext.java

If there is a `409` response on opening a stream (that is no slots remaining), then un-registering the session (inside `CleanupState.onEnter()`) fails with an exception `NoNodeError`, which again loops the task to `CleanupState` calling `CleanupState.onEnter` indefinitely. This increases the load on zookeeper as the client indefinitely tries to delete a node not present. 
Another alternative implementation to solve the issue would be to handle task of Cleanup separately outside of task queue preventing the repeated `CleanupState.onEnter()` call.

Unregister session only if registered

---

acceptance-test/src/test/java/org/zalando/nakadi/webservice/EventTypeAT.java
core-common/src/main/java/org/zalando/nakadi/view/EventOwnerSelector.java

ARUHA-2663 Fix equals for EventOwnerSelector, add some tests

ARUHA-2663 Fix equals for EventOwnerSelector

---

core-common/src/main/java/org/zalando/nakadi/repository/zookeeper/ChrootedFixedEnsembleProvider.java
core-common/src/main/java/org/zalando/nakadi/repository/zookeeper/ZooKeeperHolder.java

ARUHA-2695 Fix ensemble provider for zookeeper, to support config updates of Zookeeper 3.5.

ARUHA-2695 Fix ensemble provider for zookeeper, to support config updates of Zookeeper 3.5.

---

acceptance-test/build.gradle
acceptance-test/src/acceptance-test/java/org/zalando/nakadi/repository/kafka/KafkaRepositoryAT.java
acceptance-test/src/acceptance-test/java/org/zalando/nakadi/repository/kafka/KafkaTestHelper.java
api-consumption/build.gradle
api-cursors/build.gradle
api-misc/build.gradle
app/build.gradle
app/src/main/resources/application.yml
build.gradle
core-common/build.gradle
core-common/src/main/java/org/zalando/nakadi/repository/kafka/KafkaTopicRepository.java
core-common/src/main/java/org/zalando/nakadi/repository/zookeeper/ZookeeperSettings.java
core-metastore/build.gradle
core-services/build.gradle
docker-compose.yml

Reverts zalando/nakadi#1160 (Revert for having clean master with no staging changes)

Revert "Update Kafka Clients to 2.4.0"

---

core-services/src/main/java/org/zalando/nakadi/cache/ChangeSet.java

Aruha-2738 Fix cache nodes deletion behavior

Aruha-2738 Fix cache nodes deletion behavior

---

core-services/src/main/java/org/zalando/nakadi/cache/EventTypeCache.java

Finally bug was found - I was not calling method that supposed to remember previous state

ARUHA-2738 Fix deletion of zk nodes.

---

acceptance-test/build.gradle
acceptance-test/src/acceptance-test/java/org/zalando/nakadi/repository/kafka/KafkaRepositoryAT.java
acceptance-test/src/acceptance-test/java/org/zalando/nakadi/repository/kafka/KafkaTestHelper.java
api-consumption/build.gradle
api-cursors/build.gradle
api-misc/build.gradle
app/build.gradle
app/src/main/resources/application.yml
build.gradle
core-common/build.gradle
core-common/src/main/java/org/zalando/nakadi/repository/kafka/KafkaTopicRepository.java
core-common/src/main/java/org/zalando/nakadi/repository/zookeeper/ZookeeperSettings.java
core-metastore/build.gradle
core-services/build.gradle
docker-compose.yml

This reverts commit 346273b59a84872a9b792861a9c51ab448bfa235.
Update to new Kafka Client (however, use old library version for zookeeper). Same as https://github.com/zalando/nakadi/pull/1160 (with old zookeeper library - same as Nakadi)

Update Kafka Clients to 2.3.0

---

api-consumption/src/main/java/org/zalando/nakadi/service/subscription/state/StreamingState.java

Add forgotten on commit notification for autocommit

Add forgotten on commit notification for autocommit

---

acceptance-test/build.gradle
acceptance-test/src/acceptance-test/java/org/zalando/nakadi/repository/kafka/KafkaRepositoryAT.java
acceptance-test/src/acceptance-test/java/org/zalando/nakadi/repository/kafka/KafkaTestHelper.java
api-consumption/build.gradle
api-cursors/build.gradle
api-misc/build.gradle
app/build.gradle
app/src/main/resources/application.yml
build.gradle
core-common/build.gradle
core-common/src/main/java/org/zalando/nakadi/repository/kafka/KafkaTopicRepository.java
core-common/src/main/java/org/zalando/nakadi/repository/zookeeper/ZookeeperSettings.java
core-metastore/build.gradle
core-services/build.gradle
docker-compose.yml

Revert "Update Kafka Clients to 2.3.0"

---

api-consumption/src/main/java/org/zalando/nakadi/service/subscription/StreamingContext.java
api-consumption/src/main/java/org/zalando/nakadi/service/subscription/autocommit/AutocommitSupport.java
api-consumption/src/test/java/org/zalando/nakadi/service/subscription/autocommit/AutocommitSupportTest.java

Fix cursor comparison for autocommit

ARUHA-2687 Fix cursor comparison for autocommit

---

app/src/main/java/org/zalando/nakadi/config/MetricsConfig.java
core-common/src/main/java/org/zalando/nakadi/metrics/NakadiMetricsModule.java
core-common/src/main/java/org/zalando/nakadi/metrics/NakadiMetricsServlet.java

Revert "Revert "reduce size of the metrics response short term""

---

docs/_documentation/using_clients.md

Added [Cin](https://github.com/zalando-incubator/clin) to the list of clients in the documentation 
Recently Clin tool was open-sourced and added to the [pypi](https://pypi.org/project/clin/).

Added `Clin` tool to the clients list in the documentation

---

app/src/main/resources/log4j.properties

Reduce logging

---

app/src/main/java/org/zalando/nakadi/service/LoggingReconfigurator.java
docker-compose.yml

ARUHA-2960 Reconfigure logging on the fly from the file

ARUHA-2960 Reconfigure logging on the fly from the file

---

nakadi.sh

Exit with error if build or test fails

exit on error

---

app/build.gradle

Using PropertiesLauncher to support plugins

Using PropertiesLauncher to support plugins

---

acceptance-test/src/acceptance-test/java/org/zalando/nakadi/webservice/hila/SubscriptionAT.java

This tests has been failing too much.
I tried to improve it by changing the order of the assertions. The
purpose of this test is to verify that committing already committed
offset results in 200.
But since it commits offset 25, which does not exist, given the topic
is empty, this may cause the stream to close depending if the commit
arrives before or after the stream code reaches a certain stage.
I kept all the conditions (testing for 200 and 204) but in a way that
we don't have to commit inexistent offset 25. I run it dozens of times
and it doesnt break anymore.

Change the order of assertions to improve test stability

---

acceptance-test/build.gradle
acceptance-test/src/acceptance-test/java/org/zalando/nakadi/webservice/StorageControllerAT.java
acceptance-test/src/acceptance-test/java/org/zalando/nakadi/webservice/hila/SubscriptionAT.java
api-consumption/build.gradle
api-cursors/build.gradle
api-metastore/build.gradle
api-misc/build.gradle
api-publishing/build.gradle
app/build.gradle
build.gradle
checkstyle.xml
core-common/build.gradle
core-common/src/main/java/org/zalando/nakadi/domain/storage/ZookeeperConnection.java
core-metastore/build.gradle
core-services/build.gradle

Upgrading libraries impacted by CVEs.
Most of the security issues wouldn't be exploitable but just to stay on the safe side, we are upgrading all of those which have known security issues.
The current state of dependency management in this project requires some improvement. There's a lot of duplication and editing things often means editing multiple places. But I would leave a reorganization to a different task in order to keep the focus on the upgrades.

Library upgrades mid 2020

---

docs/_documentation/using_event-types.md

Linked to https://github.com/zalando/nakadi/pull/1226

Change doc to reflect new behaviour on schema change

---

core-services/src/main/java/org/zalando/nakadi/ShutdownHooks.java

> Zalando ticket : ARUHA-2959 
Added log to see if ShutdownHooks.onNodeShutdown() method is invoked and completed when a node is terminated.

Added logs to ShutdownHooks.onNodeShutdown

---

docs/_documentation/using_per_event_authorization.md

Simplify a bit documentation and use correct names in example

Simplify a bit documentation and use correct names in example

---

core-services/src/main/java/org/zalando/nakadi/service/StorageService.java

It is not allowed to immediately react on notifications from zookeeper, as it blocks it's address updates, and when session is expired or connection lost - zookeeper becomes unusable.

Fix watchers processing in nakadi default storage listener

---

Dockerfile

Update base image to a library version

Update base image to another one

---

core-common/src/main/java/org/zalando/nakadi/repository/zookeeper/ZooKeeperHolder.java

In order to understand how curator uses zookeeper collection of operations in the logs is done.

Trace curator operations

---

core-common/src/test/java/org/zalando/nakadi/domain/StrictJsonParserTest.java

Break a long line into 2 to respect the style guide

---

docs/_documentation/using_concepts.md

Fix wording of a sentence
One sentence was incorrect in the documentation. This PR aims at fixing the sentence.

Fix wording of a sentence

---

acceptance-test/src/acceptance-test/java/org/zalando/nakadi/repository/kafka/KafkaRepositoryAT.java
acceptance-test/src/acceptance-test/java/org/zalando/nakadi/webservice/CursorsServiceAT.java
api-metastore/src/test/java/org/zalando/nakadi/controller/EventTypeControllerTestCase.java
core-common/src/main/java/org/zalando/nakadi/config/NakadiSettings.java
core-common/src/main/java/org/zalando/nakadi/repository/zookeeper/CuratorFrameworkRotator.java
core-common/src/main/java/org/zalando/nakadi/repository/zookeeper/ZooKeeperHolder.java
core-common/src/test/java/org/zalando/nakadi/repository/zookeeper/CuratorFrameworkRotatorTest.java
core-common/src/test/java/org/zalando/nakadi/service/subscription/zk/NewZkSubscriptionClientTest.java
core-services/src/test/java/org/zalando/nakadi/service/publishing/EventPublisherTest.java

after depromting rotating curator to normal class (not Spring component https://github.com/zalando/nakadi/pull/1288) it was not able to execute @Schedule method.

use scheduled executor for curator rotation thread

---

build.gradle

Upgrade kafka client to 2.7.1

---

acceptance-test/src/acceptance-test/java/org/zalando/nakadi/repository/db/EventTypeDbRepositoryTest.java
acceptance-test/src/acceptance-test/java/org/zalando/nakadi/repository/db/SubscriptionDbRepositoryTest.java
acceptance-test/src/acceptance-test/java/org/zalando/nakadi/repository/db/SubscriptionTokenListerTest.java
acceptance-test/src/acceptance-test/java/org/zalando/nakadi/webservice/EventTypeAT.java
acceptance-test/src/acceptance-test/java/org/zalando/nakadi/webservice/hila/HilaRebalanceAT.java
acceptance-test/src/acceptance-test/java/org/zalando/nakadi/webservice/hila/HilaRepartitionAT.java
acceptance-test/src/acceptance-test/java/org/zalando/nakadi/webservice/hila/SubscriptionAT.java
api-metastore/src/main/java/org/zalando/nakadi/controller/EventTypeController.java
api-metastore/src/main/java/org/zalando/nakadi/controller/SubscriptionController.java
api-metastore/src/main/java/org/zalando/nakadi/model/AuthorizationAttributeQueryParser.java
api-metastore/src/main/java/org/zalando/nakadi/service/EventTypeService.java
api-metastore/src/main/java/org/zalando/nakadi/service/SubscriptionService.java
api-metastore/src/main/java/org/zalando/nakadi/service/SubscriptionsUriHelper.java
api-metastore/src/test/java/org/zalando/nakadi/controller/EventTypeControllerTest.java
api-metastore/src/test/java/org/zalando/nakadi/controller/EventTypeControllerTestCase.java
api-metastore/src/test/java/org/zalando/nakadi/controller/SubscriptionControllerTest.java
api-metastore/src/test/java/org/zalando/nakadi/service/EventTypeServiceTest.java
core-metastore/src/main/java/org/zalando/nakadi/repository/db/EventTypeRepository.java
core-metastore/src/main/java/org/zalando/nakadi/repository/db/SubscriptionDbRepository.java
core-metastore/src/main/java/org/zalando/nakadi/repository/db/SubscriptionTokenLister.java
core-services/src/main/java/org/zalando/nakadi/service/RepartitioningService.java
docs/_data/nakadi-event-bus-api.yaml

> Zalando ticket : GHE-747
Extend API to support GET /event-types?writers=service,user and GET /subscriptions?readers=service,user

Filter subscriptions and event types by authroziation

---

api-consumption/src/main/java/org/zalando/nakadi/service/subscription/StreamingContext.java
api-consumption/src/test/java/org/zalando/nakadi/service/subscription/StreamingContextTest.java

Always clean streaming session in ZooKeeper

---

docs/_data/nakadi-event-bus-api.yaml

> Zalando ticket : team-aruha/issues/752
This is the first step in introducing labels and annotations to the Nakadi API.
Actual implementation will follow the API definition.

Added labels and annotations to the Nakadi API

---

README.md
docker-arm/Dockerfile
docker-arm/README.MD
docker-arm/docker-compose.yml
docker-compose.yml

additional docker compose and docker file to build arm based images

docker arm images

---

api-metastore/src/main/java/org/zalando/nakadi/controller/EventTypeController.java
api-metastore/src/main/java/org/zalando/nakadi/controller/advice/EventTypeExceptionHandler.java
api-metastore/src/main/java/org/zalando/nakadi/controller/advice/PostSubscriptionExceptionHandler.java
api-metastore/src/main/java/org/zalando/nakadi/service/EventTypeService.java
api-metastore/src/main/java/org/zalando/nakadi/service/SubscriptionService.java
api-metastore/src/test/java/org/zalando/nakadi/service/EventTypeServiceTest.java
core-common/src/main/java/org/zalando/nakadi/exceptions/runtime/InvalidOwningApplicationException.java
core-common/src/main/java/org/zalando/nakadi/exceptions/runtime/WrongOwningApplicationException.java
core-services/src/main/java/org/zalando/nakadi/service/SubscriptionValidationService.java
core-services/src/test/java/org/zalando/nakadi/service/SubscriptionValidationServiceTest.java
core-services/src/test/java/org/zalando/nakadi/service/timeline/TimelineSyncImplTest.java

Addresses comments from my own review.

1308 fixes

---

api-misc/src/main/java/org/zalando/nakadi/controller/HealthCheckController.java
api-misc/src/test/java/org/zalando/nakadi/controller/HealthCheckControllerTest.java

health endpoint reports health state even though Nakadi is terminating state. the commit changes the state of the health endpoint by subscribing to shutdown hook.

change health endpoint state when Nakadi shuts down

---

api-consumption/build.gradle
api-cursors/build.gradle
api-misc/build.gradle
app/build.gradle
core-common/build.gradle
core-metastore/build.gradle
core-services/build.gradle

Staying on top of recent changes.
Internal ticket: 508

Upgrade Guava dependency

---

app/src/main/java/org/zalando/nakadi/config/WebConfig.java
app/src/main/java/org/zalando/nakadi/filters/LoggingFilter.java
app/src/main/java/org/zalando/nakadi/filters/RequestRejectedFilter.java
core-common/src/main/java/org/zalando/nakadi/filters/ExtraTracingFilter.java
core-common/src/main/java/org/zalando/nakadi/filters/MonitoringRequestFilter.java
core-common/src/main/java/org/zalando/nakadi/filters/TracingFilter.java

Supersedes #1325
Zalando ticket : 813

Use higher precedence for the request tracing filter

---

acceptance-test/src/acceptance-test/java/org/zalando/nakadi/webservice/hila/SubscriptionAT.java
api-consumption/src/main/java/org/zalando/nakadi/controller/SubscriptionStreamController.java
api-cursors/src/main/java/org/zalando/nakadi/service/CursorsService.java
api-metastore/src/main/java/org/zalando/nakadi/service/SubscriptionService.java
api-metastore/src/test/java/org/zalando/nakadi/controller/SubscriptionControllerTest.java
api-metastore/src/test/java/org/zalando/nakadi/service/SubscriptionServiceTest.java

Revert "increase SubscriptionCache usage."

---

core-metastore/src/main/java/org/zalando/nakadi/repository/db/EventTypeRepository.java

Order returned Event Types by name

---

api-metastore/src/main/java/org/zalando/nakadi/service/EventTypeService.java
api-metastore/src/main/java/org/zalando/nakadi/service/SubscriptionService.java
api-metastore/src/test/java/org/zalando/nakadi/controller/SubscriptionControllerTest.java
api-metastore/src/test/java/org/zalando/nakadi/service/SubscriptionServiceTest.java
core-metastore/src/main/java/org/zalando/nakadi/repository/db/EventTypeRepository.java

Alternate PR for solving issue with orphan subscription caused due to deleting of event type. This PR uses row locks instead of table locks.

Fix orphan subscription

---

app/src/main/java/org/zalando/nakadi/config/WebConfig.java

Fix ordering of request filters wrt. client id availability

---

acceptance-test/src/acceptance-test/java/org/zalando/nakadi/repository/db/SubscriptionDbRepositoryTest.java
api-metastore/src/main/java/org/zalando/nakadi/service/EventTypeService.java
api-metastore/src/main/java/org/zalando/nakadi/service/SubscriptionService.java
api-metastore/src/test/java/org/zalando/nakadi/controller/EventTypeControllerTest.java
api-metastore/src/test/java/org/zalando/nakadi/controller/SubscriptionControllerTest.java
api-metastore/src/test/java/org/zalando/nakadi/service/EventTypeServiceTest.java
core-metastore/src/main/java/org/zalando/nakadi/repository/db/SubscriptionDbRepository.java

Alternate PR for improving list subscription as pagination is not required for dealing with list of subscriptions internally.

Optimize list subscription query

---

app/src/main/java/org/zalando/nakadi/config/NakadiConfig.java

Clean NDC and MDC in the async task executor

---

core-common/src/main/java/org/zalando/nakadi/service/AvroSchema.java

rename variable path

---

acceptance-test/src/acceptance-test/java/org/zalando/nakadi/webservice/hila/SubscriptionAT.java
api-consumption/src/main/java/org/zalando/nakadi/controller/SubscriptionStreamController.java
api-cursors/src/main/java/org/zalando/nakadi/service/CursorsService.java
api-metastore/src/main/java/org/zalando/nakadi/service/SubscriptionService.java
api-metastore/src/test/java/org/zalando/nakadi/controller/SubscriptionControllerTest.java
api-metastore/src/test/java/org/zalando/nakadi/service/SubscriptionServiceTest.java

This PR reverts a previous revert https://github.com/zalando/nakadi/pull/1337.

Use Subscription cache to improve read performance

---

api-consumption/build.gradle
app/build.gradle
core-common/build.gradle
core-metastore/build.gradle
core-services/build.gradle

Upgrade postgresql driver

---

core-common/src/main/java/org/zalando/nakadi/repository/kafka/KafkaTopicRepository.java

Log warning when publishing order is violated

---

core-common/src/main/java/org/zalando/nakadi/repository/kafka/KafkaTopicRepository.java
core-common/src/test/java/org/zalando/nakadi/repository/kafka/KafkaTopicRepositoryTest.java

The import gone missing as more stuff was merged in between.

Fix compilation after merging #1363

---

core-common/src/main/java/org/zalando/nakadi/repository/kafka/AvroDeserializerWithSequenceDecoder.java
core-common/src/main/java/org/zalando/nakadi/repository/kafka/KafkaRecordDeserializer.java
core-common/src/main/java/org/zalando/nakadi/repository/kafka/SequenceDecoder.java

Introducing SequenceDecoder for Avro

---

core-services/src/main/java/org/zalando/nakadi/service/AuthorizationValidator.java

Include reason for auth error in response

Include reason for auth error in response

---

core-services/src/main/java/org/zalando/nakadi/partitioning/HashPartitionStrategy.java
core-services/src/test/java/org/zalando/nakadi/partitioning/HashPartitionStrategyTest.java

Derive the absolute value at the very end of the operation when doing hash partitioning

---

core-common/src/main/resources/event-type-schema/_metadata/_metadata.2.avsc
core-services/src/main/java/org/zalando/nakadi/service/publishing/NakadiKpiPublisher.java
core-services/src/test/java/org/zalando/nakadi/service/publishing/EventPublisherTest.java

partition should be string as it is for JSON schema

partition as a string

---

app/src/main/resources/application.yml

Config file processing has changed since Spring Boot 2.4 and this PR handles the change accordingly

Configure new spring version properly

---

core-common/src/main/java/org/zalando/nakadi/service/KPIEventMapper.java
core-common/src/test/java/org/zalando/nakadi/service/KPIEventMapperTest.java

> Zalando ticket : team-aruha/issues/984

Improving getter inference logic in KPIEventMapper

---

api-publishing/src/main/java/org/zalando/nakadi/EventPublishingController.java

Revert content type for json payloads, it could bring more harm than benefit at the moment.

revert content type

---

core-common/src/main/java/org/zalando/nakadi/domain/GenericRecordMetadata.java
core-common/src/main/java/org/zalando/nakadi/domain/NakadiMetadata.java
core-common/src/test/java/org/zalando/nakadi/repository/kafka/KafkaTopicRepositoryTest.java
core-services/src/test/java/org/zalando/nakadi/service/publishing/check/CheckTest.java

> Zalando ticket : team-aruha/issues/1100

Added methods to NakadiMetadata

---

core-common/src/main/java/org/zalando/nakadi/domain/GenericRecordMetadata.java
core-common/src/main/java/org/zalando/nakadi/domain/NakadiMetadata.java
core-common/src/main/java/org/zalando/nakadi/repository/kafka/AvroDeserializerWithSequenceDecoder.java
core-common/src/main/resources/event-type-schema/_metadata/_metadata.4.avsc
core-common/src/test/java/org/zalando/nakadi/repository/kafka/KafkaRecordDeserializerTest.java
core-common/src/test/java/org/zalando/nakadi/repository/kafka/KafkaTopicRepositoryTest.java
core-services/src/main/java/org/zalando/nakadi/service/publishing/NakadiKpiPublisher.java
core-services/src/main/java/org/zalando/nakadi/service/publishing/check/EventTypeCheck.java
core-services/src/test/java/org/zalando/nakadi/service/publishing/EventPublisherTest.java
core-services/src/test/java/org/zalando/nakadi/service/publishing/NakadiBatchMapperTest.java
core-services/src/test/java/org/zalando/nakadi/service/publishing/check/CheckTest.java

Fix schema version field name in event metadata

---

core-common/src/main/java/org/zalando/nakadi/domain/NakadiRecord.java
core-common/src/main/java/org/zalando/nakadi/domain/NakadiRecordResource.java
core-services/src/main/java/org/zalando/nakadi/service/AuthorizationValidator.java

> Zalando ticket : team-aruha/issues/1106

Serialize enriched metadata - Part 2

---

core-services/src/main/java/org/zalando/nakadi/service/publishing/NakadiKpiPublisher.java

Set flow-id when creating KPI events
> Zalando ticket : team-aruha/issues/1106

Set flow-id when creating KPI events

---

core-services/src/main/java/org/zalando/nakadi/service/SchemaEvolutionService.java
core-services/src/test/java/org/zalando/nakadi/validation/SchemaEvolutionServiceTest.java

Allowing such a change would complicate the things even more.

Prevent schema type change from Avro to JSON

---

acceptance-test/src/acceptance-test/java/org/zalando/nakadi/webservice/hila/HilaRebalanceAT.java
nakadi.sh

- Fix a bug in a test
- Print Nakadi logs when tests are failing

Fix buggy acceptance test

---

core-services/src/main/java/org/zalando/nakadi/repository/kafka/AvroDeserializerWithSequenceDecoder.java

revert migration step
to be deployed in 4 days

revert migration step

---

docs/_data/nakadi-event-bus-api.yaml

nakadi schemas retrieval api

---

docs/_data/nakadi-event-bus-api.yaml

separate path to get avro schema version

separate path to get avro schema version

---

app/src/main/java/org/zalando/nakadi/filters/LoggingFilter.java
core-common/src/main/java/org/zalando/nakadi/filters/TracingFilter.java

There was a long-standing copy-paste issue.

Fix tagging tracing spans with content- and accept-encoding

---

core-common/src/main/java/org/zalando/nakadi/domain/Timeline.java
core-common/src/main/java/org/zalando/nakadi/partitioning/PartitionStrategy.java
core-services/src/main/java/org/zalando/nakadi/cache/EventTypeCache.java
core-services/src/main/java/org/zalando/nakadi/partitioning/HashPartitionStrategy.java
core-services/src/main/java/org/zalando/nakadi/partitioning/PartitionResolver.java
core-services/src/main/java/org/zalando/nakadi/service/RepartitioningService.java
core-services/src/main/java/org/zalando/nakadi/service/publishing/EventPublisher.java
core-services/src/main/java/org/zalando/nakadi/service/publishing/check/PartitioningCheck.java
core-services/src/main/java/org/zalando/nakadi/service/timeline/TimelineService.java
core-services/src/test/java/org/zalando/nakadi/cache/EventTypeCacheTest.java
core-services/src/test/java/org/zalando/nakadi/partitioning/PartitionResolverTest.java
core-services/src/test/java/org/zalando/nakadi/service/CursorOperationsServiceTest.java
core-services/src/test/java/org/zalando/nakadi/service/publishing/EventPublisherTest.java

Move sorting out of the hot path on batch publishing.
Based on findings from #1398

Cache ordered partitions per event type

---

api-consumption/src/main/java/org/zalando/nakadi/controller/SubscriptionStreamController.java
api-consumption/src/main/java/org/zalando/nakadi/service/subscription/StreamingContext.java
api-consumption/src/main/java/org/zalando/nakadi/service/subscription/state/StreamingState.java
core-services/src/main/java/org/zalando/nakadi/cache/EventTypeCache.java

Reduce logging of common harmless messages

---

core-common/src/main/java/org/zalando/nakadi/filters/TracingFilter.java
core-common/src/main/java/org/zalando/nakadi/service/TracingService.java
core-services/src/main/java/org/zalando/nakadi/service/publishing/EventPublisher.java

Use correct tracing tags for errors.

Correct use of tracing error tag

---

core-common/src/main/java/org/zalando/nakadi/metrics/EventTypeMetrics.java
core-services/src/main/java/org/zalando/nakadi/service/publishing/EventPublisher.java
core-services/src/test/java/org/zalando/nakadi/service/publishing/EventPublisherTest.java

To get more detailed insights.

Collect event key metrics per event type

---

api-consumption/src/main/java/org/zalando/nakadi/service/subscription/state/PartitionData.java

Fix checkstyle 🎁

---

core-common/src/main/java/org/zalando/nakadi/repository/kafka/KafkaTopicRepository.java
core-services/src/main/java/org/zalando/nakadi/service/publishing/EventPublisher.java

the commit adds ability to track latency on publishing path in more granular way. that should help with debugging latency issues.

track publishing latency

---

core-common/src/main/java/org/zalando/nakadi/repository/kafka/KafkaTopicRepository.java

the change should help to analyse how long it takes for kafka to process the batch and understand if latency comes from the producer

measure wait for the batch sent to kafka

---

delivery.yaml

Make sure that the cache checksum is stable.

Follow official Gradle cache procedure

---

build.gradle

We are after this bugfix: https://issues.apache.org/jira/browse/KAFKA-14194

Upgrade kafka-client to v3.3.2

---

acceptance-test/src/acceptance-test/java/org/zalando/nakadi/repository/kafka/KafkaRepositoryAT.java
core-common/src/main/java/org/zalando/nakadi/domain/BatchItem.java
core-common/src/main/java/org/zalando/nakadi/repository/kafka/KafkaFactory.java
core-common/src/main/java/org/zalando/nakadi/repository/kafka/KafkaTopicRepository.java
core-common/src/test/java/org/zalando/nakadi/repository/kafka/KafkaFactoryTest.java
core-common/src/test/java/org/zalando/nakadi/repository/kafka/KafkaTopicRepositoryTest.java

that's needed to distribute partitions accross different producers it helps to unload served partitions by single producer

choose producer based on the topic 

---

core-common/src/main/java/org/zalando/nakadi/repository/kafka/KafkaTopicRepository.java

take producer based on the topic partition hashing that helps to distribute paratitions evenly between producers

use producer per topic partition hash

---

core-services/src/main/java/org/zalando/nakadi/service/publishing/EventPublisher.java
core-services/src/test/java/org/zalando/nakadi/service/publishing/EventPublisherTest.java

use event type name for partitions statistic

use event type name

---

acceptance-test/src/acceptance-test/java/org/zalando/nakadi/repository/kafka/KafkaRepositoryAT.java
app/src/main/resources/application.yml
core-common/src/main/java/org/zalando/nakadi/repository/kafka/KafkaLocationManager.java
core-common/src/main/java/org/zalando/nakadi/repository/kafka/KafkaSettings.java

in some case tcp send buffer can be a bottle neck

configure tcp send buffer

---

core-services/src/main/java/org/zalando/nakadi/service/timeline/MultiTimelineEventConsumer.java

log consumer closure

---

api-metastore/src/main/java/org/zalando/nakadi/service/SubscriptionTimeLagService.java
core-services/src/main/java/org/zalando/nakadi/service/timeline/MultiTimelineEventConsumer.java

more logs for consumer usage in time lag calculation

more logs for consumer usage in time lag calculation

---

api-metastore/src/main/java/org/zalando/nakadi/service/SubscriptionTimeLagService.java
core-common/src/main/java/org/zalando/nakadi/repository/kafka/KafkaFactory.java

Fix logging around timelag checking

---

core-common/src/main/java/org/zalando/nakadi/annotations/validation/AnnotationKey.java
core-common/src/main/java/org/zalando/nakadi/annotations/validation/AnnotationValue.java
core-common/src/main/java/org/zalando/nakadi/annotations/validation/DataLakeAnnotationValidator.java
core-common/src/main/java/org/zalando/nakadi/annotations/validation/DataLakeValidAnnotations.java
core-common/src/main/java/org/zalando/nakadi/domain/EventTypeBase.java
core-common/src/test/java/org/zalando/nakadi/annotations/validation/DataLakeAnnotationsTest.java

Validate some annotations according to their format and dependence

Validate datalake annotations

---

core-common/src/main/java/org/zalando/nakadi/repository/KafkaRepositoryCreator.java
core-common/src/main/java/org/zalando/nakadi/repository/kafka/KafkaFactory.java
core-common/src/test/java/org/zalando/nakadi/repository/kafka/KafkaFactoryTest.java

Related to on-going investigation of publishing latency.

Record Kafka consumer create rate

---

api-consumption/src/main/java/org/zalando/nakadi/controller/EventStreamController.java
api-consumption/src/main/java/org/zalando/nakadi/service/EventStream.java
api-consumption/src/main/java/org/zalando/nakadi/service/EventStreamFactory.java
api-consumption/src/main/java/org/zalando/nakadi/service/subscription/state/StreamingState.java
api-consumption/src/test/java/org/zalando/nakadi/controller/EventStreamControllerTest.java
api-consumption/src/test/java/org/zalando/nakadi/service/EventStreamTest.java
api-consumption/src/test/java/org/zalando/nakadi/service/subscription/state/StreamingStateTest.java
api-metastore/src/main/java/org/zalando/nakadi/service/SubscriptionTimeLagService.java
api-metastore/src/test/java/org/zalando/nakadi/service/SubscriptionTimeLagServiceTest.java
core-common/src/main/java/org/zalando/nakadi/repository/HighLevelConsumer.java
core-common/src/main/java/org/zalando/nakadi/repository/LowLevelConsumer.java
core-common/src/main/java/org/zalando/nakadi/repository/TopicRepository.java
core-common/src/main/java/org/zalando/nakadi/repository/kafka/KafkaTopicRepository.java
core-common/src/main/java/org/zalando/nakadi/repository/kafka/NakadiKafkaConsumer.java
core-common/src/test/java/org/zalando/nakadi/repository/kafka/NakadiKafkaConsumerTest.java
core-services/src/main/java/org/zalando/nakadi/service/timeline/HighLevelConsumer.java
core-services/src/main/java/org/zalando/nakadi/service/timeline/MultiTimelineEventConsumer.java
core-services/src/main/java/org/zalando/nakadi/service/timeline/TimelineService.java

the commits removes confusion in the layer between Kafka consumer and Nakadi consumer

separate kafka consumer from nakadi consumer

---

core-common/src/main/java/org/zalando/nakadi/annotations/validation/DataLakeAnnotationValidator.java
core-common/src/test/java/org/zalando/nakadi/annotations/validation/DataLakeAnnotationsTest.java

> Zalando ticket : 
https://jira.zalando.net/browse/ZDLK-5077
extension of Validate datalake annotations (#1509 )
The validations for annotations were extended to meet these constraints 
https://docs.google.com/document/d/1YkX9VYxntvAQj0qSCVVpgqLxOoAv4HZhJIyh7EWMwg8/edit#

ZDLK-5077 update the validations for datalake annotations

---

core-services/src/main/java/org/zalando/nakadi/cache/EventTypeCache.java

improve logging in event type cache

improve logging in event type cache

---

core-common/src/main/java/org/zalando/nakadi/repository/kafka/KafkaTopicRepository.java

When a topic is just created, describing it immediately may fail with `UnknownTopicOrPartitionException` (wrapped in an `ExecutionException` due to use of futures).

Fix retry in `listPartitionNames`

---

core-common/build.gradle

In version 1.5.4 was significant performance improvement and in 1.5.5 memory utilisation improvements

upgrade ZSTD to use latest version 

---

api-consumption/src/main/java/org/zalando/nakadi/service/subscription/StreamingContext.java
api-consumption/src/main/java/org/zalando/nakadi/service/subscription/SubscriptionStreamerFactory.java
api-consumption/src/test/java/org/zalando/nakadi/service/subscription/StreamingContextTest.java
core-common/src/main/java/org/zalando/nakadi/domain/Feature.java

Add feature flag for filtering of misplaced events

---

api-consumption/src/main/java/org/zalando/nakadi/service/subscription/StreamingContext.java
api-consumption/src/main/java/org/zalando/nakadi/service/subscription/SubscriptionStreamerFactory.java
api-consumption/src/test/java/org/zalando/nakadi/service/subscription/StreamingContextTest.java
core-common/src/main/java/org/zalando/nakadi/domain/Feature.java
core-services/src/main/java/org/zalando/nakadi/repository/kafka/KafkaRecordDeserializer.java

Add functionality to skip events while consuming that do match the event types found in subscription.

Add code for skipping events that do not match intended event type

---

acceptance-test/src/acceptance-test/java/org/zalando/nakadi/webservice/hila/HilaAT.java
api-consumption/src/main/java/org/zalando/nakadi/service/subscription/state/StreamingState.java

reducing batch limit per partition to avoid throttling healthy partitions

reduce batch limit per partition

---

app/src/main/java/org/zalando/nakadi/service/job/DlqRedriveEventTypeAttachmentJob.java
app/src/main/resources/application.yml
app/src/test/java/org/zalando/nakadi/service/job/DlqRedriveEventTypeAttachmentJobTest.java
core-common/src/main/java/org/zalando/nakadi/domain/Feature.java
core-common/src/main/java/org/zalando/nakadi/service/subscription/zk/AbstractZkSubscriptionClient.java
core-common/src/main/java/org/zalando/nakadi/service/subscription/zk/ZkSubscriptionClient.java

Add periodic exclusive job to attach DLQ redrive event type

---

core-services/src/main/java/org/zalando/nakadi/service/RepartitioningService.java

Workaround for non-working re-partitioning of event type for the DLQ redrive event type (sine the latter is consumed by subscriptions implicitly).

Workaround: disallow re-partitioning the DLQ redrive event type.

---

api-consumption/src/main/java/org/zalando/nakadi/service/subscription/state/StreamingState.java
core-common/src/main/java/org/zalando/nakadi/service/subscription/model/Partition.java

More readable DLQ debug information

---

acceptance-test/src/acceptance-test/java/org/zalando/nakadi/webservice/hila/HilaAT.java
api-consumption/src/main/java/org/zalando/nakadi/service/subscription/state/StreamingState.java
api-cursors/src/main/java/org/zalando/nakadi/service/CursorsService.java
core-common/src/main/java/org/zalando/nakadi/service/subscription/model/Partition.java
core-common/src/main/java/org/zalando/nakadi/service/subscription/zk/ZkSubscriptionClient.java

> Zalando ticket : ARUHA-1531
A few sentences describing the overall goals of the pull request's
commits.

Dlq cursor reset

---

acceptance-test/src/acceptance-test/java/org/zalando/nakadi/webservice/hila/HilaAT.java
api-consumption/src/main/java/org/zalando/nakadi/service/subscription/state/StreamingState.java
api-cursors/src/main/java/org/zalando/nakadi/service/CursorsService.java
core-common/src/main/java/org/zalando/nakadi/service/subscription/model/Partition.java

Supersedes: https://github.com/zalando/nakadi/pull/1576

Fix to not override existing last dead letter offset

---

acceptance-test/src/acceptance-test/java/org/zalando/nakadi/webservice/hila/HilaAT.java

Fix method args so build is successfull

add maxEventsSendCount

---

core-common/src/main/java/org/zalando/nakadi/repository/kafka/KafkaTopicRepository.java
core-services/src/main/java/org/zalando/nakadi/service/publishing/EventPublisher.java

in order to have ability to confirm if event landed in the desired topic

temproraly adding topic to kafka record
